#!/bin/csh

setenv LSB_JOB_REPORT_MAIL N

setenv LOCALDIR `pwd`
setenv EXECDIR DIR_MEMEXEC

setenv LC_ALL "en_US.UTF-8"

setenv LHAPDF DIR_LHAPDF
setenv LHAPATH $LHAPDF/share/LHAPDF/
setenv LHAPDF_BIN $LHAPDF/bin
setenv PATH ${PATH}:${LHAPDF_BIN}
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:$LHAPDF/lib

setenv ROOTSYS /usr/bin/root
rehash

cd ${LOCALDIR}

${EXECDIR}/./test INPUTFILE NMIN NMAX --MEMRun DIR_JOBS/Jobs_OPTION/config.cfg > log_PROC_OPTION_NUM

ls 

#cp log_PROC_OPTION_NUM DIR_JOBS/Jobs_OPTION/
cp output.root DIR_JOBS/Jobs_OPTION/output_PROC_OPTION_NUM.root
