// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : mdjordje
Date           : Tue Feb 23 10:34:20 2016
Host           : Linux vocms0301.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/m/mdjordje/CMSSW_7_6_3/src/CMGTools/TTHAnalysis/macros/finalMVA/2lss
Training events: 29641
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "0.3373713.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]])) max_Lep_eta                                                    max_Lep_eta                                                    max_Lep_eta                                                                                                                       'F'    [0.00620277225971,2.49962472916]
MT_met_lep1                   MT_met_lep1                   MT_met_lep1                   MT_met_lep1                                                     'F'    [0.0119199827313,1002.06994629]
nJet25_Recl                   numJets_float                 numJets_float                 numJets_float                                                   'F'    [1,14]
mhtJet25_Recl                 mhtJet25                      mhtJet25                      mhtJet25                                                        'F'    [0.200734004378,1020.82086182]
avg_dr_jet                    avg_dr_jet                    avg_dr_jet                    avg_dr_jet                                                      'F'    [0,4.9854631424]
mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                                                  'F'    [0.268908649683,5.08621120453]
mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                                                  'F'    [0.262473642826,5.3324174881]
NSpec 3
iF_Recl[0]                    iF0                           iF0                           F                                                               'F'    [0,4]
iF_Recl[1]                    iF1                           iF1                           F                                                               'F'    [0,4]
iF_Recl[2]                    iF2                           iF2                           F                                                               'F'    [0,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]]))", "MT_met_lep1", "nJet25_Recl", "mhtJet25_Recl", "avg_dr_jet", "mindr_lep1_jet", "mindr_lep2_jet" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0380131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.019854) , 
2, 1.00498, 1, 0, 0.251873,-0.248127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540212,0.00612388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707046,0.0390925) , 
2, 3.05473, 1, 0, 0.647636,0.147636) , 
2, 2.03483, 1, 0, 0.5,3.92763e-14)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0361867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.018657) , 
2, 1.00498, 1, 0, 0.251873,-0.234729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594449,0.0136285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758016,0.0483618) , 
2, 4.0398, 1, 0, 0.647636,0.133966) , 
2, 2.03483, 1, 0, 0.5,-0.00357241)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0345406) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0175447) , 
4, 0.0248033, 1, 0, 0.251873,-0.222074) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692268,0.0302232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532142,0.00111863) , 
0, 1.59405, 1, 0, 0.647636,0.121543) , 
2, 2.03483, 1, 0, 0.5,-0.00664031)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0330453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0165085) , 
2, 1.00498, 1, 0, 0.251873,-0.210117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540212,0.00299677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707046,0.0306305) , 
2, 3.05473, 1, 0, 0.647636,0.110548) , 
2, 2.03483, 1, 0, 0.5,-0.00907338)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0316777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0155408) , 
4, 0.0248033, 1, 0, 0.251873,-0.198818) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692193,0.0269019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545041,1.37463e-05) , 
4, 2.42322, 1, 0, 0.647636,0.100273) , 
2, 2.03483, 1, 0, 0.5,-0.0113)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0304187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0146355) , 
2, 1.00498, 1, 0, 0.251873,-0.188139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.69099,0.0239573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528989,-0.00243283) , 
0, 1.61886, 1, 0, 0.647636,0.0910237) , 
2, 2.03483, 1, 0, 0.5,-0.0131154)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0292529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0137872) , 
4, 0.0248033, 1, 0, 0.251873,-0.178044) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540212,0.000194505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.707046,0.0247517) , 
2, 3.05473, 1, 0, 0.647636,0.0827463) , 
2, 2.03483, 1, 0, 0.5,-0.0145394)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0281676) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.012991) , 
4, 0.0248033, 1, 0, 0.251873,-0.168501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692193,0.0216914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545041,-0.00235569) , 
4, 2.42322, 1, 0, 0.647636,0.0749834) , 
2, 2.03483, 1, 0, 0.5,-0.0158465)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0271523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0122429) , 
4, 0.0248033, 1, 0, 0.251873,-0.159478) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.686127,0.0186007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517833,-0.00618782) , 
0, 1.7057, 1, 0, 0.647636,0.0680057) , 
2, 2.03483, 1, 0, 0.5,-0.0168553)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0261981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0115394) , 
2, 1.00498, 1, 0, 0.251873,-0.150946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594449,0.00367256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758016,0.030815) , 
2, 4.0398, 1, 0, 0.647636,0.0617889) , 
2, 2.03483, 1, 0, 0.5,-0.0175701)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0252976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0108772) , 
2, 1.00498, 1, 0, 0.251873,-0.142878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693372,0.017187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535518,-0.0045899) , 
0, 1.56924, 1, 0, 0.647636,0.055872) , 
2, 2.03483, 1, 0, 0.5,-0.0182698)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0244444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.0102534) , 
4, 0.0248033, 1, 0, 0.251873,-0.135247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693547,0.0170183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549328,-0.00438995) , 
4, 2.40545, 1, 0, 0.647636,0.0507244) , 
2, 2.03483, 1, 0, 0.5,-0.0186504)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0236333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43672,-0.00698924) , 
2, 1.00995, 1, 0, 0.35983,-0.0887055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768253,0.0301438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654888,0.00744792) , 
4, 2.18111, 1, 0, 0.707046,0.0840287) , 
2, 3.00498, 1, 0, 0.5,-0.0189734)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.215768,-0.0183934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.372235,-0.00126939) , 
3, 111.965, 1, 0, 0.251873,-0.122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689755,0.0149806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565443,-0.0046883) , 
5, 1.40829, 1, 0, 0.647636,0.0418116) , 
2, 2.03483, 1, 0, 0.5,-0.0192969)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0223678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43672,-0.00627705) , 
4, 0.0248033, 1, 0, 0.35983,-0.0806035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742478,0.0205386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.579303,-0.00308107) , 
0, 1.70559, 1, 0, 0.707046,0.0713683) , 
2, 3.00498, 1, 0, 0.5,-0.0192531)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.021648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.00810897) , 
4, 0.0248033, 1, 0, 0.251873,-0.109864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611039,0.000210582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727137,0.0214426) , 
3, 116.988, 1, 0, 0.647636,0.0345372) , 
2, 2.03483, 1, 0, 0.5,-0.0193305)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314703,-0.014085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48583,0.0035018) , 
3, 111.965, 1, 0, 0.35983,-0.0735106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.762916,0.0226206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644072,0.00302348) , 
0, 1.18461, 1, 0, 0.707046,0.0611271) , 
2, 3.00498, 1, 0, 0.5,-0.0191579)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.0206167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336376,-0.00710195) , 
4, 0.0248033, 1, 0, 0.251873,-0.0995342) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.692193,0.0118645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545041,-0.00645415) , 
4, 2.42322, 1, 0, 0.647636,0.0289783) , 
2, 2.03483, 1, 0, 0.5,-0.0189621)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649622,0.0107214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344213,-0.0136143) , 
6, 1.97708, 1, 0, 0.60441,0.0342672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32034,-0.0155584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568327,0.00693125) , 
3, 122.066, 1, 0, 0.365119,-0.0873044) , 
5, 1.46724, 1, 0, 0.5,-0.0187785)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.090934,-0.0221958) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.192045,-0.0109779) , 
1, 148.015, 1, 0, 0.115589,-0.156885) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521418,-0.00398698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666686,0.0141931) , 
3, 116.988, 1, 0, 0.564026,0.00471552) , 
4, 0.0248033, 1, 0, 0.5,-0.0183572)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334082,-0.01163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4781,0.00653115) , 
1, 167.667, 1, 0, 0.35983,-0.0631276) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768253,0.0219063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654888,0.00228472) , 
4, 2.18111, 1, 0, 0.707046,0.0492183) , 
2, 3.00498, 1, 0, 0.5,-0.017774)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649622,0.00949664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344213,-0.0126031) , 
6, 1.97708, 1, 0, 0.60441,0.0295605) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326322,-0.0136921) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596975,0.00869391) , 
3, 132.221, 1, 0, 0.365119,-0.0782383) , 
5, 1.46724, 1, 0, 0.5,-0.0174756)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0196464) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,-0.000768649) , 
1, 213.787, 1, 0, 0.115589,-0.141673) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607192,0.00530992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450582,-0.00972374) , 
0, 1.63127, 1, 0, 0.564026,0.00372549) , 
4, 0.0248033, 1, 0, 0.5,-0.017034)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634838,0.00733824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324158,-0.0129941) , 
6, 1.99852, 1, 0, 0.587853,0.0193467) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281895,-0.0150391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528924,0.00263921) , 
3, 111.965, 1, 0, 0.335988,-0.0832976) , 
5, 1.65898, 1, 0, 0.5,-0.0164565)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0187194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,-0.000305042) , 
1, 213.787, 1, 0, 0.115589,-0.130569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540633,-0.00189797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740053,0.0237406) , 
3, 167.765, 1, 0, 0.564026,0.00304874) , 
2, 1.06468, 1, 0, 0.5,-0.0160287)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672902,0.0106232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42407,-0.00796345) , 
6, 1.6556, 1, 0, 0.613092,0.0283436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328081,-0.0123303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548572,0.00346213) , 
3, 111.91, 1, 0, 0.379552,-0.0622279) , 
5, 1.37138, 1, 0, 0.5,-0.0155157)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330227,-0.0105193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.451948,0.00401959) , 
1, 149.544, 1, 0, 0.35983,-0.0510025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768253,0.0187417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.654888,0.000830788) , 
4, 2.18111, 1, 0, 0.707046,0.0379359) , 
2, 3.00498, 1, 0, 0.5,-0.0150984)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0891181,-0.0190821) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193958,-0.00846191) , 
3, 100.355, 1, 0, 0.115589,-0.118462) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602726,0.00425663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441785,-0.00972116) , 
0, 1.7057, 1, 0, 0.564026,0.00248538) , 
2, 1.06468, 1, 0, 0.5,-0.0147831)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.375459,-0.0100194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513328,0.0016563) , 
3, 92.5072, 1, 0, 0.43393,-0.0348871) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801081,0.0229159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.676549,0.00499189) , 
0, 1.38701, 1, 0, 0.758016,0.0662915) , 
2, 4.0398, 1, 0, 0.5,-0.0142601)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889893,-0.0185498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184261,-0.00834584) , 
1, 139.794, 1, 0, 0.115589,-0.110597) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625659,0.00675349) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499486,-0.0053812) , 
0, 1.19709, 1, 0, 0.564026,0.00223634) , 
2, 1.06468, 1, 0, 0.5,-0.0138735)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627136,0.00538155) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320277,-0.0111706) , 
6, 1.99852, 1, 0, 0.579149,0.0120251) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248437,-0.0145197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443911,-0.00201625) , 
3, 90.6636, 1, 0, 0.318251,-0.0717105) , 
5, 1.77881, 1, 0, 0.5,-0.0133779)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656913,0.00894967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.287572,-0.0116181) , 
5, 2.22765, 1, 0, 0.617317,0.0321831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.398395,-0.00829143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688038,0.0174631) , 
3, 173.542, 1, 0, 0.422241,-0.0429382) , 
6, 1.1453, 1, 0, 0.5,-0.0129941)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0159594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,0.00148855) , 
1, 213.787, 1, 0, 0.115589,-0.0995654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59721,0.0028557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380078,-0.0102729) , 
4, 2.78803, 1, 0, 0.564026,0.00191549) , 
4, 0.0248033, 1, 0, 0.5,-0.0125736)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.672902,0.0082837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42407,-0.00638655) , 
6, 1.6556, 1, 0, 0.613092,0.0214107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335317,-0.00959952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578003,0.00520414) , 
3, 122.066, 1, 0, 0.379552,-0.0479601) , 
5, 1.37138, 1, 0, 0.5,-0.0121821)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413021,-0.00590678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662203,0.0154268) , 
3, 168.598, 1, 0, 0.43393,-0.0286064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.765771,0.0146334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.574704,-0.0135293) , 
5, 2.0314, 1, 0, 0.758016,0.0536662) , 
2, 4.0398, 1, 0, 0.5,-0.0118338)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889893,-0.0167237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184261,-0.00645388) , 
1, 139.794, 1, 0, 0.115589,-0.0906819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602726,0.0034888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441785,-0.0081505) , 
0, 1.7057, 1, 0, 0.564026,0.00167087) , 
2, 1.06468, 1, 0, 0.5,-0.0115149)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654842,0.00754548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279121,-0.0106442) , 
5, 2.2707, 1, 0, 0.617317,0.0271514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362443,-0.00918885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535864,0.00149548) , 
3, 102.513, 1, 0, 0.422241,-0.0364582) , 
6, 1.1453, 1, 0, 0.5,-0.0111028)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0144272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,0.0021309) , 
1, 213.787, 1, 0, 0.115589,-0.0843391) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61645,0.00449182) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465355,-0.00608539) , 
4, 2.42557, 1, 0, 0.564026,0.00155731) , 
2, 1.06468, 1, 0, 0.5,-0.0107067)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616742,0.00368199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267674,-0.0114876) , 
6, 2.21284, 1, 0, 0.579149,0.00897665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.248437,-0.0119661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443911,-0.00100458) , 
3, 90.6636, 1, 0, 0.318251,-0.0548478) , 
5, 1.77881, 1, 0, 0.5,-0.0103859)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522913,-0.00141465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251209,-0.0114296) , 
6, 2.0029, 1, 0, 0.462427,-0.0238036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674134,0.0114426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321316,-0.028452) , 
0, 2.33039, 1, 0, 0.66601,0.0506258) , 
3, 137.299, 1, 0, 0.5,-0.0100672)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545874,-0.000427352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604874,0.012452) , 
1, 134.617, 1, 0, 0.56355,0.0186737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491697,-0.00357425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21747,-0.0146255) , 
6, 2.20469, 1, 0, 0.437646,-0.0374814) , 
0, 1.18469, 1, 0, 0.5,-0.00967054)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411539,-0.0062172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50704,0.00505097) , 
1, 149.53, 1, 0, 0.43393,-0.0230432) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744546,0.00816572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822478,0.0275441) , 
2, 6.02985, 1, 0, 0.758016,0.0449672) , 
2, 4.0398, 1, 0, 0.5,-0.00917814)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.106491,-0.0130381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.297137,0.00561164) , 
3, 155.653, 1, 0, 0.115589,-0.0742569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618047,0.00553813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50393,-0.00448939) , 
4, 2.26699, 1, 0, 0.564026,0.00199951) , 
4, 0.0248033, 1, 0, 0.5,-0.0088881)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597388,0.00295095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397942,-0.00603439) , 
6, 1.1453, 1, 0, 0.475862,-0.0171604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742151,0.0184123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454026,-0.0154135) , 
0, 2.20682, 1, 0, 0.727657,0.071845) , 
3, 172.843, 1, 0, 0.5,-0.00862789)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688735,0.0119903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44358,-0.00109753) , 
5, 1.35624, 1, 0, 0.57821,0.0283518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510517,-0.00238961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21956,-0.0129572) , 
6, 2.25514, 1, 0, 0.460842,-0.0266813) , 
0, 0.911774, 1, 0, 0.5,-0.00832055)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599888,0.00359082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38518,-0.0074653) , 
6, 0.920362, 1, 0, 0.437457,-0.0307122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653412,0.0111695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536317,0.000167744) , 
0, 0.910375, 1, 0, 0.576828,0.0198445) , 
3, 91.5995, 1, 0, 0.5,-0.00802487)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889893,-0.0141824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184261,-0.00437596) , 
1, 139.794, 1, 0, 0.115589,-0.0672364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618047,0.00515798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50393,-0.0040438) , 
4, 2.26699, 1, 0, 0.564026,0.00224465) , 
4, 0.0248033, 1, 0, 0.5,-0.0076756)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611887,0.00297613) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266439,-0.00929323) , 
6, 2.21284, 1, 0, 0.573768,0.0072756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2302,-0.0110856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407692,-0.00181821) , 
3, 82.1431, 1, 0, 0.308146,-0.0458149) , 
5, 1.85071, 1, 0, 0.5,-0.00746861)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11921,-0.0102584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588424,0.00221079) , 
4, 0.0248033, 1, 0, 0.523278,0.00233523) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410874,-0.00757374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144216,-0.0189166) , 
6, 2.46891, 1, 0, 0.362883,-0.0638139) , 
0, 1.9414, 1, 0, 0.5,-0.00726496)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330262,-0.00642238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697739,0.00293399) , 
2, 3.00498, 1, 0, 0.483985,-0.0193749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779309,0.0331259) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528834,0.00388926) , 
5, 0.615927, 1, 0, 0.555436,0.0356423) , 
1, 149.573, 1, 0, 0.5,-0.00704355)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545874,-0.000291912) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604874,0.010375) , 
1, 134.617, 1, 0, 0.56355,0.0155472) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418188,-0.00579398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688744,0.0124499) , 
3, 178.947, 1, 0, 0.437646,-0.0289031) , 
0, 1.18469, 1, 0, 0.5,-0.00688903)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640263,0.00369971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741555,0.0225881) , 
1, 179.485, 1, 0, 0.660359,0.0354235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473805,-0.00162643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340638,-0.0102968) , 
4, 2.82758, 1, 0, 0.457303,-0.0176932) , 
5, 0.844109, 1, 0, 0.5,-0.00652428)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411539,-0.00478696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50704,0.00412531) , 
1, 149.53, 1, 0, 0.43393,-0.016925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.750706,0.00746136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.868406,0.0384088) , 
2, 7.01493, 1, 0, 0.758016,0.0354197) , 
2, 4.0398, 1, 0, 0.5,-0.00625367)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.138014,-0.00772414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.641248,0.00637528) , 
4, 0.473607, 1, 0, 0.57821,0.0232401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502543,-0.0019482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198252,-0.0122751) , 
6, 2.40648, 1, 0, 0.460842,-0.0207698) , 
0, 0.911774, 1, 0, 0.5,-0.00608673)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500841,-0.00217634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177539,-0.0115744) , 
5, 2.28211, 1, 0, 0.437457,-0.0244527) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582428,0.00372171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344009,-0.0172277) , 
0, 2.32086, 1, 0, 0.576828,0.0168942) , 
3, 91.5995, 1, 0, 0.5,-0.00589828)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11921,-0.00927681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588424,0.0020385) , 
4, 0.0248033, 1, 0, 0.523278,0.0025112) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410874,-0.00631786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144216,-0.0172435) , 
6, 2.46891, 1, 0, 0.362883,-0.0537938) , 
0, 1.9414, 1, 0, 0.5,-0.00566031)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597388,0.00243387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397942,-0.00450289) , 
6, 1.1453, 1, 0, 0.475862,-0.0118795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.742151,0.0145696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454026,-0.0133633) , 
0, 2.20682, 1, 0, 0.727657,0.0545072) , 
3, 172.843, 1, 0, 0.5,-0.00551529)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688735,0.0089397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44358,-0.000798426) , 
5, 1.35624, 1, 0, 0.57821,0.0206973) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469965,-0.000337124) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44525,-0.00701088) , 
4, 2.33151, 1, 0, 0.460842,-0.0183866) , 
0, 0.911774, 1, 0, 0.5,-0.00534699)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0104233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,0.0039145) , 
1, 213.787, 1, 0, 0.115589,-0.0505097) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614497,0.00541981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524088,-0.00297674) , 
4, 2.17637, 1, 0, 0.564026,0.00244373) , 
2, 1.06468, 1, 0, 0.5,-0.00511676)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455597,-0.00232845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303074,-0.0110043) , 
4, 2.87718, 1, 0, 0.437457,-0.0212806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581988,0.00328745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336696,-0.0161228) , 
0, 2.33323, 1, 0, 0.576828,0.0149909) , 
3, 91.5995, 1, 0, 0.5,-0.00500373)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640263,0.00312739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741555,0.0195411) , 
1, 179.485, 1, 0, 0.660359,0.029866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473805,-0.00120652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340638,-0.00879065) , 
4, 2.82758, 1, 0, 0.457303,-0.0139778) , 
5, 0.844109, 1, 0, 0.5,-0.00475865)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103376,-0.0100088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270084,0.00355418) , 
1, 213.787, 1, 0, 0.115589,-0.0477713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618047,0.00425598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50393,-0.0030696) , 
4, 2.26699, 1, 0, 0.564026,0.00261318) , 
2, 1.06468, 1, 0, 0.5,-0.00458053)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49391,-0.000583001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.812239,0.0179509) , 
2, 5.00995, 1, 0, 0.523278,0.00264173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410874,-0.00536066) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.144216,-0.0161802) , 
6, 2.46891, 1, 0, 0.362883,-0.0466124) , 
0, 1.9414, 1, 0, 0.5,-0.0045065)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564322,0.00496537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459014,-0.00445212) , 
1, 44.6535, 1, 0, 0.483985,-0.0136069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594028,0.00679044) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203182,-0.00936635) , 
6, 2.6541, 1, 0, 0.555436,0.0274364) , 
1, 149.573, 1, 0, 0.5,-0.00440757)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600071,0.00228734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310616,-0.00599362) , 
6, 2.00026, 1, 0, 0.547636,0.00308984) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.239274,-0.00347006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.259793,-0.0157098) , 
4, 2.08348, 1, 0, 0.244085,-0.0434226) , 
5, 2.28211, 1, 0, 0.5,-0.00420931)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547653,8.74001e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60991,0.00856643) , 
1, 134.617, 1, 0, 0.56627,0.0136961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496269,-0.00157663) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215699,-0.010007) , 
5, 2.28211, 1, 0, 0.445183,-0.0188783) , 
0, 1.11026, 1, 0, 0.5,-0.00413154)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646118,0.0052465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45266,-0.00552431) , 
4, 2.70393, 1, 0, 0.617317,0.0158227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411564,-0.00338704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.758824,0.0206655) , 
3, 224.277, 1, 0, 0.422241,-0.017064) , 
6, 1.1453, 1, 0, 0.5,-0.00395505)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102904,-0.00931904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264245,0.00357142) , 
3, 138.638, 1, 0, 0.115589,-0.0425876) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.614497,0.0046346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524088,-0.00239744) , 
4, 2.17637, 1, 0, 0.564026,0.00257463) , 
4, 0.0248033, 1, 0, 0.5,-0.00387347)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677344,0.00482527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743375,0.0204647) , 
1, 107.027, 1, 0, 0.711131,0.056157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422958,-0.00252466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752555,0.00633085) , 
2, 4.0398, 1, 0, 0.486233,-0.00771953) , 
5, 0.580476, 1, 0, 0.5,-0.00380946)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.11921,-0.00743053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588424,0.00167778) , 
4, 0.0248033, 1, 0, 0.523278,0.0025239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371665,-0.00533163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262398,-0.0185913) , 
0, 2.39132, 1, 0, 0.362883,-0.0407942) , 
0, 1.9414, 1, 0, 0.5,-0.00376284)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56157,0.00454668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45543,-0.00467887) , 
1, 46.2195, 1, 0, 0.484045,-0.0132893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576705,0.00502788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194098,-0.00806089) , 
6, 2.661, 1, 0, 0.539661,0.0202249) , 
1, 134.617, 1, 0, 0.5,-0.00367484)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451265,-0.00217301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78118,0.0125109) , 
2, 5.00995, 1, 0, 0.477528,-0.00811162) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63138,0.0222678) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750359,0.00786194) , 
4, 1.44829, 1, 0, 0.732961,0.0441921) , 
3, 177.921, 1, 0, 0.5,-0.00351011)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703677,0.00963166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516154,0.000887764) , 
6, 0.969468, 1, 0, 0.57821,0.0172173) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514955,-0.000887982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.232423,-0.0082874) , 
5, 2.21021, 1, 0, 0.460842,-0.013784) , 
0, 0.911774, 1, 0, 0.5,-0.00344098)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425571,-0.00358772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855393,0.0351815) , 
2, 6.01493, 1, 0, 0.436875,-0.0172286) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570987,0.00249699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32899,-0.0133826) , 
0, 2.33617, 1, 0, 0.565618,0.0110627) , 
3, 86.5218, 1, 0, 0.5,-0.00335686)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561441,0.00419313) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462393,-0.00323732) , 
1, 46.3923, 1, 0, 0.485225,-0.00930936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.797396,0.0269638) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547343,0.00319144) , 
5, 0.615927, 1, 0, 0.576883,0.0283389) , 
1, 169.514, 1, 0, 0.5,-0.00324046)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568044,0.0012059) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223758,-0.00746195) , 
6, 2.42357, 1, 0, 0.535996,0.0017055) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210581,-0.00350201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223975,-0.016708) , 
4, 2.0502, 1, 0, 0.213345,-0.0414457) , 
5, 2.49781, 1, 0, 0.5,-0.00310863)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118541,-0.00670128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578012,0.00120775) , 
2, 1.06468, 1, 0, 0.513365,0.000940604) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360148,-0.00614883) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265775,-0.0177493) , 
0, 2.39823, 1, 0, 0.348495,-0.048219) , 
0, 2.11507, 1, 0, 0.5,-0.00304458)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56157,0.00393019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45543,-0.00403923) , 
1, 46.2195, 1, 0, 0.484045,-0.0113693) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548236,0.00391631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.289594,-0.0133744) , 
0, 2.2841, 1, 0, 0.539661,0.0178774) , 
1, 134.617, 1, 0, 0.5,-0.00297905)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688735,0.00669936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44358,-0.000434338) , 
5, 1.35624, 1, 0, 0.57821,0.0155591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450697,-0.00259777) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77931,0.0208785) , 
3, 227.257, 1, 0, 0.460842,-0.0120303) , 
0, 0.911774, 1, 0, 0.5,-0.00282562)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115589,-0.00666315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.595235,0.00162834) , 
4, 0.0140671, 1, 0, 0.517515,0.00194965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327273,-0.00767645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.549178,0.00572472) , 
3, 117.871, 1, 0, 0.370168,-0.0376559) , 
4, 2.82758, 1, 0, 0.5,-0.00275819)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.789386,0.0199762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.631061,0.00365087) , 
0, 1.16014, 1, 0, 0.711131,0.0460792) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503649,-0.000200189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359975,-0.00584104) , 
4, 2.82758, 1, 0, 0.486233,-0.00595996) , 
5, 0.580476, 1, 0, 0.5,-0.00277449)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562825,0.00372258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456916,-0.00451043) , 
1, 45.8416, 1, 0, 0.488781,-0.012064) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598804,0.00503277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28877,-0.00415343) , 
6, 1.98054, 1, 0, 0.519363,0.0135016) , 
1, 119.661, 1, 0, 0.5,-0.00268513)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647976,0.00426795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453845,-0.00454477) , 
4, 2.70393, 1, 0, 0.619239,0.0126317) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418414,-0.000386712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437565,-0.00456051) , 
4, 2.30671, 1, 0, 0.425313,-0.0121276) , 
6, 1.12008, 1, 0, 0.5,-0.00259204)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153661,-0.00664428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584599,0.00120534) , 
4, 0.942525, 1, 0, 0.535996,0.00174293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185898,-0.00149696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270164,-0.0132287) , 
4, 1.41561, 1, 0, 0.213345,-0.0365197) , 
5, 2.49781, 1, 0, 0.5,-0.00252581)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425571,-0.00301226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.855393,0.0317041) , 
2, 6.01493, 1, 0, 0.436875,-0.0141778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571637,0.00209408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124767,-0.0161814) , 
6, 3.26408, 1, 0, 0.565618,0.00962745) , 
3, 86.5218, 1, 0, 0.5,-0.00250564)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488528,-0.000533161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.744606,0.00949566) , 
3, 172.843, 1, 0, 0.513365,0.00103996) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360148,-0.00532845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265775,-0.0161894) , 
0, 2.39823, 1, 0, 0.348495,-0.0418579) , 
0, 2.11507, 1, 0, 0.5,-0.00243761)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562933,0.00348251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45761,-0.00482887) , 
1, 45.8457, 1, 0, 0.492511,-0.0122085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588474,0.00427199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282304,-0.00391389) , 
6, 1.98054, 1, 0, 0.510132,0.0109915) , 
1, 109.69, 1, 0, 0.5,-0.0023486)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862935,0.0391682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557321,0.00131703) , 
5, 0.484563, 1, 0, 0.56355,0.0091492) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488977,-0.00109002) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20936,-0.00776165) , 
6, 2.25514, 1, 0, 0.437646,-0.013478) , 
0, 1.18469, 1, 0, 0.5,-0.00227184)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153661,-0.00616848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584599,0.00111703) , 
4, 0.942525, 1, 0, 0.535996,0.00165211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210581,-0.00249705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223975,-0.0148204) , 
4, 2.0502, 1, 0, 0.213345,-0.0331391) , 
5, 2.49781, 1, 0, 0.5,-0.00222935)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216457,-0.00332766) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699567,0.00513077) , 
2, 2.03483, 1, 0, 0.505955,0.00595489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511729,-0.00160437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234218,-0.0130538) , 
5, 2.26142, 1, 0, 0.489417,-0.0167601) , 
4, 2.33151, 1, 0, 0.5,-0.00222378)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501332,-0.000687855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314093,-0.00738317) , 
4, 2.90199, 1, 0, 0.483985,-0.00816239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.779309,0.0190403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.528834,0.00199897) , 
5, 0.615927, 1, 0, 0.555436,0.0177511) , 
1, 149.573, 1, 0, 0.5,-0.00235421)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791525,0.0241939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57022,0.00193407) , 
6, 0.495169, 1, 0, 0.57821,0.0126688) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469965,0.000289665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44525,-0.00448158) , 
4, 2.33151, 1, 0, 0.460842,-0.00973374) , 
0, 0.911774, 1, 0, 0.5,-0.00225957)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49684,-0.00191876) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519644,0.00217616) , 
1, 109.69, 1, 0, 0.506472,-0.000853875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.0106307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0191042) , 
0, 1.61443, 1, 0, 0.0882433,-0.085574) , 
6, 3.26408, 1, 0, 0.5,-0.00216483)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118541,-0.00537287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578012,0.000996905) , 
4, 0.0248033, 1, 0, 0.513365,0.00101712) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477187,0.00739029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337161,-0.00700058) , 
1, 21.7769, 1, 0, 0.348495,-0.036467) , 
0, 2.11507, 1, 0, 0.5,-0.00202158)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601104,0.00318145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380398,-0.00372132) , 
6, 0.942445, 1, 0, 0.436875,-0.0118201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570987,0.00188742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.32899,-0.0103146) , 
0, 2.33617, 1, 0, 0.565618,0.00821379) , 
3, 86.5218, 1, 0, 0.5,-0.00199711)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490819,0.00189345) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523448,-0.00198541) , 
4, 2.18269, 1, 0, 0.506472,-0.000712265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101841,-0.011763) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0724201,-0.0195162) , 
0, 1.89254, 1, 0, 0.0882433,-0.0799045) , 
6, 3.26408, 1, 0, 0.5,-0.00193768)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889893,-0.00821983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184261,0.000555168) , 
1, 139.794, 1, 0, 0.115589,-0.0256846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603269,0.00425597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542517,-0.00153396) , 
4, 2.08576, 1, 0, 0.564026,0.0021493) , 
4, 0.0248033, 1, 0, 0.5,-0.00182473)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734592,0.00829632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461185,-0.00385765) , 
6, 1.67219, 1, 0, 0.682227,0.0233446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48091,-0.000613329) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261072,-0.00904163) , 
4, 3.29884, 1, 0, 0.473649,-0.00545646) , 
5, 0.700309, 1, 0, 0.5,-0.00181786)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562933,0.00339604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45761,-0.00422727) , 
1, 45.8457, 1, 0, 0.492511,-0.00998219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588474,0.00361765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282304,-0.00330585) , 
6, 1.98054, 1, 0, 0.510132,0.00929934) , 
1, 109.69, 1, 0, 0.5,-0.00178759)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451265,-0.00136928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78118,0.00921363) , 
2, 5.00995, 1, 0, 0.477528,-0.00463659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58471,0.0212242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.750657,0.00456275) , 
4, 1.21469, 1, 0, 0.732961,0.0283216) , 
3, 177.921, 1, 0, 0.5,-0.00173704)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791525,0.0216641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.57022,0.00177229) , 
6, 0.495169, 1, 0, 0.57821,0.0114457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450697,-0.00188347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77931,0.0172642) , 
3, 227.257, 1, 0, 0.460842,-0.00832265) , 
0, 0.911774, 1, 0, 0.5,-0.00172732)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153661,-0.00545381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584599,0.00100324) , 
4, 0.942525, 1, 0, 0.535996,0.0015938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185898,-0.000510957) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270164,-0.0113311) , 
4, 1.41561, 1, 0, 0.213345,-0.0277696) , 
5, 2.49781, 1, 0, 0.5,-0.00168211)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.1204,-0.00475305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588606,0.00112198) , 
4, 0.471263, 1, 0, 0.523278,0.00203482) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379857,-0.00297656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0952106,-0.0193956) , 
5, 3.04953, 1, 0, 0.362883,-0.0236007) , 
0, 1.9414, 1, 0, 0.5,-0.00168565)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566414,0.00332995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464136,-0.00204391) , 
1, 42.1759, 1, 0, 0.485225,-0.00559963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764335,0.0310031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569821,0.00272289) , 
0, 0.267039, 1, 0, 0.576883,0.0187082) , 
1, 169.514, 1, 0, 0.5,-0.0016812)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490819,0.00175001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523448,-0.00177003) , 
4, 2.18269, 1, 0, 0.506472,-0.000494035) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00910603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.017664) , 
0, 1.61443, 1, 0, 0.0882433,-0.0726276) , 
6, 3.26408, 1, 0, 0.5,-0.00161023)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562933,0.00289589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45761,-0.00376288) , 
1, 45.8457, 1, 0, 0.492511,-0.0090498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588474,0.00331875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282304,-0.0029405) , 
6, 1.98054, 1, 0, 0.510132,0.00867015) , 
1, 109.69, 1, 0, 0.5,-0.00151887)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519866,0.00033839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281381,-0.00682996) , 
4, 3.27404, 1, 0, 0.511869,0.000103171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142192,-0.00439116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1276,-0.0232283) , 
4, 1.46806, 1, 0, 0.139574,-0.0494612) , 
5, 3.04904, 1, 0, 0.5,-0.00147693)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.426213,-0.00278634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.864936,0.0320489) , 
2, 6.01493, 1, 0, 0.438325,-0.0125355) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627979,0.00498953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507745,-0.00012152) , 
0, 0.737636, 1, 0, 0.536332,0.00511333) , 
3, 71.2887, 1, 0, 0.5,-0.00142929)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.656647,-0.00919474) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718116,0.00988354) , 
1, 28.9326, 1, 0, 0.711131,0.031708) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493448,-0.000354272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268361,-0.0074216) , 
4, 3.29884, 1, 0, 0.486233,-0.00356601) , 
5, 0.580476, 1, 0, 0.5,-0.00140678)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490819,0.00163548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523448,-0.00160503) , 
4, 2.18269, 1, 0, 0.506472,-0.000318652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00855264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0170477) , 
0, 1.61443, 1, 0, 0.0882433,-0.067942) , 
6, 3.26408, 1, 0, 0.5,-0.00136506)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117442,-0.00461039) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568967,0.000633782) , 
4, 0.471263, 1, 0, 0.504307,-0.000104131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330458,-0.000958397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245926,-0.0164964) , 
4, 2.27699, 1, 0, 0.290231,-0.0590407) , 
0, 2.35076, 1, 0, 0.5,-0.00128976)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499617,0.0016938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524828,-0.00144061) , 
4, 2.18269, 1, 0, 0.511869,0.000177392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142192,-0.00400125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1276,-0.0223772) , 
4, 1.46806, 1, 0, 0.139574,-0.045954) , 
5, 3.04904, 1, 0, 0.5,-0.00129326)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562933,0.00275455) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45761,-0.00345651) , 
1, 45.8457, 1, 0, 0.492511,-0.00812422) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588474,0.00307681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282304,-0.0026876) , 
6, 1.98054, 1, 0, 0.510132,0.00809236) , 
1, 109.69, 1, 0, 0.5,-0.00123222)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118541,-0.00423962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578012,0.000838736) , 
4, 0.0248033, 1, 0, 0.513365,0.00113642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493587,0.0124191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341891,-0.00533424) , 
1, 12.4618, 1, 0, 0.348495,-0.0277483) , 
0, 2.11507, 1, 0, 0.5,-0.00120516)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433974,-0.00222169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531559,0.000725307) , 
3, 71.2887, 1, 0, 0.495276,-0.00209732) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.867762,0.0151942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.869589,0.0398178) , 
0, 1.26724, 1, 0, 0.868406,0.0679703) , 
2, 7.01493, 1, 0, 0.5,-0.00121023)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491123,-0.000690188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586792,0.00347044) , 
1, 169.514, 1, 0, 0.506472,-0.0002041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00786953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0163423) , 
0, 1.61443, 1, 0, 0.0882433,-0.0625771) , 
6, 3.26408, 1, 0, 0.5,-0.00116926)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153661,-0.00478848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584599,0.000908629) , 
4, 0.942525, 1, 0, 0.535996,0.00158127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185898,0.000166571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270164,-0.0102275) , 
4, 1.41561, 1, 0, 0.213345,-0.0225604) , 
5, 2.49781, 1, 0, 0.5,-0.00111208)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758641,0.0231392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702576,0.00408937) , 
3, 52.6039, 1, 0, 0.711131,0.0280796) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500442,-9.87763e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327821,-0.00447742) , 
4, 2.9764, 1, 0, 0.486233,-0.00304177) , 
5, 0.580476, 1, 0, 0.5,-0.00113674)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481499,-0.000455008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.740512,0.00634526) , 
3, 177.921, 1, 0, 0.504307,-5.81476e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330458,-0.000446652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245926,-0.0153336) , 
4, 2.27699, 1, 0, 0.290231,-0.0528365) , 
0, 2.35076, 1, 0, 0.5,-0.00111989)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499617,0.00164168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524828,-0.0013679) , 
4, 2.18269, 1, 0, 0.511869,0.000243421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126042,-0.0022024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177737,-0.0180044) , 
4, 0.90674, 1, 0, 0.139574,-0.0416261) , 
5, 3.04904, 1, 0, 0.5,-0.00109136)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601556,0.00112761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332557,0.00896221) , 
6, 2.3221, 1, 0, 0.57821,0.00924939) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496076,-0.000391597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178595,-0.00712834) , 
6, 2.5326, 1, 0, 0.460842,-0.00619163) , 
0, 0.911774, 1, 0, 0.5,-0.00104003)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0889893,-0.00687014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184261,0.00154387) , 
1, 139.794, 1, 0, 0.115589,-0.0186449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573714,0.00416341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560735,-0.000925228) , 
4, 1.94984, 1, 0, 0.564026,0.00192744) , 
4, 0.0248033, 1, 0, 0.5,-0.0010098)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658049,0.00262737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28992,-0.00484813) , 
5, 2.22765, 1, 0, 0.619239,0.00796941) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418237,-0.00141655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779102,0.0169737) , 
3, 254.719, 1, 0, 0.425313,-0.00663703) , 
6, 1.12008, 1, 0, 0.5,-0.00101165)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562933,0.00258793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45761,-0.00312099) , 
1, 45.8457, 1, 0, 0.492511,-0.00711952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588474,0.00272299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.282304,-0.00235721) , 
6, 1.98054, 1, 0, 0.510132,0.00718334) , 
1, 109.69, 1, 0, 0.5,-0.00104085)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4736,-0.000473437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.79282,0.00701164) , 
2, 5.00995, 1, 0, 0.502107,-0.00033658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325864,-0.0171415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24183,-0.00664673) , 
6, 1.44546, 1, 0, 0.277998,-0.0730348) , 
0, 2.40038, 1, 0, 0.5,-0.00101996)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49684,-0.00118186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519644,0.0015011) , 
1, 109.69, 1, 0, 0.506472,-0.000143658) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00711395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0154764) , 
0, 1.61443, 1, 0, 0.0882433,-0.0564985) , 
6, 3.26408, 1, 0, 0.5,-0.00101569)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664742,-0.0100254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77048,0.0209361) , 
1, 58.0256, 1, 0, 0.742331,0.0468925) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502083,-0.000122962) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27314,-0.00599003) , 
4, 3.29884, 1, 0, 0.494931,-0.00195125) , 
5, 0.484609, 1, 0, 0.5,-0.000950557)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.820437,0.0212374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.536082,0.000382327) , 
5, 0.484117, 1, 0, 0.541775,0.00328192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346382,-0.0036951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527734,0.00298182) , 
3, 113.017, 1, 0, 0.393612,-0.0116389) , 
0, 1.63127, 1, 0, 0.5,-0.000925061)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499617,0.00149116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524828,-0.00122023) , 
4, 2.18269, 1, 0, 0.511869,0.000277404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.142192,-0.00293889) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.1276,-0.0203522) , 
4, 1.46806, 1, 0, 0.139574,-0.0373661) , 
5, 3.04904, 1, 0, 0.5,-0.000922658)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103251,-0.00500462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271594,0.00630507) , 
3, 138.638, 1, 0, 0.116678,-0.0170854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564211,0.00402009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564201,-0.000777833) , 
4, 1.91326, 1, 0, 0.564203,0.00183117) , 
4, 0.471263, 1, 0, 0.5,-0.000882641)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491123,-0.000554967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586792,0.00291206) , 
1, 169.514, 1, 0, 0.506472,-5.89843e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101841,-0.00838094) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0724201,-0.0160946) , 
0, 1.89254, 1, 0, 0.0882433,-0.0534007) , 
6, 3.26408, 1, 0, 0.5,-0.000884394)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573295,0.00149989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456364,-0.00109694) , 
0, 0.911774, 1, 0, 0.495276,-0.0015875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.908496,0.0364027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769151,-0.00217448) , 
6, 1.13652, 1, 0, 0.868406,0.0572026) , 
2, 7.01493, 1, 0, 0.5,-0.000843189)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494582,-0.000229387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797232,0.0119198) , 
3, 254.086, 1, 0, 0.502107,-0.00021056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325864,-0.0158948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24183,-0.00594388) , 
6, 1.44546, 1, 0, 0.277998,-0.0665052) , 
0, 2.40038, 1, 0, 0.5,-0.000833744)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664084,0.00525143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337699,-0.00235701) , 
5, 1.99451, 1, 0, 0.563481,0.0123918) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45826,-0.0023849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515926,0.0011694) , 
1, 116.316, 1, 0, 0.485546,-0.00380672) , 
1, 44.8802, 1, 0, 0.5,-0.00080247)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514242,0.000219431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280846,-0.00492694) , 
4, 3.27404, 1, 0, 0.506472,-1.69084e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0718953,-0.0100802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114214,-0.0130372) , 
3, 93.3111, 1, 0, 0.0882433,-0.0504346) , 
6, 3.26408, 1, 0, 0.5,-0.000797072)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.089469,-0.00603164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19681,0.00194838) , 
3, 100.355, 1, 0, 0.116678,-0.0158496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564211,0.00376316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564201,-0.00071935) , 
4, 1.91326, 1, 0, 0.564203,0.00175004) , 
4, 0.471263, 1, 0, 0.5,-0.000774839)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728643,0.012035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399491,-0.0148007) , 
5, 0.948538, 1, 0, 0.486459,-0.0523049) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620081,0.00166504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425383,-0.000921857) , 
6, 1.12008, 1, 0, 0.500188,-6.45123e-05) , 
3, 15.4339, 1, 0, 0.5,-0.000780002)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.117811,-0.00337578) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571724,0.000552654) , 
4, 0.471263, 1, 0, 0.507072,0.000423978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494173,0.0055767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277033,-0.00762902) , 
5, 0.950635, 1, 0, 0.318652,-0.0313696) , 
0, 2.27633, 1, 0, 0.5,-0.000769301)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586473,0.00282803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495331,-0.000501952) , 
1, 44.8802, 1, 0, 0.511869,0.000277465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126042,-0.000816744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177737,-0.0164976) , 
4, 0.90674, 1, 0, 0.139574,-0.0331053) , 
5, 3.04904, 1, 0, 0.5,-0.000786766)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391306,-0.0258715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43885,-0.00124372) , 
0, 0.138588, 1, 0, 0.438325,-0.00833054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627979,0.00379035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507745,-0.000129973) , 
0, 0.737636, 1, 0, 0.536332,0.00368106) , 
3, 71.2887, 1, 0, 0.5,-0.000771767)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49684,-0.00100738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519644,0.00132262) , 
1, 109.69, 1, 0, 0.506472,-1.90206e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00561692) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0140239) , 
0, 1.61443, 1, 0, 0.0882433,-0.0467476) , 
6, 3.26408, 1, 0, 0.5,-0.000742098)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.682681,0.00612557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49785,-0.000206992) , 
6, 0.539933, 1, 0, 0.507466,0.000371392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.276721,1.86806e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290426,-0.016098) , 
2, 2.01493, 1, 0, 0.280204,-0.0320807) , 
4, 3.27404, 1, 0, 0.5,-0.000694718)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497342,-0.000151083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874327,0.0217405) , 
2, 7.01493, 1, 0, 0.502107,-0.00012194) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208642,-0.00542647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387483,-0.0151804) , 
2, 3.0199, 1, 0, 0.277998,-0.0592499) , 
0, 2.40038, 1, 0, 0.5,-0.000677756)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629875,0.007784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421691,-0.0149085) , 
1, 48.4069, 1, 0, 0.486459,-0.0484124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503619,0.000122643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.220567,-0.00769306) , 
4, 3.64609, 1, 0, 0.500188,3.56705e-06) , 
3, 15.4339, 1, 0, 0.5,-0.000659543)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153661,-0.00418417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.584599,0.000775107) , 
4, 0.942525, 1, 0, 0.535996,0.00133268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.185898,0.00105512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270164,-0.00888191) , 
4, 1.41561, 1, 0, 0.213345,-0.0162546) , 
5, 2.49781, 1, 0, 0.5,-0.000629428)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210486,-0.00234914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712013,0.00468076) , 
2, 2.03483, 1, 0, 0.480008,0.00469253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542552,-0.000471919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.253212,-0.00854199) , 
5, 2.26783, 1, 0, 0.522218,-0.00662314) , 
4, 2.18269, 1, 0, 0.5,-0.000666949)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566601,0.00238893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460237,-0.00240024) , 
1, 42.5719, 1, 0, 0.492511,-0.00547442) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.689478,0.00620825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466824,2.85272e-05) , 
5, 0.768967, 1, 0, 0.510132,0.00550633) , 
1, 109.69, 1, 0, 0.5,-0.000807629)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532128,0.000668984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397856,-0.00222625) , 
4, 2.75317, 1, 0, 0.513365,0.000812652) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493587,0.0124768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341891,-0.00390502) , 
1, 12.4618, 1, 0, 0.348495,-0.0189479) , 
0, 2.11507, 1, 0, 0.5,-0.000789263)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458267,0.00128897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543961,-0.00090204) , 
4, 2.08348, 1, 0, 0.506472,-9.57435e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0779311,-0.0147409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0954089,-0.00720765) , 
6, 3.42068, 1, 0, 0.0882433,-0.0435116) , 
6, 3.26408, 1, 0, 0.5,-0.00076756)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486194,-0.00848605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507042,0.000122517) , 
3, 15.4339, 1, 0, 0.506752,-1.2252e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132391,-0.00424782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838952,-0.0163801) , 
0, 1.90913, 1, 0, 0.115847,-0.040778) , 
5, 3.19284, 1, 0, 0.5,-0.000716438)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664742,-0.0110546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77048,0.0176955) , 
1, 58.0256, 1, 0, 0.742331,0.0355041) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498388,-0.000152805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214892,-0.00765567) , 
4, 3.64609, 1, 0, 0.494931,-0.00143699) , 
5, 0.484609, 1, 0, 0.5,-0.000680154)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.862935,0.0279589) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557321,0.000610398) , 
5, 0.484563, 1, 0, 0.56355,0.00454371) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521305,0.00539388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429551,-0.0015953) , 
1, 22.6757, 1, 0, 0.437646,-0.00576679) , 
0, 1.18469, 1, 0, 0.5,-0.000660501)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501332,-0.000189385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314093,-0.0040862) , 
4, 2.90199, 1, 0, 0.483985,-0.00344363) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451859,0.00322358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.745215,-0.00270697) , 
2, 3.02488, 1, 0, 0.555436,0.0089485) , 
1, 149.573, 1, 0, 0.5,-0.000666092)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.118114,-0.00322369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568317,0.000445694) , 
4, 0.471263, 1, 0, 0.511869,0.000318687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126042,-0.000455531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177737,-0.0152425) , 
4, 0.90674, 1, 0, 0.139574,-0.0288277) , 
5, 3.04904, 1, 0, 0.5,-0.000610489)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648014,0.0040733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69437,-0.0261778) , 
3, 215.035, 1, 0, 0.651125,0.0116282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462682,-0.00082156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789126,0.013039) , 
3, 224.192, 1, 0, 0.474058,-0.00273599) , 
6, 0.716498, 1, 0, 0.5,-0.000631526)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486949,-0.000481027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581171,0.00239517) , 
1, 169.514, 1, 0, 0.502107,-0.000144978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325864,-0.0135527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24183,-0.00416602) , 
6, 1.44546, 1, 0, 0.277998,-0.0527075) , 
0, 2.40038, 1, 0, 0.5,-0.000639077)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458267,0.00123198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.543961,-0.000823155) , 
4, 2.08348, 1, 0, 0.506472,3.09186e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00455171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0130658) , 
0, 1.61443, 1, 0, 0.0882433,-0.0407187) , 
6, 3.26408, 1, 0, 0.5,-0.00059964)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486962,-0.00102837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.506475,0.000857315) , 
1, 109.69, 1, 0, 0.495276,-0.00112069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.94446,0.0515705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.829804,0.00587226) , 
6, 0.706425, 1, 0, 0.868406,0.0430973) , 
2, 7.01493, 1, 0, 0.5,-0.000560872)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.10691,-0.00372667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309073,0.00854182) , 
3, 155.653, 1, 0, 0.116678,-0.0125562) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567853,0.000434205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178733,-0.0141349) , 
6, 3.0928, 1, 0, 0.564203,0.00147359) , 
4, 0.471263, 1, 0, 0.5,-0.000539153)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728643,0.0123635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399491,-0.0126417) , 
5, 0.948538, 1, 0, 0.486459,-0.0416814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507042,0.000128294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114756,-0.0081694) , 
5, 3.19284, 1, 0, 0.500188,4.47902e-06) , 
3, 15.4339, 1, 0, 0.5,-0.000566455)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664084,0.00423003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337699,-0.00206227) , 
5, 1.99451, 1, 0, 0.563481,0.00962591) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464542,-0.00253415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.496584,0.000498614) , 
1, 92.5056, 1, 0, 0.485546,-0.00286438) , 
1, 44.8802, 1, 0, 0.5,-0.000547869)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502006,-5.24461e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.815229,0.0129249) , 
3, 284.553, 1, 0, 0.507072,0.000382934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494173,0.0056549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277033,-0.00633896) , 
5, 0.950635, 1, 0, 0.318652,-0.0243418) , 
0, 2.27633, 1, 0, 0.5,-0.000545036)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2065,-0.00200234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715032,0.00522679) , 
2, 2.04478, 1, 0, 0.446619,0.00470919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563137,-0.000228357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263261,-0.00776696) , 
5, 2.26783, 1, 0, 0.542756,-0.00473465) , 
4, 2.08348, 1, 0, 0.5,-0.000534587)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601556,0.000405938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332557,0.00883431) , 
6, 2.3221, 1, 0, 0.57821,0.00586405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.450697,-0.000986643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77931,0.012063) , 
3, 227.257, 1, 0, 0.460842,-0.00391951) , 
0, 0.911774, 1, 0, 0.5,-0.000655414)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487368,-0.00734699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503393,7.94328e-05) , 
3, 15.4339, 1, 0, 0.503173,-0.000140945) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217731,-0.0125373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218152,-0.000861932) , 
6, 1.58266, 1, 0, 0.217964,-0.0435642) , 
4, 3.67089, 1, 0, 0.5,-0.000624039)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49684,-0.000778266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519644,0.00101843) , 
1, 109.69, 1, 0, 0.506472,-1.80363e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114596,-0.00399187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0735183,-0.0116526) , 
1, 99.4411, 1, 0, 0.0882433,-0.0368056) , 
6, 3.26408, 1, 0, 0.5,-0.000587287)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.655249,-2.48202e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.732152,0.020904) , 
6, 0.512227, 1, 0, 0.672303,0.0188295) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597809,-0.00942705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48779,-7.95247e-05) , 
6, 0.587728, 1, 0, 0.490649,-0.00160201) , 
6, 0.539933, 1, 0, 0.5,-0.000550263)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4736,-0.000306917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.79282,0.00505219) , 
2, 5.00995, 1, 0, 0.502107,-8.36248e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.208642,-0.00375844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387483,-0.013007) , 
2, 3.0199, 1, 0, 0.277998,-0.0469249) , 
0, 2.40038, 1, 0, 0.5,-0.000523943)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560697,0.0048535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56685,-0.00120893) , 
4, 2.18269, 1, 0, 0.563481,0.00883274) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422464,-0.00105784) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.75781,0.00330021) , 
2, 4.0398, 1, 0, 0.485546,-0.00266534) , 
1, 44.8802, 1, 0, 0.5,-0.000532851)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503751,0.00013775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630046,-0.00598795) , 
1, 299.134, 1, 0, 0.506752,1.08071e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132391,-0.00321544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838952,-0.0150165) , 
0, 1.90913, 1, 0, 0.115847,-0.0337485) , 
5, 3.19284, 1, 0, 0.5,-0.00057235)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391306,-0.0241675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43885,-0.000876814) , 
0, 0.138588, 1, 0, 0.438325,-0.00620029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.654312,0.00806533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531479,0.000274552) , 
0, 0.278941, 1, 0, 0.536332,0.00279287) , 
3, 71.2887, 1, 0, 0.5,-0.000540992)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648014,0.00365946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69437,-0.0251487) , 
3, 215.035, 1, 0, 0.651125,0.00992056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471096,-0.000558229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858413,0.0304314) , 
3, 325.673, 1, 0, 0.474058,-0.00230881) , 
6, 0.716498, 1, 0, 0.5,-0.000517111)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491123,-0.000382503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586792,0.00207346) , 
1, 169.514, 1, 0, 0.506472,2.02349e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114596,-0.00372162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0735183,-0.0112161) , 
1, 99.4411, 1, 0, 0.0882433,-0.0346305) , 
6, 3.26408, 1, 0, 0.5,-0.000515951)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.089469,-0.00488769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19681,0.00254868) , 
3, 100.355, 1, 0, 0.116678,-0.010886) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564211,0.00303202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564201,-0.000615003) , 
4, 1.91326, 1, 0, 0.564203,0.00124666) , 
4, 0.471263, 1, 0, 0.5,-0.000493927)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494969,-0.000749343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.51435,0.000965325) , 
1, 109.69, 1, 0, 0.503173,-5.31535e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217731,-0.0118895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218152,-0.000641019) , 
6, 1.58266, 1, 0, 0.217964,-0.0402961) , 
4, 3.67089, 1, 0, 0.5,-0.000500865)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560899,0.000428332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575012,0.00785941) , 
1, 37.2865, 1, 0, 0.563481,0.00855574) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554584,0.00098845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431696,-0.00150468) , 
0, 1.08545, 1, 0, 0.485546,-0.0025186) , 
1, 44.8802, 1, 0, 0.5,-0.000464701)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503256,-3.14611e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76133,0.018718) , 
1, 418.782, 1, 0, 0.504307,0.000134364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330458,0.00309079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245926,-0.0117427) , 
4, 2.27699, 1, 0, 0.290231,-0.0294211) , 
0, 2.35076, 1, 0, 0.5,-0.000460203)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.711719,0.00450489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497595,-0.000180681) , 
5, 0.587, 1, 0, 0.511869,0.000306713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.126042,0.000499922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177737,-0.0140844) , 
4, 0.90674, 1, 0, 0.139574,-0.0231434) , 
5, 3.04904, 1, 0, 0.5,-0.000440869)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629875,0.00877431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421691,-0.0122281) , 
1, 48.4069, 1, 0, 0.486459,-0.0354201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.620081,0.0011803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425383,-0.000629348) , 
6, 1.12008, 1, 0, 0.500188,4.43729e-05) , 
3, 15.4339, 1, 0, 0.5,-0.000441352)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.104514,-0.00341896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269791,0.00625576) , 
1, 213.787, 1, 0, 0.116678,-0.0103338) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567853,0.000371909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.178733,-0.0130916) , 
6, 3.0928, 1, 0, 0.564203,0.00121716) , 
4, 0.471263, 1, 0, 0.5,-0.00043997)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615711,-0.0212758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56788,0.00345503) , 
5, 0.543419, 1, 0, 0.569924,0.0117957) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453789,-0.0093632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492948,-0.000197515) , 
3, 16.4923, 1, 0, 0.492369,-0.00180193) , 
1, 24.9387, 1, 0, 0.5,-0.000463963)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554563,0.00131267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.458761,-0.00258287) , 
1, 50.4314, 1, 0, 0.501702,-0.00466891) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440386,-0.000109542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.788943,0.0069445) , 
2, 4.0398, 1, 0, 0.498432,0.00345736) , 
1, 94.7338, 1, 0, 0.5,-0.000440223)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493123,-0.000212025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.639669,0.0100635) , 
1, 246.968, 1, 0, 0.496908,0.000158621) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509678,0.0100446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681898,-0.0160835) , 
2, 2.04478, 1, 0, 0.627007,-0.0262433) , 
1, 299.134, 1, 0, 0.5,-0.000468893)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497342,-0.000101209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.874327,0.0166523) , 
2, 7.01493, 1, 0, 0.502107,-4.45944e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325864,-0.011665) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24183,-0.00248009) , 
6, 1.44546, 1, 0, 0.277998,-0.0411102) , 
0, 2.40038, 1, 0, 0.5,-0.00043062)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503751,0.000146717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630046,-0.00556447) , 
1, 299.134, 1, 0, 0.506752,9.97491e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132391,-0.00271277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838952,-0.0141817) , 
0, 1.90913, 1, 0, 0.115847,-0.0300917) , 
5, 3.19284, 1, 0, 0.5,-0.000421777)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50403,-0.000823617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502378,0.000734549) , 
1, 94.7338, 1, 0, 0.503173,1.60688e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.217731,-0.0113036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218152,-0.000466197) , 
6, 1.58266, 1, 0, 0.217964,-0.0374054) , 
4, 3.67089, 1, 0, 0.5,-0.000400253)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2065,-0.00178227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.715032,0.00455257) , 
2, 2.04478, 1, 0, 0.446619,0.00398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563137,-0.000134117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263261,-0.00701) , 
5, 2.26783, 1, 0, 0.542756,-0.0038529) , 
4, 2.08348, 1, 0, 0.5,-0.000369285)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383545,-0.0224543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669432,0.0051614) , 
3, 71.8831, 1, 0, 0.557428,-0.0390393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586903,0.00174323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474006,-0.000477705) , 
0, 0.732143, 1, 0, 0.499437,-0.000103806) , 
0, 0.130254, 1, 0, 0.5,-0.000482023)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.664742,-0.0114276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.77048,0.0146495) , 
1, 58.0256, 1, 0, 0.742331,0.0259129) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.64714,-0.0127994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493499,-9.92752e-05) , 
5, 0.507603, 1, 0, 0.494931,-0.00101462) , 
5, 0.484609, 1, 0, 0.5,-0.000462937)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491123,-0.00031754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586792,0.0017469) , 
1, 169.514, 1, 0, 0.506472,4.07422e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.114596,-0.00270945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0735183,-0.0105999) , 
1, 99.4411, 1, 0, 0.0882433,-0.0308367) , 
6, 3.26408, 1, 0, 0.5,-0.000437056)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560899,0.000266057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.575012,0.00724823) , 
1, 37.2865, 1, 0, 0.563481,0.0073566) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554584,0.000874682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431696,-0.00132272) , 
0, 1.08545, 1, 0, 0.485546,-0.00218931) , 
1, 44.8802, 1, 0, 0.5,-0.000418878)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787782,0.0197402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628205,-0.000909367) , 
0, 0.742803, 1, 0, 0.672303,0.0153789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597809,-0.00906348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48779,-2.51445e-05) , 
6, 0.587728, 1, 0, 0.490649,-0.00127077) , 
6, 0.539933, 1, 0, 0.5,-0.000413705)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383545,-0.0210609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669432,0.00453247) , 
3, 71.8831, 1, 0, 0.557428,-0.0374277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683654,0.00260335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.472882,-0.000310598) , 
5, 0.700309, 1, 0, 0.499437,-3.52069e-05) , 
0, 0.130254, 1, 0, 0.5,-0.000398436)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615711,-0.0188922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56788,0.00313713) , 
5, 0.543419, 1, 0, 0.569924,0.0107065) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453789,-0.00868122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492948,-0.000171391) , 
3, 16.4923, 1, 0, 0.492369,-0.00160483) , 
1, 24.9387, 1, 0, 0.5,-0.000393432)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503751,0.000143742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630046,-0.00533724) , 
1, 299.134, 1, 0, 0.506752,0.000110091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132391,-0.00245478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0838952,-0.0136119) , 
0, 1.90913, 1, 0, 0.115847,-0.0278977) , 
5, 3.19284, 1, 0, 0.5,-0.000373714)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504109,-0.000802731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502733,0.000727229) , 
1, 94.7338, 1, 0, 0.503395,4.42176e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219169,0.00133458) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224603,-0.00908603) , 
1, 112.895, 1, 0, 0.222235,-0.0330075) , 
4, 3.64609, 1, 0, 0.5,-0.000354939)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.089469,-0.00437969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19681,0.00249997) , 
3, 100.355, 1, 0, 0.116678,-0.00920934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517011,0.00339508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.572384,-0.000389313) , 
4, 1.73387, 1, 0, 0.564203,0.00116035) , 
4, 0.471263, 1, 0, 0.5,-0.00032731)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648014,0.00324824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.69437,-0.0232532) , 
3, 215.035, 1, 0, 0.651125,0.00841617) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470156,-0.00047527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.851294,0.0236117) , 
3, 305.377, 1, 0, 0.474058,-0.00183358) , 
6, 0.716498, 1, 0, 0.5,-0.000331913)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49684,-0.000592264) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.519644,0.000829068) , 
1, 109.69, 1, 0, 0.506472,0.000111111) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.112423,-0.00214793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0743212,-0.0110062) , 
0, 1.61443, 1, 0, 0.0882433,-0.0290873) , 
6, 3.26408, 1, 0, 0.5,-0.000340705)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.501059,-4.8193e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.76133,0.0177647) , 
1, 418.782, 1, 0, 0.502107,2.92626e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.325864,-0.0107734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24183,-0.00209949) , 
6, 1.44546, 1, 0, 0.277998,-0.0371113) , 
0, 2.40038, 1, 0, 0.5,-0.000319867)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
