// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : mdjordje
Date           : Tue Feb 23 09:46:57 2016
Host           : Linux vocms0301.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/m/mdjordje/CMSSW_7_6_3/src/CMGTools/TTHAnalysis/macros/finalMVA/2lss
Training events: 297113
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "0.0336573.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]])) max_Lep_eta                                                    max_Lep_eta                                                    max_Lep_eta                                                                                                                       'F'    [0.00047644416918,2.49998140335]
MT_met_lep1                   MT_met_lep1                   MT_met_lep1                   MT_met_lep1                                                     'F'    [0.0011816623155,1616.76672363]
nJet25_Recl                   numJets_float                 numJets_float                 numJets_float                                                   'F'    [4,13]
mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                                                  'F'    [0.257497280836,4.48677635193]
mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                                                  'F'    [0.201934933662,4.34443044662]
LepGood_conePt[iF_Recl[0]]    LepGood_conePt_iF_Recl_0__    LepGood_conePt[iF_Recl[0]]    LepGood_conePt[iF_Recl[0]]                                      'F'    [20.0009708405,1964.67797852]
LepGood_conePt[iF_Recl[1]]    LepGood_conePt_iF_Recl_1__    LepGood_conePt[iF_Recl[1]]    LepGood_conePt[iF_Recl[1]]                                      'F'    [10.0000810623,671.500915527]
NSpec 3
iF_Recl[0]                    iF0                           iF0                           F                                                               'F'    [0,3]
iF_Recl[1]                    iF1                           iF1                           F                                                               'F'    [0,4]
iF_Recl[2]                    iF2                           iF2                           F                                                               'F'    [0,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]]))", "MT_met_lep1", "nJet25_Recl", "mindr_lep1_jet", "mindr_lep2_jet", "LepGood_conePt[iF_Recl[0]]", "LepGood_conePt[iF_Recl[1]]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479563,-0.00203664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322263,-0.0230865) , 
5, 111.981, 1, 0, 0.442883,-0.0571168) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703262,0.0152151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565101,0.00575807) , 
0, 1.31853, 1, 0, 0.640403,0.140403) , 
2, 5.02985, 1, 0, 0.5,1.84462e-13)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493088,-0.000575775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356174,-0.0165999) , 
5, 87.4532, 1, 0, 0.442883,-0.0536448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685445,0.0136635) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535467,0.0029993) , 
0, 1.6294, 1, 0, 0.640403,0.134947) , 
2, 5.02985, 1, 0, 0.5,0.000890375)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476811,-0.00199637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313949,-0.0219769) , 
5, 118.113, 1, 0, 0.442883,-0.050421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703262,0.0141463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565101,0.00521149) , 
0, 1.31853, 1, 0, 0.640403,0.129718) , 
2, 5.02985, 1, 0, 0.5,0.00167)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502413,0.000454742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37329,-0.012819) , 
5, 75.1892, 1, 0, 0.442883,-0.0473477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613191,0.00812334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789118,0.0186832) , 
2, 7.00995, 1, 0, 0.640403,0.124683) , 
2, 5.02985, 1, 0, 0.5,0.00239858)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438115,-0.00559724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311785,-0.0222008) , 
6, 45.5356, 1, 0, 0.40139,-0.0859339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531631,0.00301163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714236,0.0142624) , 
2, 6.03483, 1, 0, 0.569277,0.0654764) , 
2, 4.04478, 1, 0, 0.5,0.00299833)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476811,-0.00150369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313949,-0.0192927) , 
5, 118.113, 1, 0, 0.442883,-0.042136) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685445,0.0120467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535467,0.00183112) , 
0, 1.6294, 1, 0, 0.640403,0.115961) , 
2, 5.02985, 1, 0, 0.5,0.00358104)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.438115,-0.00510149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.311785,-0.0202355) , 
6, 45.5356, 1, 0, 0.40139,-0.0781385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601452,0.0078282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439667,-0.00648514) , 
3, 1.42343, 1, 0, 0.569277,0.0619216) , 
2, 4.04478, 1, 0, 0.5,0.00412707)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487996,0.000825205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385492,-0.0111788) , 
0, 1.37008, 1, 0, 0.442883,-0.0377156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679683,0.0114473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545673,0.00121603) , 
5, 97.4032, 1, 0, 0.640403,0.10868) , 
2, 5.02985, 1, 0, 0.5,0.00461763)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436786,-0.00489888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286205,-0.0217045) , 
5, 111.981, 1, 0, 0.40139,-0.0711816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531631,0.00265524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714236,0.0129265) , 
2, 6.03483, 1, 0, 0.569277,0.0584888) , 
2, 4.04478, 1, 0, 0.5,0.00498148)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487996,0.000988519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385492,-0.0103282) , 
0, 1.37008, 1, 0, 0.442883,-0.0335098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.703262,0.0118186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565101,0.00307932) , 
0, 1.31853, 1, 0, 0.640403,0.101025) , 
2, 5.02985, 1, 0, 0.5,0.00539362)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432626,-0.00442156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296569,-0.020008) , 
6, 51.4581, 1, 0, 0.40139,-0.0648107) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626072,0.00866042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493041,-0.00117505) , 
5, 78.0518, 1, 0, 0.569277,0.0552043) , 
2, 4.04478, 1, 0, 0.5,0.00568122)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505825,0.00154666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379867,-0.0112602) , 
3, 1.41476, 1, 0, 0.470484,-0.0153375) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756881,0.014169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607718,0.00583525) , 
0, 1.6418, 1, 0, 0.714236,0.160932) , 
2, 6.01493, 1, 0, 0.5,0.00600697)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528056,0.0027472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395817,-0.00816678) , 
5, 78.051, 1, 0, 0.470484,-0.0143224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756881,0.0137184) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607718,0.00559624) , 
0, 1.6418, 1, 0, 0.714236,0.155125) , 
2, 6.01493, 1, 0, 0.5,0.006196)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435369,-0.00289308) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343415,-0.0141367) , 
0, 1.51907, 1, 0, 0.40139,-0.0584501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.623475,0.00821744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494112,-0.00132128) , 
0, 1.39314, 1, 0, 0.569277,0.0519303) , 
2, 4.04478, 1, 0, 0.5,0.00638286)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505825,0.00158197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734197,0.0122513) , 
2, 6.01493, 1, 0, 0.53882,0.0379814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418855,-0.00653711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21576,-0.0370399) , 
5, 145.777, 1, 0, 0.39003,-0.0823255) , 
3, 1.41476, 1, 0, 0.5,0.00659274)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483172,0.000511057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354015,-0.0116596) , 
6, 42.9106, 1, 0, 0.442883,-0.0257864) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679683,0.00960424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545673,5.10688e-05) , 
5, 97.4032, 1, 0, 0.640403,0.0870683) , 
2, 5.02985, 1, 0, 0.5,0.00684783)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520141,0.00280319) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.747832,0.0124393) , 
2, 6.01493, 1, 0, 0.556419,0.0519515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455572,-0.00282199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285293,-0.0243155) , 
1, 144.786, 1, 0, 0.429489,-0.0491217) , 
3, 1.12019, 1, 0, 0.5,0.00702565)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44159,-0.00174888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350763,-0.0117974) , 
0, 1.37008, 1, 0, 0.40139,-0.0509895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628265,0.00804285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500161,-0.000922516) , 
0, 1.31853, 1, 0, 0.569277,0.0480408) , 
2, 4.04478, 1, 0, 0.5,0.00717684)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56674,0.00538152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441714,-0.00499892) , 
4, 1.37667, 1, 0, 0.534325,0.032439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469116,-0.00156802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326439,-0.0157055) , 
5, 58.7025, 1, 0, 0.378691,-0.0815416) , 
3, 1.49893, 1, 0, 0.5,0.00730044)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517954,0.0025245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.398056,-0.00751842) , 
6, 36.3285, 1, 0, 0.470484,-0.00984031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670375,0.0073355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789118,0.0142977) , 
2, 7.02985, 1, 0, 0.714236,0.132549) , 
2, 6.01493, 1, 0, 0.5,0.00740158)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49004,0.00152571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685066,0.00894913) , 
2, 5.02985, 1, 0, 0.559468,0.0506122) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489049,-0.000372363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335348,-0.0137761) , 
5, 87.7275, 1, 0, 0.434258,-0.0402856) , 
3, 1.0781, 1, 0, 0.5,0.00744082)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443177,-0.00119823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628256,0.00759076) , 
2, 4.04478, 1, 0, 0.552949,0.0495606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496115,0.000326202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359146,-0.012652) , 
6, 32.2783, 1, 0, 0.439242,-0.0406395) , 
0, 1.31862, 1, 0, 0.5,0.00755786)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489109,0.000527024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284683,-0.020974) , 
5, 165.126, 1, 0, 0.470484,-0.00841908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670375,0.00683995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789118,0.0136631) , 
2, 7.02985, 1, 0, 0.714236,0.124341) , 
2, 6.01493, 1, 0, 0.5,0.00765687)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581338,0.00582533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408852,-0.00553994) , 
5, 116.756, 1, 0, 0.542303,0.040337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487222,-0.000416497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350035,-0.0132406) , 
6, 29.9586, 1, 0, 0.426338,-0.0490973) , 
0, 1.51759, 1, 0, 0.5,0.00771235)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593135,0.0065133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459215,-0.00329334) , 
4, 1.37197, 1, 0, 0.559468,0.0481311) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462551,-0.00163101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302921,-0.0186827) , 
1, 136.743, 1, 0, 0.434258,-0.0368425) , 
3, 1.0781, 1, 0, 0.5,0.00777343)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464977,0.00113825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37457,-0.0077685) , 
0, 0.910663, 1, 0, 0.40139,-0.0422101) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626072,0.00692717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493041,-0.00108784) , 
5, 78.0518, 1, 0, 0.569277,0.0429397) , 
2, 4.04478, 1, 0, 0.5,0.00780339)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559161,0.0043127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41775,-0.00561222) , 
6, 49.4927, 1, 0, 0.527389,0.0257002) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397502,-0.00648112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256342,-0.0244483) , 
1, 104.571, 1, 0, 0.356594,-0.0857825) , 
3, 1.64622, 1, 0, 0.5,0.00782281)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.446506,-0.000648217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.632082,0.00721639) , 
2, 4.04478, 1, 0, 0.556741,0.0489914) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503603,0.00070441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37131,-0.00987916) , 
6, 30.987, 1, 0, 0.445073,-0.0319628) , 
0, 1.24401, 1, 0, 0.5,0.00785691)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489109,0.000506666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284683,-0.0184997) , 
5, 165.126, 1, 0, 0.470484,-0.00691457) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.00764915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0166543) , 
2, 8.01493, 1, 0, 0.714236,0.115181) , 
2, 6.01493, 1, 0, 0.5,0.00787002)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42595,-0.00207822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60573,0.00572197) , 
2, 4.04478, 1, 0, 0.532133,0.031569) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462824,-0.00251651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305959,-0.0173143) , 
6, 36.6114, 1, 0, 0.412194,-0.0569026) , 
0, 1.71655, 1, 0, 0.5,0.00786638)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597173,0.00635383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47671,-0.00187351) , 
4, 1.2118, 1, 0, 0.554952,0.0409974) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468785,-0.00112598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.318949,-0.0137228) , 
6, 44.5029, 1, 0, 0.426997,-0.0360553) , 
3, 1.14123, 1, 0, 0.5,0.00790608)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52459,0.00289944) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416783,-0.00472433) , 
0, 1.25833, 1, 0, 0.470484,-0.0059963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670375,0.00585051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789118,0.0125309) , 
2, 7.02985, 1, 0, 0.714236,0.108705) , 
2, 6.01493, 1, 0, 0.5,0.00789284)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571404,0.00481042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448654,-0.00277464) , 
0, 1.51907, 1, 0, 0.525141,0.0235439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434132,-0.00243249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.307956,-0.0168298) , 
4, 0.899138, 1, 0, 0.362812,-0.078033) , 
6, 59.3658, 1, 0, 0.5,0.00781212)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513696,0.00217701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390585,-0.0050979) , 
5, 62.9251, 1, 0, 0.442883,-0.0152321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.679683,0.00749146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545673,-0.000529265) , 
5, 97.4032, 1, 0, 0.640403,0.0643672) , 
2, 5.02985, 1, 0, 0.5,0.00778569)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606448,0.00652767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490847,-0.000763551) , 
4, 1.12989, 1, 0, 0.559468,0.0417501) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.460442,-0.00136875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290055,-0.0176896) , 
1, 144.786, 1, 0, 0.434258,-0.0298294) , 
3, 1.0781, 1, 0, 0.5,0.00775382)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559037,0.00411303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438926,-0.00414834) , 
4, 1.37667, 1, 0, 0.527389,0.0229787) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.397502,-0.0054953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256342,-0.0209814) , 
1, 104.571, 1, 0, 0.356594,-0.0721681) , 
3, 1.64622, 1, 0, 0.5,0.00772092)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489109,0.000559205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284683,-0.0164674) , 
5, 165.126, 1, 0, 0.470484,-0.0050449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.00663936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0155497) , 
2, 8.01493, 1, 0, 0.714236,0.100093) , 
2, 6.01493, 1, 0, 0.5,0.00768628)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570116,0.00435479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400184,-0.00482789) , 
5, 116.752, 1, 0, 0.532133,0.0283964) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475028,-0.0012587) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329541,-0.0129229) , 
6, 29.9586, 1, 0, 0.412194,-0.0490732) , 
0, 1.71655, 1, 0, 0.5,0.00764136)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464977,0.00121269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37457,-0.00616157) , 
0, 0.910663, 1, 0, 0.40139,-0.0322297) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626072,0.00579144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493041,-0.000866809) , 
5, 78.0518, 1, 0, 0.569277,0.0356056) , 
2, 4.04478, 1, 0, 0.5,0.00761395)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586782,0.00535993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389718,-0.00688719) , 
6, 69.239, 1, 0, 0.562915,0.0461765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512156,0.00107649) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383471,-0.00712074) , 
6, 30.987, 1, 0, 0.454413,-0.0204207) , 
0, 1.11966, 1, 0, 0.5,0.0075601)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587038,0.00527022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411321,-0.00358054) , 
3, 1.40857, 1, 0, 0.546172,0.0382553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5276,0.00169762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385508,-0.00748844) , 
5, 62.3909, 1, 0, 0.448007,-0.0271697) , 
4, 1.08814, 1, 0, 0.5,0.00748244)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541044,0.00370717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436947,-0.00277374) , 
0, 0.947912, 1, 0, 0.470484,-0.00447243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670375,0.00488733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.789118,0.0114544) , 
2, 7.02985, 1, 0, 0.714236,0.0938201) , 
2, 6.01493, 1, 0, 0.5,0.00742982)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593135,0.00508683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459215,-0.00245444) , 
4, 1.37197, 1, 0, 0.559468,0.0372085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.456067,-0.00140531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26835,-0.018685) , 
1, 160.873, 1, 0, 0.434258,-0.0257447) , 
3, 1.0781, 1, 0, 0.5,0.00730924)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564418,0.00391384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437595,-0.00344527) , 
0, 1.74257, 1, 0, 0.530249,0.0227839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469833,0.00111134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337381,-0.0112798) , 
4, 0.781111, 1, 0, 0.379978,-0.0543407) , 
6, 52.7837, 1, 0, 0.5,0.00725911)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.413903,-0.00262941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202626,-0.0236089) , 
5, 191.698, 1, 0, 0.40139,-0.0291961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595563,0.00420216) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.418784,-0.00601909) , 
5, 136.102, 1, 0, 0.569277,0.0327704) , 
2, 4.04478, 1, 0, 0.5,0.00720049)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541044,0.00348695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436947,-0.00257099) , 
0, 0.947912, 1, 0, 0.470484,-0.00396567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.0058323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0146488) , 
2, 8.01493, 1, 0, 0.714236,0.0880549) , 
2, 6.01493, 1, 0, 0.5,0.0071771)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593781,0.00514804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425428,-0.00224436) , 
3, 1.35287, 1, 0, 0.549745,0.0376571) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532251,0.00176933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391529,-0.00634169) , 
5, 62.3909, 1, 0, 0.453381,-0.0216309) , 
4, 1.02631, 1, 0, 0.5,0.00705146)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557165,0.00353734) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448474,-0.00322916) , 
1, 121.62, 1, 0, 0.527389,0.0196456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.40035,-0.00426571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270061,-0.0162366) , 
1, 96.527, 1, 0, 0.356594,-0.0593415) , 
3, 1.64622, 1, 0, 0.5,0.00697922)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53438,0.00224949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411757,-0.0040767) , 
6, 36.3285, 1, 0, 0.486463,0.00068207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00866296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0142245) , 
2, 8.02488, 1, 0, 0.789118,0.139828) , 
2, 7.04478, 1, 0, 0.5,0.00690578)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42595,-0.00152429) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60573,0.00443372) , 
2, 4.04478, 1, 0, 0.532133,0.0242313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475028,-0.00112175) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329541,-0.0108084) , 
6, 29.9586, 1, 0, 0.412194,-0.0409078) , 
0, 1.71655, 1, 0, 0.5,0.00677972)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585863,0.00463625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404931,-0.00716897) , 
4, 1.77543, 1, 0, 0.569848,0.0415646) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486504,0.000159934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355973,-0.00897104) , 
1, 120.655, 1, 0, 0.454698,-0.0158311) , 
3, 0.909774, 1, 0, 0.5,0.0067495)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575704,0.00392316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454112,-0.00168971) , 
0, 1.39491, 1, 0, 0.522968,0.0176176) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425401,-0.00234261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298114,-0.0140388) , 
4, 0.899138, 1, 0, 0.353967,-0.0630446) , 
6, 62.6569, 1, 0, 0.5,0.00665526)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499423,0.000747014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271502,-0.0175304) , 
5, 194.151, 1, 0, 0.486463,0.000673704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.0082759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0138035) , 
2, 8.02488, 1, 0, 0.789118,0.132997) , 
2, 7.04478, 1, 0, 0.5,0.00659226)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571983,0.00409169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350362,-0.00729327) , 
3, 1.76131, 1, 0, 0.549745,0.0346047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525194,0.00185801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4054,-0.00536544) , 
6, 24.8065, 1, 0, 0.453381,-0.0198506) , 
4, 1.02631, 1, 0, 0.5,0.00649375)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458582,-0.000136451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.664394,0.00526313) , 
2, 5.02985, 1, 0, 0.51854,0.0173626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464185,-0.00212914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332479,-0.0117299) , 
6, 24.2461, 1, 0, 0.390956,-0.0580253) , 
0, 1.99013, 1, 0, 0.5,0.0064074)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585863,0.00433148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404931,-0.00653089) , 
4, 1.77543, 1, 0, 0.569848,0.0387838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476034,-0.000415818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299757,-0.013501) , 
1, 160.873, 1, 0, 0.454698,-0.0146922) , 
3, 0.909774, 1, 0, 0.5,0.00634627)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588702,0.00469988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331,-0.0114816) , 
5, 196.608, 1, 0, 0.572489,0.0438751) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525577,0.00147023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400138,-0.00484817) , 
6, 29.7465, 1, 0, 0.465538,-0.0116108) , 
0, 0.945563, 1, 0, 0.5,0.0062679)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507265,0.000927111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313228,-0.0103647) , 
5, 155.451, 1, 0, 0.486463,0.000615417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00780977) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0133204) , 
2, 8.02488, 1, 0, 0.789118,0.125066) , 
2, 7.04478, 1, 0, 0.5,0.00618185)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582097,0.00386982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420286,-0.00236358) , 
3, 1.3343, 1, 0, 0.537327,0.025124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534145,0.00202891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3874,-0.00607593) , 
5, 50.2799, 1, 0, 0.43242,-0.0283743) , 
4, 1.25302, 1, 0, 0.5,0.00608859)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543047,0.00307937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439071,-0.00205402) , 
0, 0.910663, 1, 0, 0.470484,-0.00319976) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.00491624) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0129774) , 
2, 8.01493, 1, 0, 0.714236,0.0729951) , 
2, 6.01493, 1, 0, 0.5,0.00602669)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477847,0.00182961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38434,-0.00391034) , 
0, 0.687165, 1, 0, 0.40139,-0.0232306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591967,0.00350314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44298,-0.00471012) , 
0, 1.96513, 1, 0, 0.569277,0.0263918) , 
2, 4.04478, 1, 0, 0.5,0.00591559)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550692,0.00280878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433723,-0.00296046) , 
4, 1.37667, 1, 0, 0.517302,0.0136262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.4486,0.000987271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305473,-0.0126762) , 
4, 0.610071, 1, 0, 0.330484,-0.0703744) , 
6, 72.53, 1, 0, 0.5,0.00584668)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578458,0.0038886) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462074,-0.00108973) , 
6, 31.9015, 1, 0, 0.528929,0.0203835) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515197,0.000941032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37555,-0.0068821) , 
3, 0.773425, 1, 0, 0.421393,-0.0339234) , 
1, 120.655, 1, 0, 0.5,0.00577395)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49004,0.00087532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.685066,0.00530796) , 
2, 5.02985, 1, 0, 0.559468,0.0282412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474076,-7.41262e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.36404,-0.00661783) , 
1, 96.5245, 1, 0, 0.434258,-0.0192523) , 
3, 1.0781, 1, 0, 0.5,0.00568444)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428926,-0.00111952) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610117,0.00380086) , 
2, 4.04478, 1, 0, 0.53601,0.0212346) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480528,-0.000681938) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336698,-0.00809833) , 
6, 29.9586, 1, 0, 0.417834,-0.0300068) , 
0, 1.64194, 1, 0, 0.5,0.00562056)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499423,0.000628666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271502,-0.01493) , 
5, 194.151, 1, 0, 0.486463,0.000574849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00805027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.015879) , 
2, 9.0199, 1, 0, 0.789118,0.112612) , 
2, 7.04478, 1, 0, 0.5,0.00558605)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57349,0.00384419) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.423746,-0.00376693) , 
1, 160.873, 1, 0, 0.551862,0.0309525) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536254,0.00149961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395528,-0.00478808) , 
5, 62.3909, 1, 0, 0.457322,-0.015449) , 
4, 0.985093, 1, 0, 0.5,0.00549806)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494945,0.00122267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709546,0.0058542) , 
2, 5.02985, 1, 0, 0.558459,0.029541) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.515434,0.00103277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39566,-0.00440097) , 
6, 25.7403, 1, 0, 0.448137,-0.0159784) , 
0, 1.20671, 1, 0, 0.5,0.00542054)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538065,0.00211848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391033,-0.0063519) , 
4, 1.74764, 1, 0, 0.521772,0.0136528) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364543,-0.00494851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270706,-0.0159979) , 
3, 2.25862, 1, 0, 0.33948,-0.0558362) , 
3, 1.77246, 1, 0, 0.5,0.00535327)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550546,0.00242869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376992,-0.00454186) , 
5, 126.426, 1, 0, 0.51854,0.0143785) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468805,-0.00156802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342362,-0.00908994) , 
6, 22.2111, 1, 0, 0.390956,-0.0481786) , 
0, 1.99013, 1, 0, 0.5,0.00528787)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503956,0.000731189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316654,-0.00942963) , 
6, 72.53, 1, 0, 0.486463,0.000469131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00769261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0155135) , 
2, 9.0199, 1, 0, 0.789118,0.106744) , 
2, 7.04478, 1, 0, 0.5,0.00522259)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582517,0.00355902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38366,-0.00755346) , 
4, 1.89647, 1, 0, 0.569848,0.0323464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493631,0.000540752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388551,-0.00523394) , 
1, 96.5245, 1, 0, 0.454698,-0.0125164) , 
3, 0.909774, 1, 0, 0.5,0.00513346)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58923,0.00436724) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495384,-0.000136898) , 
1, 96.5245, 1, 0, 0.551862,0.0284052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53628,0.00223729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419872,-0.0036813) , 
6, 21.8452, 1, 0, 0.457322,-0.014172) , 
4, 0.985093, 1, 0, 0.5,0.00504858)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508626,0.00181885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722923,0.00626064) , 
2, 5.03483, 1, 0, 0.572489,0.0356019) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541196,0.00165432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414427,-0.00326432) , 
5, 58.701, 1, 0, 0.465538,-0.00961954) , 
0, 0.945563, 1, 0, 0.5,0.00495176)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61025,0.00437058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455245,-0.00107084) , 
5, 120.626, 1, 0, 0.577043,0.036622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487457,-4.75475e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317131,-0.009944) , 
1, 160.873, 1, 0, 0.466269,-0.00901614) , 
3, 0.804568, 1, 0, 0.5,0.00488095)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50407,0.000851077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378903,-0.00605101) , 
0, 2.00332, 1, 0, 0.486463,0.000307768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00635362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0118242) , 
2, 8.02488, 1, 0, 0.789118,0.101068) , 
2, 7.04478, 1, 0, 0.5,0.00481457)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553345,0.00238338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434869,-0.00259557) , 
4, 1.37667, 1, 0, 0.521772,0.0121737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.364543,-0.00447112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.270706,-0.0145914) , 
3, 2.25862, 1, 0, 0.33948,-0.0502953) , 
3, 1.77246, 1, 0, 0.5,0.00471264)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499423,0.000524321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271502,-0.0129951) , 
5, 194.151, 1, 0, 0.486463,0.000335392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.0070697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0149304) , 
2, 9.0199, 1, 0, 0.789118,0.0970122) , 
2, 7.04478, 1, 0, 0.5,0.00465955)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467403,0.000730747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651363,0.00496633) , 
2, 4.0398, 1, 0, 0.577218,0.0372) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.531754,0.00128176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407001,-0.0035183) , 
6, 29.7465, 1, 0, 0.471611,-0.00740019) , 
0, 0.84608, 1, 0, 0.5,0.00458898)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587545,0.00359891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370679,-0.00839584) , 
4, 1.99501, 1, 0, 0.577043,0.034053) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50988,0.000583572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367803,-0.00523631) , 
6, 41.8488, 1, 0, 0.466269,-0.00840622) , 
3, 0.804568, 1, 0, 0.5,0.00452285)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505691,0.00138686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428615,-0.00255026) , 
1, 88.4809, 1, 0, 0.470484,-0.00271225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.00384523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0112726) , 
2, 8.01493, 1, 0, 0.714236,0.0565428) , 
2, 6.01493, 1, 0, 0.5,0.00446295)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42595,-0.00110148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60573,0.00305618) , 
2, 4.04478, 1, 0, 0.532133,0.0159933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.458784,-0.00145959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299381,-0.00905678) , 
6, 38.829, 1, 0, 0.412194,-0.0273651) , 
0, 1.71655, 1, 0, 0.5,0.00437707)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579566,0.0038751) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360733,-0.00653871) , 
6, 92.2763, 1, 0, 0.566112,0.0361268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50978,0.000414159) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343754,-0.00696551) , 
6, 51.4581, 1, 0, 0.476254,-0.00704884) , 
4, 0.75839, 1, 0, 0.5,0.00436091)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59001,0.00327746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486206,-0.00115242) , 
1, 121.62, 1, 0, 0.559468,0.0220243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48723,0.00127585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405151,-0.00361563) , 
1, 56.3064, 1, 0, 0.434258,-0.0152823) , 
3, 1.0781, 1, 0, 0.5,0.00430573)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498602,0.00110467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.714983,0.00519565) , 
2, 5.02985, 1, 0, 0.562915,0.0260493) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496564,0.00102196) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421083,-0.00331321) , 
1, 72.3937, 1, 0, 0.454413,-0.0115794) , 
0, 1.11966, 1, 0, 0.5,0.00423028)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430721,-0.000709139) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614377,0.00350315) , 
2, 4.04478, 1, 0, 0.549745,0.0230139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532807,0.00189668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415522,-0.00341907) , 
6, 21.8452, 1, 0, 0.453381,-0.0135039) , 
4, 1.02631, 1, 0, 0.5,0.00416267)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532409,0.00162121) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299668,-0.0102754) , 
5, 194.151, 1, 0, 0.51854,0.0115919) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401544,-0.00384504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274201,-0.0185066) , 
4, 2.20726, 1, 0, 0.390956,-0.0398616) , 
0, 1.99013, 1, 0, 0.5,0.00411482)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503956,0.000579811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316654,-0.00786807) , 
6, 72.53, 1, 0, 0.486463,0.000159735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00645772) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0143318) , 
2, 9.0199, 1, 0, 0.789118,0.0874628) , 
2, 7.04478, 1, 0, 0.5,0.00406463)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592403,0.00365436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365468,-0.00834359) , 
4, 1.9997, 1, 0, 0.581838,0.0348224) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493648,0.00010829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328458,-0.00803887) , 
1, 160.873, 1, 0, 0.472684,-0.00628741) , 
3, 0.741445, 1, 0, 0.5,0.00400055)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593468,0.003548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337036,-0.00734881) , 
5, 196.608, 1, 0, 0.577218,0.033073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536694,0.00129533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420032,-0.00265704) , 
6, 26.4554, 1, 0, 0.471611,-0.00676822) , 
0, 0.84608, 1, 0, 0.5,0.00394167)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535564,0.00160519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390016,-0.00512785) , 
4, 1.74764, 1, 0, 0.5193,0.00982198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343478,-0.0054119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.225972,-0.0208827) , 
3, 2.58742, 1, 0, 0.331106,-0.0481431) , 
3, 1.83559, 1, 0, 0.5,0.00387746)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498698,0.00055684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366995,-0.00655788) , 
0, 2.12748, 1, 0, 0.486463,0.000106201) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00524747) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0106334) , 
2, 8.02488, 1, 0, 0.789118,0.0835179) , 
2, 7.04478, 1, 0, 0.5,0.00383704)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57843,0.00349499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381194,-0.0056774) , 
1, 225.222, 1, 0, 0.566112,0.032222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56747,0.00224679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436723,-0.00224185) , 
5, 50.2799, 1, 0, 0.476254,-0.00647086) , 
4, 0.75839, 1, 0, 0.5,0.00375426)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590058,0.00314535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369962,-0.00672922) , 
6, 88.9853, 1, 0, 0.577043,0.0290054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574645,0.00290401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443144,-0.00176402) , 
5, 39.351, 1, 0, 0.466269,-0.00739723) , 
3, 0.804568, 1, 0, 0.5,0.00368758)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543047,0.00202783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439071,-0.0014233) , 
0, 0.910663, 1, 0, 0.470484,-0.00254452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.693685,0.00329831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.0103579) , 
2, 8.01493, 1, 0, 0.714236,0.0483735) , 
2, 6.01493, 1, 0, 0.5,0.00362115)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574094,0.00278444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440351,-0.00167115) , 
6, 40.1148, 1, 0, 0.534807,0.0169103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459998,-0.0012255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284426,-0.0136576) , 
1, 278.046, 1, 0, 0.447367,-0.0166169) , 
1, 96.5245, 1, 0, 0.5,0.0035643)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540751,0.00155832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379726,-0.00596428) , 
4, 1.85069, 1, 0, 0.527389,0.0106441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378114,-0.00293417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271629,-0.012048) , 
3, 2.25391, 1, 0, 0.356594,-0.0338019) , 
3, 1.64622, 1, 0, 0.5,0.00351669)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644461,0.00477554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518261,0.00157996) , 
3, 0.851598, 1, 0, 0.566112,0.0302521) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546279,0.00166705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430968,-0.00244899) , 
6, 24.8065, 1, 0, 0.476254,-0.00612611) , 
4, 0.75839, 1, 0, 0.5,0.00348733)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443177,-0.00055047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628256,0.00307029) , 
2, 4.04478, 1, 0, 0.552949,0.0182696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481439,0.000580497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402454,-0.00363709) , 
1, 75.1585, 1, 0, 0.439242,-0.0136111) , 
0, 1.31862, 1, 0, 0.5,0.00342399)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505048,0.000490314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300238,-0.00754919) , 
5, 165.126, 1, 0, 0.486463,-2.9636e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.0057168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0136116) , 
2, 9.0199, 1, 0, 0.789118,0.0764526) , 
2, 7.04478, 1, 0, 0.5,0.00339126)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533117,0.00147507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.389041,-0.00394063) , 
1, 160.873, 1, 0, 0.512439,0.00833318) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.389912,-0.00462839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262982,-0.0185953) , 
4, 2.20726, 1, 0, 0.378131,-0.04547) , 
0, 2.12692, 1, 0, 0.5,0.00335021)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504703,0.00143428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704785,0.00478903) , 
2, 5.02985, 1, 0, 0.581838,0.0303069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505074,0.000279082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341528,-0.00555984) , 
6, 52.4651, 1, 0, 0.472684,-0.00572237) , 
3, 0.741445, 1, 0, 0.5,0.00329416)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585736,0.00298631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327027,-0.0107609) , 
1, 277.246, 1, 0, 0.577218,0.0285069) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517844,0.00169337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449067,-0.00191689) , 
1, 56.3064, 1, 0, 0.471611,-0.00601111) , 
0, 0.84608, 1, 0, 0.5,0.00326783)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432866,-0.000564927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615812,0.00303756) , 
2, 4.04478, 1, 0, 0.551862,0.0199522) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53628,0.00164014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.419872,-0.00276153) , 
6, 21.8452, 1, 0, 0.457322,-0.0105957) , 
4, 0.985093, 1, 0, 0.5,0.00319454)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499756,0.000384234) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296908,-0.00848088) , 
6, 82.4032, 1, 0, 0.486463,-8.07365e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00544487) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0133269) , 
2, 9.0199, 1, 0, 0.789118,0.0724539) , 
2, 7.04478, 1, 0, 0.5,0.00316359)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443508,-0.000698729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620089,0.00269328) , 
2, 4.04478, 1, 0, 0.559468,0.0173213) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443409,-0.00105513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.160925,-0.0257345) , 
5, 232.853, 1, 0, 0.434258,-0.012584) , 
3, 1.0781, 1, 0, 0.5,0.00311794)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428926,-0.00077304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610117,0.00242676) , 
2, 4.04478, 1, 0, 0.53601,0.0128699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434232,-0.00150475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26654,-0.0118617) , 
3, 1.99974, 1, 0, 0.417834,-0.0191203) , 
0, 1.64194, 1, 0, 0.5,0.00312198)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659736,0.00653913) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.55408,0.00206815) , 
0, 0.472986, 1, 0, 0.566112,0.0273529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545358,0.00114452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.409078,-0.00271997) , 
5, 68.4463, 1, 0, 0.476254,-0.00559596) , 
4, 0.75839, 1, 0, 0.5,0.00311122)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507176,0.0015907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.712727,0.00494212) , 
2, 5.03483, 1, 0, 0.587857,0.0322139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519318,0.00110153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437031,-0.00221664) , 
1, 80.4373, 1, 0, 0.478619,-0.00403179) , 
3, 0.678321, 1, 0, 0.5,0.00306255)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60109,0.00400166) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334341,-0.00880588) , 
1, 281.067, 1, 0, 0.592441,0.0401789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499379,0.000129046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290257,-0.00936958) , 
6, 82.4032, 1, 0, 0.486299,-0.00250925) , 
0, 0.560067, 1, 0, 0.5,0.0030012)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.482288,0.000209046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729381,0.00412296) , 
2, 6.01493, 1, 0, 0.512439,0.00747186) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498128,0.00164791) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361116,-0.00639495) , 
6, 14.0709, 1, 0, 0.378131,-0.0413521) , 
0, 2.12692, 1, 0, 0.5,0.00295003)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570021,0.0026515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46743,-0.000701455) , 
0, 0.687165, 1, 0, 0.486463,-8.72374e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00505048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0129742) , 
2, 9.0199, 1, 0, 0.789118,0.0668976) , 
2, 7.04478, 1, 0, 0.5,0.00290886)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507704,0.00159679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720967,0.00534669) , 
2, 5.03483, 1, 0, 0.592839,0.0344786) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503139,0.000270178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347213,-0.00563146) , 
1, 160.873, 1, 0, 0.482525,-0.00311208) , 
3, 0.636239, 1, 0, 0.5,0.00284284)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564008,0.00198097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3259,-0.00637963) , 
3, 1.87271, 1, 0, 0.546172,0.0157133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535794,0.00204964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42024,-0.0025836) , 
6, 18.884, 1, 0, 0.448007,-0.0117319) , 
4, 1.08814, 1, 0, 0.5,0.00280437)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573316,0.00263615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279107,-0.0127959) , 
5, 281.226, 1, 0, 0.566112,0.0249989) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56747,0.00178522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.436723,-0.00179863) , 
5, 50.2799, 1, 0, 0.476254,-0.00519843) , 
4, 0.75839, 1, 0, 0.5,0.00278162)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414848,-0.00105215) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590666,0.00189497) , 
2, 4.04478, 1, 0, 0.51854,0.00822978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401544,-0.00284775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274201,-0.014614) , 
4, 2.20726, 1, 0, 0.390956,-0.0295602) , 
0, 1.99013, 1, 0, 0.5,0.00273823)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563062,0.00171964) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425712,-0.00273709) , 
4, 1.54155, 1, 0, 0.53882,0.0105245) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406773,-0.00159902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271251,-0.0101064) , 
3, 2.25537, 1, 0, 0.39003,-0.0193752) , 
3, 1.41476, 1, 0, 0.5,0.00272352)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570847,0.00253758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41124,-0.00261227) , 
6, 49.8121, 1, 0, 0.540036,0.0176119) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544249,0.00122022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43131,-0.00224364) , 
0, 0.957945, 1, 0, 0.468857,-0.00888233) , 
1, 72.3937, 1, 0, 0.5,0.00270966)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49284,0.000196732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231992,-0.0153031) , 
5, 252.201, 1, 0, 0.486463,-0.000141242) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00382393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.00915804) , 
2, 8.02488, 1, 0, 0.789118,0.0626995) , 
2, 7.04478, 1, 0, 0.5,0.0026695)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592403,0.00268079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365468,-0.00665811) , 
4, 1.9997, 1, 0, 0.581838,0.0248113) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579998,0.00244998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449792,-0.00128552) , 
5, 39.351, 1, 0, 0.472684,-0.00477364) , 
3, 0.741445, 1, 0, 0.5,0.00263015)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604527,0.00381968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336659,-0.00843378) , 
1, 275.088, 1, 0, 0.59531,0.0380631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498603,0.000104465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280163,-0.00973066) , 
6, 88.9853, 1, 0, 0.487788,-0.00196171) , 
0, 0.522761, 1, 0, 0.5,0.00258416)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496608,0.000346544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.362358,-0.00554026) , 
0, 2.17715, 1, 0, 0.486463,-0.000163849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00367577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.00893211) , 
2, 8.02488, 1, 0, 0.789118,0.0602819) , 
2, 7.04478, 1, 0, 0.5,0.00253977)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574094,0.00217807) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440351,-0.00147752) , 
6, 40.1148, 1, 0, 0.534807,0.0126313) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455989,-0.00107549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.251208,-0.0151953) , 
1, 323.427, 1, 0, 0.447367,-0.0128473) , 
1, 96.5245, 1, 0, 0.5,0.00248915)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507704,0.00141142) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720967,0.00492693) , 
2, 5.03483, 1, 0, 0.592839,0.0311092) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568964,0.00234881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463203,-0.000992572) , 
0, 0.687165, 1, 0, 0.482525,-0.00292777) , 
3, 0.636239, 1, 0, 0.5,0.00246418)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575229,0.00244858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.284412,-0.00927189) , 
3, 2.16976, 1, 0, 0.566112,0.0229364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546279,0.00132901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430968,-0.00197629) , 
6, 24.8065, 1, 0, 0.476254,-0.00495468) , 
4, 0.75839, 1, 0, 0.5,0.00241591)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565509,0.00268132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380228,-0.00340059) , 
6, 63.0824, 1, 0, 0.544741,0.0221048) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539768,0.000670853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402578,-0.00264319) , 
3, 1.14123, 1, 0, 0.483122,-0.00505617) , 
1, 48.2628, 1, 0, 0.5,0.0023834)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560775,0.0015687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.306686,-0.0104215) , 
1, 281.528, 1, 0, 0.552949,0.0135838) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517478,0.0011864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408487,-0.00229904) , 
3, 0.80847, 1, 0, 0.439242,-0.0105359) , 
0, 1.31862, 1, 0, 0.5,0.00235219)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499423,0.000264459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271502,-0.0079956) , 
5, 194.151, 1, 0, 0.486463,-0.000237869) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00434228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0123016) , 
2, 9.0199, 1, 0, 0.789118,0.0571597) , 
2, 7.04478, 1, 0, 0.5,0.00232941)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613781,0.00300434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437634,-0.000196631) , 
3, 1.35672, 1, 0, 0.569315,0.0238846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570377,0.0016085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440227,-0.00151621) , 
5, 50.2799, 1, 0, 0.47944,-0.0040965) , 
4, 0.717171, 1, 0, 0.5,0.00230457)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42595,-0.000734878) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60573,0.00187659) , 
2, 4.04478, 1, 0, 0.532133,0.00927862) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519094,0.00219078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396639,-0.0027493) , 
6, 14.4354, 1, 0, 0.412194,-0.016871) , 
0, 1.71655, 1, 0, 0.5,0.00227279)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558796,0.00223072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358528,-0.00464865) , 
6, 71.0445, 1, 0, 0.543038,0.0187174) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537607,0.000560146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39844,-0.00260713) , 
3, 1.12586, 1, 0, 0.479179,-0.00569593) , 
1, 56.3064, 1, 0, 0.5,0.00226379)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.670045,0.00580194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.576819,0.00250022) , 
4, 0.638495, 1, 0, 0.59531,0.0341166) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507687,0.000291125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365636,-0.00409047) , 
1, 160.873, 1, 0, 0.487788,-0.00184968) , 
0, 0.522761, 1, 0, 0.5,0.00223523)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495621,0.000283555) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359971,-0.00537137) , 
0, 2.20198, 1, 0, 0.486463,-0.000255916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.75377,0.00326795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.858454,0.00845733) , 
2, 8.02488, 1, 0, 0.789118,0.0544247) , 
2, 7.04478, 1, 0, 0.5,0.00218984)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507704,0.00122617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720967,0.00455406) , 
2, 5.03483, 1, 0, 0.592839,0.0280496) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556462,0.00167261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.457351,-0.00107123) , 
6, 19.8732, 1, 0, 0.482525,-0.00272752) , 
3, 0.636239, 1, 0, 0.5,0.00214803)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433979,-0.000377316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618656,0.00239527) , 
2, 4.04478, 1, 0, 0.554848,0.0157772) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541749,0.00139318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.426342,-0.00199724) , 
6, 21.8452, 1, 0, 0.46326,-0.00704473) , 
4, 0.923265, 1, 0, 0.5,0.00211019)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534385,0.000985152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357483,-0.0064849) , 
4, 1.99496, 1, 0, 0.524425,0.00650935) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.359078,-0.00270432) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228824,-0.0152239) , 
3, 2.57988, 1, 0, 0.348693,-0.025241) , 
3, 1.70934, 1, 0, 0.5,0.00209641)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565509,0.00240848) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380228,-0.00305643) , 
6, 63.0824, 1, 0, 0.544741,0.0197662) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49379,-0.00012001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349786,-0.00637035) , 
0, 2.17654, 1, 0, 0.483122,-0.00457671) , 
1, 48.2628, 1, 0, 0.5,0.00209098)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.475058,-6.97678e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.718442,0.00301935) , 
2, 6.01493, 1, 0, 0.504547,0.00344963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.343676,0.000241632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206974,-0.0201924) , 
4, 0.55173, 1, 0, 0.228627,-0.0814741) , 
5, 281.226, 1, 0, 0.5,0.00205016)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604527,0.00324391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336659,-0.00692106) , 
1, 275.088, 1, 0, 0.59531,0.0320895) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500879,0.000108856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292958,-0.00717445) , 
6, 82.4032, 1, 0, 0.487788,-0.00181533) , 
0, 0.522761, 1, 0, 0.5,0.00203546)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507704,0.00117083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720967,0.00431765) , 
2, 5.03483, 1, 0, 0.592839,0.0265106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585617,0.00202702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460778,-0.000864584) , 
5, 39.351, 1, 0, 0.482525,-0.00260705) , 
3, 0.636239, 1, 0, 0.5,0.00200561)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575266,0.00225154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28008,-0.0124372) , 
6, 131.769, 1, 0, 0.569315,0.0212704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511169,0.000234051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335721,-0.0045008) , 
5, 122.946, 1, 0, 0.47944,-0.00375152) , 
4, 0.717171, 1, 0, 0.5,0.0019726)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494032,0.000441199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708047,0.00296438) , 
2, 5.02985, 1, 0, 0.557235,0.0127932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541684,0.00212617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430596,-0.00151995) , 
6, 15.2469, 1, 0, 0.446149,-0.00822676) , 
0, 1.23158, 1, 0, 0.5,0.00196302)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571707,0.00167836) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466175,-0.000599387) , 
0, 0.84608, 1, 0, 0.494503,0.000667742) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00632078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0117784) , 
2, 9.0199, 1, 0, 0.858454,0.0854805) , 
2, 8.02985, 1, 0, 0.5,0.00194867)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574094,0.00180929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.440351,-0.00129028) , 
6, 40.1148, 1, 0, 0.534807,0.0102512) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.457477,-0.000829924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302999,-0.0088176) , 
0, 2.18966, 1, 0, 0.447367,-0.0107196) , 
1, 96.5245, 1, 0, 0.5,0.00190344)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534106,0.000968664) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.280908,-0.009236) , 
3, 2.10912, 1, 0, 0.524047,0.00698635) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412393,-0.00166837) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.308948,-0.00961713) , 
0, 2.25266, 1, 0, 0.403434,-0.0185926) , 
4, 1.54155, 1, 0, 0.5,0.00188654)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529821,0.00155325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470275,-0.000680853) , 
1, 48.2628, 1, 0, 0.486463,-0.000302994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00370759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0115683) , 
2, 9.0199, 1, 0, 0.789118,0.0485064) , 
2, 7.04478, 1, 0, 0.5,0.00188015)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598918,0.00261448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304032,-0.0138351) , 
4, 2.25952, 1, 0, 0.592839,0.0250618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503139,0.000169834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347213,-0.00419686) , 
1, 160.873, 1, 0, 0.482525,-0.00253583) , 
3, 0.636239, 1, 0, 0.5,0.00183604)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580155,0.00162611) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365659,-0.00560619) , 
4, 1.99733, 1, 0, 0.569848,0.0140239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459253,-0.000525293) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139708,-0.0276638) , 
5, 290.901, 1, 0, 0.454698,-0.0061045) , 
3, 0.909774, 1, 0, 0.5,0.00181442)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606197,0.00316384) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319735,-0.00775826) , 
1, 287.056, 1, 0, 0.597486,0.0313863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500246,9.29587e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281372,-0.0076544) , 
6, 88.9853, 1, 0, 0.489359,-0.00141948) , 
0, 0.485455, 1, 0, 0.5,0.00180891)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669338,0.0053598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557301,0.0014336) , 
0, 0.385945, 1, 0, 0.566112,0.0180632) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546279,0.00107341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430968,-0.00161425) , 
6, 24.8065, 1, 0, 0.476254,-0.0040663) , 
4, 0.75839, 1, 0, 0.5,0.00178172)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557341,0.00113017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449076,-0.000826833) , 
0, 1.11966, 1, 0, 0.494503,0.0005567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.0060027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0113502) , 
2, 9.0199, 1, 0, 0.858454,0.0799386) , 
2, 8.02985, 1, 0, 0.5,0.00175561)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529821,0.00145396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470275,-0.000644203) , 
1, 48.2628, 1, 0, 0.486463,-0.000329491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.772829,0.00350701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0111585) , 
2, 9.0199, 1, 0, 0.789118,0.0455043) , 
2, 7.04478, 1, 0, 0.5,0.00172056)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423444,-0.000918343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603044,0.0017258) , 
2, 4.04478, 1, 0, 0.537327,0.0086776) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534145,0.00108023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3874,-0.00260886) , 
5, 50.2799, 1, 0, 0.43242,-0.0109856) , 
4, 1.25302, 1, 0, 0.5,0.00168116)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507704,0.000988393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720967,0.00388011) , 
2, 5.03483, 1, 0, 0.592839,0.0231881) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585617,0.00176739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460778,-0.000765008) , 
5, 39.351, 1, 0, 0.482525,-0.0023486) , 
3, 0.636239, 1, 0, 0.5,0.00169679)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523412,0.000643941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.303242,-0.0110419) , 
4, 2.36593, 1, 0, 0.5193,0.00479802) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.341356,-0.00291311) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.217329,-0.0155783) , 
3, 2.65337, 1, 0, 0.331106,-0.0256961) , 
3, 1.83559, 1, 0, 0.5,0.00167073)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525359,0.000733544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.394263,-0.00246855) , 
0, 1.99013, 1, 0, 0.506147,0.00320423) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.2306,-0.00473813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.325747,-0.0111834) , 
2, 4.03483, 1, 0, 0.282468,-0.0528831) , 
1, 281.528, 1, 0, 0.5,0.00166292)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502372,0.000224626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255756,-0.00901931) , 
5, 232.851, 1, 0, 0.494503,0.000518096) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00568084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0109259) , 
2, 9.0199, 1, 0, 0.858454,0.0746298) , 
2, 8.02985, 1, 0, 0.5,0.00163741)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575266,0.00193533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28008,-0.0109044) , 
6, 131.769, 1, 0, 0.569315,0.018139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559048,0.00166153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455691,-0.00105879) , 
6, 18.884, 1, 0, 0.47944,-0.00329236) , 
4, 0.717171, 1, 0, 0.5,0.00161037)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673243,0.00502356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578565,0.00210826) , 
4, 0.638495, 1, 0, 0.597486,0.0287648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58946,0.00233739) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475674,-0.000532257) , 
3, 0.594156, 1, 0, 0.489359,-0.00138334) , 
0, 0.485455, 1, 0, 0.5,0.00158352)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570847,0.00176099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41124,-0.00206571) , 
6, 49.8121, 1, 0, 0.540036,0.0116452) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546791,0.000920096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434698,-0.00152301) , 
0, 0.908207, 1, 0, 0.468857,-0.0063142) , 
1, 72.3937, 1, 0, 0.5,0.00154353)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479339,4.71962e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348599,-0.00423645) , 
0, 2.20198, 1, 0, 0.470484,-0.00172425) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.753807,0.00377452) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647794,-0.000182815) , 
5, 83.5161, 1, 0, 0.714236,0.0251517) , 
2, 6.01493, 1, 0, 0.5,0.00153016)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.448544,-0.000448803) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.629873,0.00190049) , 
2, 4.04478, 1, 0, 0.569848,0.0123244) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50487,0.00086569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42821,-0.00150241) , 
1, 56.3064, 1, 0, 0.454698,-0.0054946) , 
3, 0.909774, 1, 0, 0.5,0.00151573)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504534,0.00024281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286115,-0.00647679) , 
6, 92.2763, 1, 0, 0.494503,0.000441373) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00542544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0106642) , 
2, 9.0199, 1, 0, 0.858454,0.0709229) , 
2, 8.02985, 1, 0, 0.5,0.00150586)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58923,0.00190748) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495384,-0.000294466) , 
1, 96.5245, 1, 0, 0.551862,0.0109392) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542728,0.00147301) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430695,-0.00151031) , 
6, 18.884, 1, 0, 0.457322,-0.00629764) , 
4, 0.985093, 1, 0, 0.5,0.00148359)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538205,0.000794855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365654,-0.00464567) , 
4, 1.95374, 1, 0, 0.527389,0.0051809) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369357,-0.00177322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246418,-0.0101816) , 
3, 2.46589, 1, 0, 0.356594,-0.0179671) , 
3, 1.64622, 1, 0, 0.5,0.00146887)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602653,0.00247496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329182,-0.00672855) , 
1, 275.088, 1, 0, 0.593327,0.0238435) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587173,0.00217135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473214,-0.000542367) , 
3, 0.594156, 1, 0, 0.486839,-0.00168278) , 
0, 0.547632, 1, 0, 0.5,0.00147206)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491102,7.39349e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.210941,-0.0133353) , 
5, 281.226, 1, 0, 0.486463,-0.000352445) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858934,0.00661623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739718,0.00198154) , 
0, 1.04495, 1, 0, 0.789118,0.0396955) , 
2, 7.04478, 1, 0, 0.5,0.00143882)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511166,0.0004031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762788,0.00317955) , 
2, 6.01493, 1, 0, 0.542303,0.00767526) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527181,0.00191609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412298,-0.00161626) , 
6, 14.4354, 1, 0, 0.426338,-0.00946316) , 
0, 1.51759, 1, 0, 0.5,0.00142335)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565509,0.00184508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380228,-0.00255046) , 
6, 63.0824, 1, 0, 0.544741,0.0148051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539768,0.000416023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402578,-0.00179507) , 
3, 1.14123, 1, 0, 0.483122,-0.00363292) , 
1, 48.2628, 1, 0, 0.5,0.00141738)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575266,0.00174141) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28008,-0.00965887) , 
6, 131.769, 1, 0, 0.569315,0.0162721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50613,0.000137785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.321585,-0.00435316) , 
5, 135.057, 1, 0, 0.47944,-0.00300626) , 
4, 0.717171, 1, 0, 0.5,0.00140394)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596258,0.00267038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486145,-0.000201315) , 
0, 0.423278, 1, 0, 0.494503,0.000407327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.0050953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0103488) , 
2, 9.0199, 1, 0, 0.858454,0.0663336) , 
2, 8.02985, 1, 0, 0.5,0.00140301)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520073,0.000580292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.333775,-0.00461484) , 
1, 225.222, 1, 0, 0.509271,0.00350573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454257,0.00129459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35598,-0.00477085) , 
4, 0.720492, 1, 0, 0.371687,-0.0282686) , 
0, 2.20153, 1, 0, 0.5,0.00136467)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587643,0.00161148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320777,-0.00887418) , 
4, 2.25653, 1, 0, 0.581838,0.0149582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579998,0.00164853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449792,-0.000868299) , 
5, 39.351, 1, 0, 0.472684,-0.00319499) , 
3, 0.741445, 1, 0, 0.5,0.00134795)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502822,0.000195095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276522,-0.00670236) , 
6, 98.8584, 1, 0, 0.494503,0.000370414) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00494367) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.0101652) , 
2, 9.0199, 1, 0, 0.858454,0.0641001) , 
2, 8.02985, 1, 0, 0.5,0.00133293)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500972,0.00236304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393694,-0.00126603) , 
0, 0.414001, 1, 0, 0.40139,-0.00793283) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58351,0.00112981) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407632,-0.00460273) , 
1, 193.048, 1, 0, 0.569277,0.00780697) , 
2, 4.04478, 1, 0, 0.5,0.00131209)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517503,0.000479191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299401,-0.00986978) , 
4, 2.38653, 1, 0, 0.513556,0.00336491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.305588,-0.00509346) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.355323,0.00803675) , 
4, 2.35301, 1, 0, 0.308849,-0.0275202) , 
3, 2.00392, 1, 0, 0.5,0.00131963)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60467,0.00240261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494936,0.000378533) , 
5, 59.0447, 1, 0, 0.544741,0.0137726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494837,-8.14856e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353059,-0.00439644) , 
0, 2.15167, 1, 0, 0.483122,-0.00339138) , 
1, 48.2628, 1, 0, 0.5,0.00130995)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613781,0.00198687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437634,-0.000262031) , 
3, 1.35672, 1, 0, 0.569315,0.0151439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553579,0.00114351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445713,-0.00108494) , 
6, 21.8452, 1, 0, 0.47944,-0.00282311) , 
4, 0.717171, 1, 0, 0.5,0.00128709)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828401,0.0150742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617261,0.00322202) , 
3, 0.38301, 1, 0, 0.620788,0.0368204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588386,0.0019285) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480696,-0.000361494) , 
0, 0.562999, 1, 0, 0.494659,-0.000298362) , 
3, 0.48895, 1, 0, 0.5,0.00127356)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498534,0.000131639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241959,-0.0110984) , 
1, 329.789, 1, 0, 0.494503,0.00031504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00476048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.00995091) , 
2, 9.0199, 1, 0, 0.858454,0.0614714) , 
2, 8.02985, 1, 0, 0.5,0.00123869)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455588,-0.000265529) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64806,0.0022788) , 
2, 4.0398, 1, 0, 0.587857,0.0160956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510383,0.000188716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34883,-0.00278924) , 
6, 52.7837, 1, 0, 0.478619,-0.00240546) , 
3, 0.678321, 1, 0, 0.5,0.00121574)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439642,-0.000460386) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623513,0.00145771) , 
2, 4.04478, 1, 0, 0.54854,0.00752289) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511717,0.000814267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403926,-0.00161276) , 
3, 0.80847, 1, 0, 0.433969,-0.00735697) , 
0, 1.39324, 1, 0, 0.5,0.00121879)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560871,0.00158031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35823,-0.00327014) , 
6, 71.0445, 1, 0, 0.544741,0.0130585) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542066,0.000516718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427138,-0.00131146) , 
0, 1.23151, 1, 0, 0.483122,-0.00323724) , 
1, 48.2628, 1, 0, 0.5,0.00122628)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433979,-0.000416513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.618656,0.00163736) , 
2, 4.04478, 1, 0, 0.554848,0.0100583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554983,0.00195008) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446882,-0.00104379) , 
6, 15.9227, 1, 0, 0.46326,-0.00471534) , 
4, 0.923265, 1, 0, 0.5,0.00121103)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499112,0.00013097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.219545,-0.0115071) , 
5, 281.226, 1, 0, 0.494503,0.000320745) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.887467,0.0074475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748308,0.00190698) , 
0, 1.73424, 1, 0, 0.858454,0.0589137) , 
2, 8.02985, 1, 0, 0.5,0.00120568)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.683466,0.00486136) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581739,0.00181689) , 
4, 0.634032, 1, 0, 0.60176,0.0256847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59095,0.00180467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.478011,-0.000380511) , 
3, 0.594156, 1, 0, 0.491627,-0.000829983) , 
0, 0.423278, 1, 0, 0.5,0.00118581)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569353,0.00118686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.443901,-0.0010695) , 
6, 37.3764, 1, 0, 0.526906,0.00505956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492646,0.00150628) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397047,-0.00209593) , 
4, 0.641838, 1, 0, 0.413158,-0.0114458) , 
1, 128.699, 1, 0, 0.5,0.00115532)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570533,0.00249666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480856,-0.000225809) , 
4, 0.511076, 1, 0, 0.486463,-0.000354717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.799456,0.00373473) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564713,-0.00629601) , 
3, 1.58086, 1, 0, 0.789118,0.0334025) , 
2, 7.04478, 1, 0, 0.5,0.00115517)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630107,0.00352521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.503795,0.000149826) , 
3, 0.48895, 1, 0, 0.509271,0.00298768) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492663,0.00159478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352379,-0.0041913) , 
6, 14.3743, 1, 0, 0.371687,-0.024585) , 
0, 2.20153, 1, 0, 0.5,0.00112975)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532293,0.000641867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.264457,-0.00879859) , 
3, 2.19329, 1, 0, 0.524047,0.00453685) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.405901,-0.00133073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262152,-0.0174489) , 
0, 2.40105, 1, 0, 0.403434,-0.0126697) , 
4, 1.54155, 1, 0, 0.5,0.0011063)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592641,0.00193976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47457,-1.8261e-05) , 
5, 73.6858, 1, 0, 0.544741,0.0122262) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539768,0.000334985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402578,-0.00149518) , 
3, 1.14123, 1, 0, 0.483122,-0.00308195) , 
1, 48.2628, 1, 0, 0.5,0.00111105)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500664,0.000147029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.277916,-0.00679498) , 
1, 281.528, 1, 0, 0.494503,0.000264767) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00429535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.00954171) , 
2, 9.0199, 1, 0, 0.858454,0.0556408) , 
2, 8.02985, 1, 0, 0.5,0.00110111)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601825,0.00223012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589556,0.0190949) , 
4, 2.37127, 1, 0, 0.60176,0.0243272) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556643,0.000591975) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430094,-0.000880849) , 
5, 68.376, 1, 0, 0.491627,-0.000830711) , 
0, 0.423278, 1, 0, 0.5,0.00108194)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.42774,-0.000748999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.611443,0.00141753) , 
2, 4.04478, 1, 0, 0.546172,0.00727331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535794,0.00134511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42024,-0.00144196) , 
6, 18.884, 1, 0, 0.448007,-0.0059269) , 
4, 1.08814, 1, 0, 0.5,0.00106455)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408948,-0.000724337) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577616,0.000803915) , 
2, 4.04478, 1, 0, 0.508263,0.00235832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.395927,0.00324438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256623,-0.00851341) , 
4, 0.601117, 1, 0, 0.283008,-0.0325941) , 
6, 98.8584, 1, 0, 0.5,0.00107613)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.622761,0.00325856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.525704,0.000308227) , 
4, 0.506232, 1, 0, 0.532133,0.00507703) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423509,-0.000766697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.309493,-0.00593245) , 
4, 2.06321, 1, 0, 0.412194,-0.00980933) , 
0, 1.71655, 1, 0, 0.5,0.00108879)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502372,0.000150743) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255756,-0.00659442) , 
5, 232.851, 1, 0, 0.494503,0.00027291) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828376,0.00413071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.920366,0.00934162) , 
2, 9.0199, 1, 0, 0.858454,0.0533846) , 
2, 8.02985, 1, 0, 0.5,0.00107506)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570847,0.00131993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41124,-0.00172525) , 
6, 49.8121, 1, 0, 0.540036,0.00836491) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546791,0.000712048) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434698,-0.00114038) , 
0, 0.908207, 1, 0, 0.468857,-0.00462308) , 
1, 72.3937, 1, 0, 0.5,0.00105954)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.828401,0.0144636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617261,0.00275154) , 
3, 0.38301, 1, 0, 0.620788,0.0314678) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569948,0.0015083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.480253,-0.000353534) , 
4, 0.637029, 1, 0, 0.494659,-0.00029101) , 
3, 0.48895, 1, 0, 0.5,0.00105392)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488962,2.27398e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184553,-0.015932) , 
5, 339.276, 1, 0, 0.486463,-0.000341279) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858934,0.00572369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739718,0.00126633) , 
0, 1.04495, 1, 0, 0.789118,0.0301995) , 
2, 7.04478, 1, 0, 0.5,0.00102475)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
