// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : mdjordje
Date           : Tue Feb 23 09:47:14 2016
Host           : Linux vocms0301.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/m/mdjordje/CMSSW_7_6_3/src/CMGTools/TTHAnalysis/macros/finalMVA/2lss
Training events: 122907
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "0.0813623.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]])) max_Lep_eta                                                    max_Lep_eta                                                    max_Lep_eta                                                                                                                       'F'    [0.005187259987,2.49993348122]
nJet25_Recl                   numJets_float                 numJets_float                 numJets_float                                                   'F'    [4,15]
mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                                                  'F'    [0.264623969793,4.24731683731]
mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                                                  'F'    [0.266556233168,4.55896615982]
min(met_pt,400)               met                           met                           met                                                             'F'    [0.205991342664,400]
avg_dr_jet                    avg_dr_jet                    avg_dr_jet                    avg_dr_jet                                                      'F'    [0.697745859623,3.89711785316]
MT_met_lep1                   MT_met_lep1                   MT_met_lep1                   MT_met_lep1                                                     'F'    [8.61581211211e-05,1128.38647461]
NSpec 3
iF_Recl[0]                    iF0                           iF0                           F                                                               'F'    [0,3]
iF_Recl[1]                    iF1                           iF1                           F                                                               'F'    [0,4]
iF_Recl[2]                    iF2                           iF2                           F                                                               'F'    [0,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]]))", "nJet25_Recl", "mindr_lep1_jet", "mindr_lep2_jet", "min(met_pt,400)", "avg_dr_jet", "MT_met_lep1" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473778,-0.0039757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672335,0.0251921) , 
1, 4.05473, 1, 0, 0.590967,0.090967) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321525,-0.0278762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.516551,0.00249416) , 
1, 5.04478, 1, 0, 0.372585,-0.127415) , 
0, 1.51941, 1, 0, 0.5,-4.43286e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473778,-0.00367437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672335,0.023366) , 
1, 4.05473, 1, 0, 0.590967,0.0843489) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.278471,-0.0326237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449998,-0.00662329) , 
1, 4.04975, 1, 0, 0.372585,-0.117455) , 
0, 1.51941, 1, 0, 0.5,0.00028745)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.556059,0.00652925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770124,0.036155) , 
6, 111.448, 1, 0, 0.603427,0.090583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349911,-0.0212242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557933,0.0102882) , 
6, 106.663, 1, 0, 0.390684,-0.0946592) , 
0, 1.37047, 1, 0, 0.5,0.000526073)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5209,0.00163823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730589,0.0294592) , 
1, 5.0398, 1, 0, 0.583754,0.06854) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309821,-0.0257239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47553,-0.000134682) , 
4, 87.7231, 1, 0, 0.364295,-0.108906) , 
0, 1.59388, 1, 0, 0.5,0.000819649)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39137,-0.0147863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617843,0.0150156) , 
1, 5.04478, 1, 0, 0.454874,-0.0398951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749163,0.031001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527212,0.00665282) , 
0, 1.66835, 1, 0, 0.686347,0.170059) , 
6, 112.277, 1, 0, 0.5,0.0010354)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326286,-0.0230857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524016,0.00221643) , 
1, 4.05473, 1, 0, 0.434543,-0.0580983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.706713,0.0254435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.491008,0.001944) , 
0, 1.48579, 1, 0, 0.622266,0.112191) , 
4, 89.7121, 1, 0, 0.5,0.0012796)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547768,0.00428343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.734397,0.0272358) , 
4, 101.651, 1, 0, 0.604599,0.0771648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350597,-0.0178388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550638,0.0091445) , 
4, 111.591, 1, 0, 0.392376,-0.0764482) , 
0, 1.35806, 1, 0, 0.5,0.0014534)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334026,-0.020153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540721,0.00454365) , 
1, 4.04975, 1, 0, 0.451174,-0.0380682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736146,0.0264453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514659,0.00535223) , 
0, 1.66835, 1, 0, 0.672261,0.141552) , 
6, 106.663, 1, 0, 0.5,0.00160027)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50638,0.000489721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.716618,0.0232987) , 
1, 5.0398, 1, 0, 0.568787,0.049145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.310211,-0.0215257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507998,0.00405416) , 
6, 106.481, 1, 0, 0.346804,-0.103789) , 
0, 1.73041, 1, 0, 0.5,0.00175468)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.362451,-0.0160385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.590163,0.00894162) , 
1, 5.0398, 1, 0, 0.421019,-0.0599269) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668257,0.0180508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444638,-0.00265557) , 
0, 1.66844, 1, 0, 0.597398,0.0780349) , 
4, 75.7889, 1, 0, 0.5,0.00185139)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337645,-0.0172292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544277,0.00434369) , 
1, 4.04975, 1, 0, 0.454874,-0.0305037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.78511,0.0287594) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59784,0.0116124) , 
0, 1.1844, 1, 0, 0.686347,0.13592) , 
6, 112.277, 1, 0, 0.5,0.00194056)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568268,0.0061463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367053,-0.0137232) , 
0, 1.23394, 1, 0, 0.452697,-0.032344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.708123,0.0220014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468907,-0.000799121) , 
0, 1.90628, 1, 0, 0.663973,0.121216) , 
4, 113.58, 1, 0, 0.5,0.00203689)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387848,-0.0110693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614225,0.0109128) , 
1, 5.04478, 1, 0, 0.451174,-0.0300444) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77459,0.0256446) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58556,0.00968723) , 
0, 1.17199, 1, 0, 0.672261,0.115473) , 
6, 106.663, 1, 0, 0.5,0.00209278)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.586483,0.0115434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391098,-0.0123394) , 
3, 1.50516, 1, 0, 0.539904,0.0393689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342408,-0.0208016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.558997,0.00227348) , 
4, 97.6682, 1, 0, 0.398785,-0.0921966) , 
5, 2.36906, 1, 0, 0.5,0.0021662)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.643789,0.0139393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475955,-0.00850297) , 
5, 2.47538, 1, 0, 0.614377,0.0663314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333135,-0.0163027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.495201,0.00150435) , 
4, 71.8109, 1, 0, 0.407612,-0.049675) , 
0, 1.24635, 1, 0, 0.5,0.0021596)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337645,-0.0147852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609622,0.00951333) , 
6, 112.277, 1, 0, 0.387809,-0.0624393) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.637211,0.0147814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500478,-0.0035438) , 
5, 2.26702, 1, 0, 0.583636,0.0503151) , 
1, 4.05473, 1, 0, 0.5,0.0021586)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618578,0.013562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444105,-0.0054233) , 
3, 1.37703, 1, 0, 0.572831,0.056932) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388562,-0.0123689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.603838,0.00913552) , 
4, 119.552, 1, 0, 0.4277,-0.052195) , 
2, 1.0572, 1, 0, 0.5,0.0021688)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514584,0.000958946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.713009,0.0186446) , 
4, 107.613, 1, 0, 0.567329,0.0375654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381956,-0.00777584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231162,-0.0292705) , 
3, 1.74007, 1, 0, 0.345444,-0.0791192) , 
0, 1.74282, 1, 0, 0.5,0.00215833)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387848,-0.00938169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.614225,0.0092607) , 
1, 5.04478, 1, 0, 0.451174,-0.0251415) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.696943,0.0169658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.428616,-0.00711943) , 
0, 2.12749, 1, 0, 0.672261,0.0984934) , 
6, 106.663, 1, 0, 0.5,0.00216289)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594222,0.0110941) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.390919,-0.00998747) , 
3, 1.54787, 1, 0, 0.548869,0.0422699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.351916,-0.0163497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550282,0.00149804) , 
4, 83.745, 1, 0, 0.42144,-0.0622383) , 
5, 2.27356, 1, 0, 0.5,0.00219079)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507305,0.00138998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702424,0.0157074) , 
1, 4.05473, 1, 0, 0.624606,0.0651056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471346,0.000256378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351014,-0.0151444) , 
5, 2.27356, 1, 0, 0.42365,-0.0364203) , 
0, 1.12224, 1, 0, 0.5,0.00215297)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517042,0.00323571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710782,0.0187749) , 
4, 103.635, 1, 0, 0.572831,0.0503124) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345739,-0.0150824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510958,0.000146951) , 
4, 67.838, 1, 0, 0.4277,-0.045777) , 
2, 1.0572, 1, 0, 0.5,0.00209188)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588138,0.00920078) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4193,-0.00941213) , 
5, 2.42731, 1, 0, 0.550112,0.0327051) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349215,-0.0147172) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.609888,0.00990418) , 
4, 133.513, 1, 0, 0.38597,-0.0676126) , 
3, 1.37703, 1, 0, 0.5,0.00207832)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.400008,-0.00755653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.670457,0.0133062) , 
6, 123.505, 1, 0, 0.439994,-0.026674) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68897,0.0146431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.431679,-0.00664916) , 
0, 2.01651, 1, 0, 0.650908,0.0742669) , 
1, 5.0398, 1, 0, 0.5,0.00204401)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60146,0.00849475) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.44361,-0.0083685) , 
5, 2.43273, 1, 0, 0.567329,0.0313626) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.37794,-0.00688101) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222103,-0.026368) , 
3, 1.82549, 1, 0, 0.345444,-0.0652081) , 
0, 1.74282, 1, 0, 0.5,0.00205898)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421222,-0.00601498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.668333,0.0148503) , 
1, 6.0398, 1, 0, 0.451174,-0.0209788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.738292,0.0195451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61734,0.00699056) , 
2, 0.885993, 1, 0, 0.672261,0.0830957) , 
6, 106.663, 1, 0, 0.5,0.00200575)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35942,-0.0102631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.62206,0.0124553) , 
4, 139.479, 1, 0, 0.387809,-0.0466985) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647407,0.0130712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.520767,-0.00103343) , 
5, 2.1828, 1, 0, 0.583636,0.0383205) , 
1, 4.05473, 1, 0, 0.5,0.00200957)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.648583,0.0110389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468338,-0.00677636) , 
5, 2.53596, 1, 0, 0.624606,0.0554248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486517,0.00268443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377494,-0.0106705) , 
5, 2.1303, 1, 0, 0.42365,-0.0307998) , 
0, 1.12224, 1, 0, 0.5,0.00195997)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596668,0.00870188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358325,-0.0121143) , 
3, 1.76143, 1, 0, 0.57051,0.041518) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399037,-0.00880144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644067,0.0115289) , 
4, 145.409, 1, 0, 0.42543,-0.0400285) , 
2, 1.07701, 1, 0, 0.5,0.00188577)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471401,-0.00133409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304974,-0.0163614) , 
3, 1.33407, 1, 0, 0.414818,-0.0379519) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621162,0.00907544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378552,-0.00834615) , 
0, 2.04074, 1, 0, 0.58611,0.0420834) , 
4, 69.8219, 1, 0, 0.5,0.00184896)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418549,-0.00573326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669047,0.0133793) , 
1, 6.0398, 1, 0, 0.448859,-0.0204595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67761,0.0124363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408166,-0.00694326) , 
0, 2.12761, 1, 0, 0.652183,0.0681566) , 
6, 101.05, 1, 0, 0.5,0.00182952)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.68426,0.0141447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570467,0.00301429) , 
5, 2.23304, 1, 0, 0.63751,0.060637) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337331,-0.0109403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527099,0.0018074) , 
1, 4.04975, 1, 0, 0.443605,-0.0222921) , 
0, 0.948474, 1, 0, 0.5,0.00182697)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634837,0.0119951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505814,-6.9575e-05) , 
5, 2.27426, 1, 0, 0.588196,0.048028) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366623,-0.0100546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540044,0.00201843) , 
4, 73.805, 1, 0, 0.444171,-0.027516) , 
2, 0.918499, 1, 0, 0.5,0.00176735)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577474,0.00647533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381555,-0.00829957) , 
3, 1.52652, 1, 0, 0.532932,0.0203061) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.350885,-0.0133476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.635761,0.00915701) , 
4, 145.405, 1, 0, 0.378802,-0.0666629) , 
5, 2.44865, 1, 0, 0.5,0.00172374)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525699,0.0042501) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411706,-0.00754221) , 
5, 2.14172, 1, 0, 0.463076,-0.0132778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.715874,0.0143711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393755,-0.0207641) , 
2, 2.1056, 1, 0, 0.705592,0.0849341) , 
6, 123.505, 1, 0, 0.5,0.00167549)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436537,-0.00326994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638974,0.00819523) , 
1, 4.05473, 1, 0, 0.554656,0.0216909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.353978,-0.00767322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166765,-0.0313361) , 
3, 2.20989, 1, 0, 0.333615,-0.0593474) , 
0, 1.85453, 1, 0, 0.5,0.00165273)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425661,-0.00472798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665345,0.0123711) , 
1, 6.02488, 1, 0, 0.452697,-0.0166277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726294,0.015472) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594185,0.00455849) , 
2, 1.03758, 1, 0, 0.663973,0.0648603) , 
4, 113.58, 1, 0, 0.5,0.00161675)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600762,0.00628757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.824771,0.0205832) , 
6, 127.369, 1, 0, 0.63751,0.0530682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508094,0.00338451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.399399,-0.00779167) , 
5, 2.11438, 1, 0, 0.443605,-0.0195113) , 
0, 0.948474, 1, 0, 0.5,0.00159764)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493594,0.000950233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68738,0.011724) , 
1, 5.0398, 1, 0, 0.561662,0.0293503) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390391,-0.0078702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.640131,0.00929508) , 
4, 145.409, 1, 0, 0.417354,-0.0357324) , 
2, 1.15627, 1, 0, 0.5,0.00154094)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423265,-0.00334875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625469,0.00686477) , 
1, 4.05473, 1, 0, 0.540704,0.0163155) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337218,-0.00878926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.151337,-0.0318546) , 
3, 2.20989, 1, 0, 0.314706,-0.0659169) , 
0, 1.99105, 1, 0, 0.5,0.00150476)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512294,0.00308398) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396422,-0.00775259) , 
5, 2.14172, 1, 0, 0.448859,-0.0167676) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.680898,0.0112404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524197,-0.00131446) , 
5, 2.48802, 1, 0, 0.652183,0.0557194) , 
6, 101.05, 1, 0, 0.5,0.00146457)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582225,0.00579625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4016,-0.00758293) , 
5, 2.488, 1, 0, 0.550112,0.0214471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339301,-0.01056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591957,0.00469502) , 
6, 108.009, 1, 0, 0.38597,-0.0440748) , 
3, 1.37703, 1, 0, 0.5,0.00144341)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484049,0.00146546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.364989,-0.00931453) , 
5, 2.1303, 1, 0, 0.412676,-0.0292765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634272,0.00848853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.490726,-0.00142284) , 
2, 1.23462, 1, 0, 0.582448,0.0303965) , 
4, 67.8328, 1, 0, 0.5,0.00141695)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658695,0.00895782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.476415,-0.00370507) , 
5, 2.53596, 1, 0, 0.634745,0.0448145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412442,-0.004861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64634,0.0104975) , 
1, 6.0398, 1, 0, 0.439806,-0.0180185) , 
0, 0.985709, 1, 0, 0.5,0.00138322)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491186,-5.95191e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263063,-0.0177442) , 
3, 1.91091, 1, 0, 0.46824,-0.0100947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728117,0.013669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453371,-0.00284832) , 
0, 2.0671, 1, 0, 0.698342,0.0727494) , 
4, 139.438, 1, 0, 0.5,0.00134006)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46989,0.000962224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662943,0.0102066) , 
1, 4.05473, 1, 0, 0.600219,0.0441631) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.371631,-0.00766207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54071,0.00161765) , 
4, 67.8328, 1, 0, 0.456183,-0.0174126) , 
2, 0.819427, 1, 0, 0.5,0.00131911)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593807,0.00624831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474247,-0.00258967) , 
5, 2.20989, 1, 0, 0.539487,0.0137344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.335402,-0.00787249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.150969,-0.0284458) , 
3, 2.20989, 1, 0, 0.312842,-0.0576981) , 
0, 2.00347, 1, 0, 0.5,0.00128922)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436668,-0.00331789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681008,0.0106935) , 
1, 6.0398, 1, 0, 0.466452,-0.00945331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724134,0.0122723) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39241,-0.019024) , 
2, 2.1056, 1, 0, 0.713487,0.0692667) , 
6, 129.119, 1, 0, 0.5,0.00123699)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662941,0.00853221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479788,-0.00294955) , 
5, 2.53596, 1, 0, 0.63904,0.0427687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54299,0.00404314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.40407,-0.00540709) , 
2, 0.839241, 1, 0, 0.446375,-0.0147801) , 
0, 0.923651, 1, 0, 0.5,0.00123764)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.516656,0.00328786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.405831,-0.00589982) , 
5, 2.09428, 1, 0, 0.448859,-0.0135192) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.668554,0.00859688) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466349,-0.00696428) , 
2, 1.75714, 1, 0, 0.652183,0.0449819) , 
6, 101.05, 1, 0, 0.5,0.00119521)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415563,-0.00390746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669947,0.0104743) , 
4, 151.372, 1, 0, 0.439994,-0.0147361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632774,0.00477812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741106,0.0168043) , 
1, 7.02985, 1, 0, 0.650908,0.0412059) , 
1, 5.0398, 1, 0, 0.5,0.00117963)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596019,0.00566424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434103,-0.00410694) , 
5, 2.38179, 1, 0, 0.553282,0.0190247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360494,-0.00780683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620182,0.00578097) , 
4, 133.513, 1, 0, 0.397509,-0.0332184) , 
3, 1.31296, 1, 0, 0.5,0.00115499)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570282,0.00249644) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802288,0.0142688) , 
6, 132.676, 1, 0, 0.603427,0.0245896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454893,0.00144757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347896,-0.00780102) , 
5, 2.11438, 1, 0, 0.390684,-0.0236647) , 
0, 1.37047, 1, 0, 0.5,0.00113037)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348068,-0.00654089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588438,0.00483605) , 
4, 119.592, 1, 0, 0.387809,-0.0262955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.624565,0.00605844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470226,-0.0033983) , 
5, 2.37931, 1, 0, 0.583636,0.021524) , 
1, 4.05473, 1, 0, 0.5,0.00110068)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.63276,0.00753188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493535,-0.000654869) , 
2, 0.805593, 1, 0, 0.53588,0.0110546) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.319296,-0.0074224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203198,-0.0262005) , 
0, 2.40169, 1, 0, 0.307463,-0.0524595) , 
0, 2.0407, 1, 0, 0.5,0.00107767)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487588,0.00355281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42631,-0.00531516) , 
6, 43.7374, 1, 0, 0.448859,-0.0119417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519329,-0.00168238) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683346,0.0084899) , 
4, 58.941, 1, 0, 0.652183,0.0396645) , 
6, 101.05, 1, 0, 0.5,0.00103847)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573207,0.00395767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395011,-0.00605299) , 
5, 2.48188, 1, 0, 0.540075,0.0129063) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376045,-0.00561169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181931,-0.025646) , 
3, 2.55157, 1, 0, 0.358656,-0.0408525) , 
3, 1.54787, 1, 0, 0.5,0.00103105)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544811,0.00407034) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434388,-0.00399632) , 
5, 2.05071, 1, 0, 0.471802,-0.00724448) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744172,0.01221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489465,0.000399411) , 
0, 1.94259, 1, 0, 0.700041,0.0594394) , 
1, 6.02488, 1, 0, 0.5,0.000994015)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574609,0.00400879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344043,-0.00810548) , 
3, 1.76143, 1, 0, 0.548191,0.0163125) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491769,0.00311258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380264,-0.00734044) , 
5, 1.90242, 1, 0, 0.403242,-0.0298708) , 
2, 1.29497, 1, 0, 0.5,0.00095787)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54322,0.00529364) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387745,-0.00548329) , 
2, 0.63688, 1, 0, 0.409309,-0.0227579) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517826,0.00111107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.71533,0.00910702) , 
6, 112.277, 1, 0, 0.574126,0.0202926) , 
4, 63.8548, 1, 0, 0.5,0.000930754)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546598,0.00201143) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.704944,0.00872292) , 
4, 63.8601, 1, 0, 0.63904,0.0348773) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418589,-0.0034017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653657,0.00759438) , 
1, 6.0398, 1, 0, 0.446375,-0.0121551) , 
0, 0.923651, 1, 0, 0.5,0.00093558)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497244,0.000128792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269912,-0.0130137) , 
3, 1.91091, 1, 0, 0.474472,-0.00614611) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.717957,0.0105579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243801,-0.0303648) , 
0, 2.40084, 1, 0, 0.713385,0.0599031) , 
4, 153.361, 1, 0, 0.5,0.000911211)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525446,0.00212138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338566,-0.00617616) , 
0, 0.936063, 1, 0, 0.387809,-0.022171) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.659173,0.00802509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541274,0.000226268) , 
5, 2.08454, 1, 0, 0.583636,0.0180887) , 
1, 4.05473, 1, 0, 0.5,0.000894086)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.47352,-0.000772776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656752,0.00646349) , 
6, 95.4358, 1, 0, 0.527495,0.00808723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309549,-0.00744541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203521,-0.0235805) , 
0, 2.40176, 1, 0, 0.295232,-0.0529348) , 
0, 2.12758, 1, 0, 0.5,0.000863597)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548182,0.00256697) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.294988,-0.01045) , 
3, 1.99633, 1, 0, 0.527385,0.009573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336101,-0.00892187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625854,0.00523615) , 
4, 145.405, 1, 0, 0.363648,-0.0425859) , 
5, 2.51232, 1, 0, 0.5,0.000849502)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551077,0.00286031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.34491,-0.0106335) , 
5, 2.71675, 1, 0, 0.538362,0.0121672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486579,0.00287438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365634,-0.00780446) , 
5, 1.88717, 1, 0, 0.391174,-0.0313634) , 
2, 1.41386, 1, 0, 0.5,0.000821762)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415563,-0.00291214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669947,0.00779021) , 
4, 151.372, 1, 0, 0.439994,-0.010831) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632774,0.00337218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741106,0.0137388) , 
1, 7.02985, 1, 0, 0.650908,0.0300175) , 
1, 5.0398, 1, 0, 0.5,0.000790558)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489123,0.00375645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456647,-0.00320496) , 
6, 41.753, 1, 0, 0.466452,-0.00638365) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724134,0.00880716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39241,-0.0170927) , 
2, 2.1056, 1, 0, 0.713487,0.0463448) , 
6, 129.119, 1, 0, 0.5,0.000776953)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520668,4.02978e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.68328,0.00615662) , 
4, 63.8601, 1, 0, 0.614377,0.0207133) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477011,0.0025131) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375399,-0.00512589) , 
5, 2.05071, 1, 0, 0.407612,-0.0153481) , 
0, 1.24635, 1, 0, 0.5,0.000765046)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.611122,0.00537632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235671,-0.0178087) , 
3, 2.33341, 1, 0, 0.602255,0.0287902) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616037,0.0055699) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429211,-0.00323938) , 
0, 0.687829, 1, 0, 0.458645,-0.010601) , 
2, 0.799613, 1, 0, 0.5,0.000742304)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56587,0.00346374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215216,-0.0188481) , 
3, 2.42344, 1, 0, 0.554083,0.0166756) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.421156,-0.00397634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.701477,0.0115966) , 
1, 7.00995, 1, 0, 0.436356,-0.0180629) , 
5, 2.20989, 1, 0, 0.5,0.000716962)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480549,0.00260456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416924,-0.00582197) , 
6, 52.2285, 1, 0, 0.447284,-0.0102628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651567,0.00568636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370456,-0.0068166) , 
0, 2.18966, 1, 0, 0.630355,0.0277578) , 
6, 95.4358, 1, 0, 0.5,0.000685435)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.349311,-0.00479383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591427,0.00375501) , 
4, 121.58, 1, 0, 0.387809,-0.0188997) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626765,0.00400565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379753,-0.00421812) , 
0, 1.97836, 1, 0, 0.583636,0.0152808) , 
1, 4.05473, 1, 0, 0.5,0.000682577)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573988,0.00318249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361849,-0.00769599) , 
5, 2.63971, 1, 0, 0.555113,0.0133441) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367735,-0.00519328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626825,0.00413735) , 
4, 133.513, 1, 0, 0.404931,-0.0211739) , 
3, 1.27025, 1, 0, 0.5,0.000676942)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54322,0.00457849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.387745,-0.00432002) , 
2, 0.63688, 1, 0, 0.409309,-0.0172795) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552455,0.00155156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.736667,0.0107079) , 
4, 180.921, 1, 0, 0.574126,0.0153315) , 
4, 63.8548, 1, 0, 0.5,0.000664844)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577345,0.00311053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385251,-0.00403919) , 
3, 1.52652, 1, 0, 0.538362,0.0101739) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486579,0.00250727) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365634,-0.00665876) , 
5, 1.88717, 1, 0, 0.391174,-0.0263306) , 
2, 1.41386, 1, 0, 0.5,0.000659697)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581877,0.00349581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462657,-0.00180599) , 
5, 2.20989, 1, 0, 0.527495,0.00636922) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309549,-0.00578025) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203521,-0.0209635) , 
0, 2.40176, 1, 0, 0.295232,-0.0419821) , 
0, 2.12758, 1, 0, 0.5,0.000645509)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433171,-0.00206192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.689967,0.00565806) , 
6, 123.505, 1, 0, 0.471802,-0.00518327) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.67428,0.00443012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741106,0.0119237) , 
1, 7.0398, 1, 0, 0.700041,0.0417408) , 
1, 6.02488, 1, 0, 0.5,0.000613997)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.674679,0.0069072) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473697,-0.00175768) , 
5, 2.5705, 1, 0, 0.652752,0.0344894) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54096,0.00176813) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397047,-0.00401326) , 
2, 1.07701, 1, 0, 0.469304,-0.00618849) , 
0, 0.687829, 1, 0, 0.5,0.000618083)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480549,0.00254119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416924,-0.00527952) , 
6, 52.2285, 1, 0, 0.447284,-0.00872257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.638239,0.00459236) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377032,-0.0129868) , 
2, 2.12303, 1, 0, 0.630355,0.02365) , 
6, 95.4358, 1, 0, 0.5,0.000599266)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576804,0.00425679) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18216,-0.0234775) , 
3, 2.59428, 1, 0, 0.566695,0.0215153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452233,-0.00239771) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727749,0.0109428) , 
1, 7.00995, 1, 0, 0.46743,-0.00961823) , 
5, 2.05071, 1, 0, 0.5,0.000597024)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471833,-0.000442822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.276497,-0.00658311) , 
0, 1.54423, 1, 0, 0.387809,-0.0161307) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.662459,0.00639961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.546699,0.000286091) , 
5, 2.05647, 1, 0, 0.583636,0.0130245) , 
1, 4.05473, 1, 0, 0.5,0.000572567)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48021,-0.000618518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279069,-0.00711943) , 
0, 1.69317, 1, 0, 0.409309,-0.0152226) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55308,0.00137067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737693,0.0098254) , 
4, 182.593, 1, 0, 0.574126,0.0134544) , 
4, 63.8548, 1, 0, 0.5,0.000557018)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630069,0.0058798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37109,-0.0105769) , 
5, 2.73676, 1, 0, 0.618902,0.0297994) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629348,0.00474152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442519,-0.00220873) , 
0, 0.687829, 1, 0, 0.472541,-0.00619461) , 
2, 0.680726, 1, 0, 0.5,0.000558295)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58164,0.00317022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359353,-0.00721048) , 
5, 2.63721, 1, 0, 0.562363,0.0135054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461335,-0.00133242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.250409,-0.010036) , 
0, 2.12836, 1, 0, 0.428136,-0.0144039) , 
3, 1.12077, 1, 0, 0.5,0.000538447)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.346193,-0.00445746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505269,0.000608474) , 
4, 57.8877, 1, 0, 0.439994,-0.00795243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.685119,0.00533544) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.526586,-0.00145448) , 
5, 2.42627, 1, 0, 0.650908,0.0218376) , 
1, 5.0398, 1, 0, 0.5,0.000522927)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480549,0.00239243) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416924,-0.00485982) , 
6, 52.2285, 1, 0, 0.447284,-0.00781961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.633692,0.00392192) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268316,-0.0261233) , 
2, 2.52376, 1, 0, 0.630355,0.0211398) , 
6, 95.4358, 1, 0, 0.5,0.00051941)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53085,0.00132138) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275646,-0.00926059) , 
3, 2.0604, 1, 0, 0.513199,0.00399043) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307199,-0.00955392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.681687,0.0148611) , 
4, 201.138, 1, 0, 0.318354,-0.0472704) , 
5, 2.71924, 1, 0, 0.5,0.000518082)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529099,0.00118424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402472,-0.00341211) , 
5, 2.27356, 1, 0, 0.479712,-0.00333437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726869,0.00861681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687722,-0.0144221) , 
6, 348.06, 1, 0, 0.725115,0.0430323) , 
4, 167.284, 1, 0, 0.5,0.000498836)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642531,0.0125651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61585,0.00359726) , 
6, 22.4574, 1, 0, 0.618902,0.0267729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629348,0.00431391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442519,-0.00200391) , 
0, 0.687829, 1, 0, 0.472541,-0.00558939) , 
2, 0.680726, 1, 0, 0.5,0.000482165)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489123,0.00302612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456647,-0.00243343) , 
6, 41.753, 1, 0, 0.466452,-0.00442553) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.716413,0.0068102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.669672,-0.0142766) , 
6, 303.122, 1, 0, 0.713487,0.0315886) , 
6, 129.119, 1, 0, 0.5,0.000465253)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546637,0.00170191) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.201219,-0.0168297) , 
3, 2.38073, 1, 0, 0.538362,0.00777487) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519799,0.00854895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382274,-0.00451318) , 
5, 1.56694, 1, 0, 0.391174,-0.0202918) , 
2, 1.41386, 1, 0, 0.5,0.000459829)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469596,0.00020288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343737,-0.00633508) , 
5, 2.1303, 1, 0, 0.393642,-0.0202565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542317,0.00161632) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216844,-0.0187359) , 
0, 2.40065, 1, 0, 0.537298,0.00770672) , 
4, 43.9645, 1, 0, 0.5,0.000446489)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.544811,0.00226527) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434388,-0.00229306) , 
5, 2.05071, 1, 0, 0.471802,-0.00414265) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.688901,0.00460986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.770715,0.0140879) , 
1, 8.03483, 1, 0, 0.700041,0.0329089) , 
1, 6.02488, 1, 0, 0.5,0.000434899)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568806,0.00239017) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336241,-0.012581) , 
2, 2.15528, 1, 0, 0.562363,0.0115704) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436042,-0.00178718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152398,-0.0218389) , 
3, 2.69447, 1, 0, 0.428136,-0.0124291) , 
3, 1.12077, 1, 0, 0.5,0.000420005)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.598857,0.00379395) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.78013,0.00976917) , 
4, 97.7158, 1, 0, 0.661525,0.0323595) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463531,-0.00119969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720899,0.00804039) , 
4, 183.196, 1, 0, 0.47859,-0.00382793) , 
0, 0.563713, 1, 0, 0.5,0.000407225)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.329117,-0.00380852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.540814,0.00111755) , 
6, 95.4358, 1, 0, 0.387809,-0.0130261) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596382,0.00248901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421795,-0.00700493) , 
2, 1.77541, 1, 0, 0.583636,0.0104075) , 
1, 4.05473, 1, 0, 0.5,0.000399196)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510758,0.000274891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759579,0.00858844) , 
4, 181.207, 1, 0, 0.527495,0.00457978) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.309549,-0.00414026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203521,-0.0174856) , 
0, 2.40176, 1, 0, 0.295232,-0.0307278) , 
0, 2.12758, 1, 0, 0.5,0.000400159)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534027,0.00121257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.206332,-0.0135496) , 
3, 2.42344, 1, 0, 0.524566,0.00501995) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.345762,-0.00543186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694717,0.0109502) , 
4, 201.098, 1, 0, 0.357106,-0.026543) , 
5, 2.54415, 1, 0, 0.5,0.000389675)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478894,0.00204361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416582,-0.00433926) , 
6, 53.6529, 1, 0, 0.447284,-0.0066106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629859,0.00347974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653112,-0.0176994) , 
6, 326.694, 1, 0, 0.630355,0.0176492) , 
6, 95.4358, 1, 0, 0.5,0.000375136)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.630069,0.00462256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37109,-0.00867187) , 
5, 2.73676, 1, 0, 0.618902,0.0229502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629348,0.0036096) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442519,-0.00171536) , 
0, 0.687829, 1, 0, 0.472541,-0.00483894) , 
2, 0.680726, 1, 0, 0.5,0.000374622)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381381,-0.00381053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.691965,0.0103049) , 
1, 7.03483, 1, 0, 0.393642,-0.0178153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.538905,0.00506067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53688,0.000127015) , 
6, 39.2971, 1, 0, 0.537298,0.00673776) , 
4, 43.9645, 1, 0, 0.5,0.000362933)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572959,0.00264859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.196342,-0.0157037) , 
3, 2.55157, 1, 0, 0.562954,0.0130207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43964,-0.00214149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.722351,0.00905457) , 
1, 7.00995, 1, 0, 0.455332,-0.00863447) , 
5, 2.11438, 1, 0, 0.5,0.000353332)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488892,0.00258153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465696,-0.00192226) , 
6, 41.8943, 1, 0, 0.472516,-0.00334117) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729765,0.00709414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674694,-0.0128144) , 
6, 297.649, 1, 0, 0.725134,0.0305063) , 
6, 140.347, 1, 0, 0.5,0.000341314)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567411,0.0020335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299369,-0.015743) , 
2, 2.34843, 1, 0, 0.563361,0.0102729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36024,-0.00364145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56211,0.00109474) , 
4, 87.7723, 1, 0, 0.431112,-0.0104633) , 
3, 1.09941, 1, 0, 0.5,0.000338123)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569233,0.0052795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375982,-0.0025881) , 
0, 0.414772, 1, 0, 0.387809,-0.0114728) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596845,0.00222888) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425102,-0.00609897) , 
2, 1.75784, 1, 0, 0.583636,0.00914342) , 
1, 4.05473, 1, 0, 0.5,0.000338404)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576955,0.00308012) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187832,-0.016269) , 
3, 2.59428, 1, 0, 0.566788,0.0154622) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526462,0.000182032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30535,-0.00538502) , 
0, 1.85453, 1, 0, 0.470404,-0.00637557) , 
5, 2.0348, 1, 0, 0.5,0.000329954)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478894,0.00170754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.416582,-0.00380253) , 
6, 53.6529, 1, 0, 0.447284,-0.00599296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.629859,0.00315689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.653112,-0.0153998) , 
6, 326.694, 1, 0, 0.630355,0.0159379) , 
6, 95.4358, 1, 0, 0.5,0.000322125)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627274,0.0040851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481888,-0.000414511) , 
2, 0.680726, 1, 0, 0.509635,0.00249075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.289993,-0.00918397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.682699,0.0153668) , 
4, 201.138, 1, 0, 0.300021,-0.0446828) , 
5, 2.79883, 1, 0, 0.5,0.000322411)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.399213,-0.00257909) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545537,0.00133376) , 
4, 45.9536, 1, 0, 0.504842,0.00155665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201368,-0.0136869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24049,-0.0247055) , 
4, 124.567, 1, 0, 0.206404,-0.0753045) , 
0, 2.40064, 1, 0, 0.5,0.00030956)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44302,-0.0011906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.711293,0.00454605) , 
6, 140.347, 1, 0, 0.471802,-0.00332779) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734293,0.00651869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581814,-0.000744968) , 
5, 2.41228, 1, 0, 0.700041,0.0260487) , 
1, 6.02488, 1, 0, 0.5,0.000301551)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626935,0.00226356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.845152,0.0124447) , 
1, 7.00995, 1, 0, 0.63904,0.0154446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452337,-0.000616872) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275424,-0.0119106) , 
2, 2.26588, 1, 0, 0.446375,-0.00552926) , 
0, 0.923651, 1, 0, 0.5,0.000308438)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.43738,-0.000628996) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.643499,0.00325402) , 
1, 4.04478, 1, 0, 0.554083,0.00888275) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336614,-0.00471548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498254,-6.05098e-05) , 
4, 53.9097, 1, 0, 0.436356,-0.00980357) , 
5, 2.20989, 1, 0, 0.5,0.000298378)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560329,0.00153637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413172,-0.00237972) , 
2, 1.43367, 1, 0, 0.525081,0.00346814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308174,-0.00341835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.202755,-0.0150361) , 
0, 2.40139, 1, 0, 0.292488,-0.0259384) , 
0, 2.15241, 1, 0, 0.5,0.000297123)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491483,-2.95332e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.296121,-0.00956226) , 
2, 2.16681, 1, 0, 0.484247,-0.00204257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.758285,0.0231547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.737162,0.00601914) , 
5, 1.41315, 1, 0, 0.737849,0.0354906) , 
4, 183.196, 1, 0, 0.5,0.000288878)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53085,0.000911287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275646,-0.00659919) , 
3, 2.0604, 1, 0, 0.513199,0.00268618) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430052,-0.00142808) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258475,-0.00923323) , 
0, 1.18934, 1, 0, 0.318354,-0.0328215) , 
5, 2.71924, 1, 0, 0.5,0.000280937)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.575958,0.00268733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177644,-0.0160778) , 
3, 2.63699, 1, 0, 0.566788,0.0135364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.455379,-0.00145488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72906,0.00720373) , 
1, 7.00995, 1, 0, 0.470404,-0.00560553) , 
5, 2.0348, 1, 0, 0.5,0.000272224)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669211,0.00920088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660424,0.0035852) , 
6, 21.2527, 1, 0, 0.661525,0.0242298) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527893,0.000764987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400497,-0.00260735) , 
5, 2.27356, 1, 0, 0.47859,-0.00291269) , 
0, 0.563713, 1, 0, 0.5,0.000263906)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478953,0.00166359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411817,-0.00403553) , 
6, 53.6241, 1, 0, 0.446863,-0.00578302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607965,0.00252756) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646957,-0.0163365) , 
6, 332.671, 1, 0, 0.608643,0.0125918) , 
6, 89.8219, 1, 0, 0.5,0.000252205)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.539623,-0.00471516) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564568,0.00200977) , 
3, 0.479045, 1, 0, 0.562363,0.00818813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571725,0.0063755) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420274,-0.00206776) , 
2, 0.522211, 1, 0, 0.428136,-0.0088906) , 
3, 1.12077, 1, 0, 0.5,0.000253184)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451627,-0.000516273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.221535,-0.00960668) , 
0, 2.30135, 1, 0, 0.439994,-0.00506256) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.741814,0.00734903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63207,0.00146692) , 
2, 0.594373, 1, 0, 0.650908,0.0135968) , 
1, 5.0398, 1, 0, 0.5,0.000246083)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485133,-0.000156314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274328,-0.0105189) , 
2, 2.28569, 1, 0, 0.479712,-0.00226921) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.726869,0.00592198) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.687722,-0.0102177) , 
6, 348.06, 1, 0, 0.725115,0.0281131) , 
4, 167.284, 1, 0, 0.5,0.000242543)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488892,0.00221943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465696,-0.0015972) , 
6, 41.8943, 1, 0, 0.472516,-0.00261977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729765,0.00573894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674694,-0.0111869) , 
6, 297.649, 1, 0, 0.725134,0.0236396) , 
6, 140.347, 1, 0, 0.5,0.000237155)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403594,-0.00202168) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.547766,0.0011846) , 
4, 45.9536, 1, 0, 0.507811,0.00178535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.0013992) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229436,-0.0118534) , 
0, 1.17654, 1, 0, 0.288773,-0.0416425) , 
5, 2.84658, 1, 0, 0.5,0.000236647)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.667598,0.00423846) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396664,-0.00801922) , 
5, 2.87215, 1, 0, 0.661525,0.022017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463531,-0.000839255) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720899,0.00567072) , 
4, 183.196, 1, 0, 0.47859,-0.00265654) , 
0, 0.563713, 1, 0, 0.5,0.000231106)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627011,0.00914651) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600756,0.00182425) , 
6, 11.2297, 1, 0, 0.602255,0.0126516) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463742,-0.000636645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.177995,-0.0155382) , 
0, 2.40064, 1, 0, 0.458645,-0.00479782) , 
2, 0.799613, 1, 0, 0.5,0.000226996)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576955,0.00239998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187832,-0.0133043) , 
3, 2.59428, 1, 0, 0.566788,0.0119076) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526462,0.000142504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30535,-0.00426039) , 
0, 1.85453, 1, 0, 0.470404,-0.00496308) , 
5, 2.0348, 1, 0, 0.5,0.000217252)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554679,0.00140161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43964,-0.00150796) , 
5, 2.11438, 1, 0, 0.487943,-0.00152961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786018,0.00869104) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513514,-0.00147055) , 
0, 1.9539, 1, 0, 0.741106,0.0350785) , 
1, 7.00995, 1, 0, 0.5,0.000213882)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478953,0.00145134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411817,-0.0035942) , 
6, 53.6241, 1, 0, 0.446863,-0.00521148) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607965,0.00227438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646957,-0.0140812) , 
6, 332.671, 1, 0, 0.608643,0.0112892) , 
6, 89.8219, 1, 0, 0.5,0.000208174)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520863,0.010576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38522,-0.00183395) , 
5, 1.39811, 1, 0, 0.387809,-0.00865665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605991,0.00179502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.382763,-0.00445877) , 
3, 1.76186, 1, 0, 0.583636,0.00682027) , 
1, 4.05473, 1, 0, 0.5,0.000210198)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.49349,-8.17674e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.130792,-0.0196328) , 
3, 2.74377, 1, 0, 0.489377,-0.00130098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.764043,0.00762271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37618,-0.0126298) , 
0, 2.30142, 1, 0, 0.753613,0.0362797) , 
4, 209.054, 1, 0, 0.5,0.000209808)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.535887,0.000882696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.19925,-0.011165) , 
3, 2.38073, 1, 0, 0.527444,0.00369312) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378495,-0.00251754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337643,-0.0410987) , 
6, 287.041, 1, 0, 0.378227,-0.0152716) , 
2, 1.57237, 1, 0, 0.5,0.000205167)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419825,-0.0011327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267487,-0.00806557) , 
2, 1.60361, 1, 0, 0.393642,-0.011987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549196,0.00491543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535769,0.000240326) , 
6, 22.4555, 1, 0, 0.537298,0.00447321) , 
4, 43.9645, 1, 0, 0.5,0.000199578)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488892,0.00187617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.465696,-0.0013779) , 
6, 41.8943, 1, 0, 0.472516,-0.002314) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729765,0.00510827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674694,-0.00990091) , 
6, 297.649, 1, 0, 0.725134,0.0207819) , 
6, 140.347, 1, 0, 0.5,0.000198749)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483553,-0.000368565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.690237,0.0049489) , 
1, 4.0398, 1, 0, 0.626958,0.0180326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444673,-0.00106055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.672375,0.00275768) , 
4, 131.482, 1, 0, 0.47969,-0.00265397) , 
2, 0.621283, 1, 0, 0.5,0.000198882)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669743,0.00396736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.488095,-0.000163303) , 
0, 0.538889, 1, 0, 0.507811,0.00155804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.000947746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229436,-0.010703) , 
0, 1.17654, 1, 0, 0.288773,-0.0364597) , 
5, 2.84658, 1, 0, 0.5,0.000202274)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478953,0.001237) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411817,-0.00317798) , 
6, 53.6241, 1, 0, 0.446863,-0.00472514) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.61174,0.00201593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.274026,-0.0188857) , 
2, 2.51323, 1, 0, 0.608643,0.0102464) , 
6, 89.8219, 1, 0, 0.5,0.00019227)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53993,-0.00446426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565811,0.00179406) , 
3, 0.482015, 1, 0, 0.563361,0.00689488) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425425,-0.00152001) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749286,0.0110561) , 
4, 252.835, 1, 0, 0.431112,-0.00708561) , 
3, 1.09941, 1, 0, 0.5,0.000196781)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494369,-5.44004e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.748246,0.00633192) , 
1, 7.00995, 1, 0, 0.506486,0.00126798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.255247,-0.00671884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139784,-0.0218737) , 
5, 2.50566, 1, 0, 0.232729,-0.0440777) , 
0, 2.37582, 1, 0, 0.5,0.000193646)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593715,-0.00588156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565328,0.00224664) , 
3, 0.480109, 1, 0, 0.566788,0.0103395) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526462,0.00010857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.30535,-0.00368173) , 
0, 1.85453, 1, 0, 0.470404,-0.00431238) , 
5, 2.0348, 1, 0, 0.5,0.000186652)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608259,0.00483077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463971,-0.000711831) , 
2, 0.522211, 1, 0, 0.471802,-0.00229947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.702658,0.00353463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363617,-0.0225606) , 
2, 2.16519, 1, 0, 0.700041,0.017772) , 
1, 6.02488, 1, 0, 0.5,0.00018027)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.480545,0.00120028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412299,-0.00287436) , 
6, 52.2835, 1, 0, 0.446863,-0.00436968) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.707565,0.0198686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.607651,0.00150273) , 
5, 1.41386, 1, 0, 0.608643,0.0094706) , 
6, 89.8219, 1, 0, 0.5,0.000176167)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411325,-0.000980381) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.610004,0.00162064) , 
1, 4.05473, 1, 0, 0.527385,0.00308853) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.369788,-0.00231711) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.142773,-0.0195175) , 
0, 2.37584, 1, 0, 0.363648,-0.014305) , 
5, 2.51232, 1, 0, 0.5,0.000179481)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558687,0.00109947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304443,-0.0117566) , 
2, 2.25074, 1, 0, 0.553282,0.00477711) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570451,0.0178785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395818,-0.00183097) , 
5, 1.24544, 1, 0, 0.397509,-0.00867059) , 
3, 1.31296, 1, 0, 0.5,0.00017733)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419825,-0.000993246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267487,-0.00716237) , 
2, 1.60361, 1, 0, 0.393642,-0.0105052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524719,0.00258149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54297,-0.000183636) , 
6, 56.1387, 1, 0, 0.537298,0.00392028) , 
4, 43.9645, 1, 0, 0.5,0.000174934)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663808,0.00287031) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594303,0.011038) , 
2, 1.98484, 1, 0, 0.661525,0.0174196) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527893,0.000605245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400497,-0.00198994) , 
5, 2.27356, 1, 0, 0.47859,-0.00211461) , 
0, 0.563713, 1, 0, 0.5,0.000171555)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636265,0.00446114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486503,-0.000399492) , 
2, 0.522211, 1, 0, 0.495368,-0.000642284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749903,0.012277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798713,0.00465156) , 
4, 95.1311, 1, 0, 0.770715,0.0472797) , 
1, 8.04975, 1, 0, 0.5,0.000163879)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494146,-6.46022e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757763,0.0062409) , 
4, 209.054, 1, 0, 0.504842,0.00094806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201368,-0.00852348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24049,-0.0205125) , 
4, 124.567, 1, 0, 0.206404,-0.0478187) , 
0, 2.40064, 1, 0, 0.5,0.000156808)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478953,0.000986203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.411817,-0.00268161) , 
6, 53.6241, 1, 0, 0.446863,-0.00413369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607965,0.00184351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646957,-0.0130021) , 
6, 332.671, 1, 0, 0.608643,0.0089139) , 
6, 89.8219, 1, 0, 0.5,0.000151799)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474223,-0.000205073) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.721866,0.00319722) , 
6, 129.119, 1, 0, 0.507811,0.00130729) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.000588701) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229436,-0.00940272) , 
0, 1.17654, 1, 0, 0.288773,-0.0310428) , 
5, 2.84658, 1, 0, 0.5,0.000153636)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571677,0.00187218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.47325,-0.000606866) , 
5, 2.03102, 1, 0, 0.502714,0.00079977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.251608,-0.0168618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314213,0.00224817) , 
3, 1.61641, 1, 0, 0.274095,-0.0534639) , 
2, 2.52346, 1, 0, 0.5,0.000155706)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.512323,0.000375543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.327494,-0.00539954) , 
2, 2.12718, 1, 0, 0.504734,0.000838052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355952,0.0182515) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.132868,-0.0177801) , 
5, 1.67345, 1, 0, 0.156573,-0.0499716) , 
3, 2.6797, 1, 0, 0.5,0.000147173)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570476,0.0139937) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439089,-0.000739476) , 
5, 1.25485, 1, 0, 0.439994,-0.00350952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.613975,0.000715281) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.769578,0.00535933) , 
6, 106.142, 1, 0, 0.650908,0.00932081) , 
1, 5.0398, 1, 0, 0.5,0.000140754)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.652398,0.00607653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.644303,0.00156469) , 
6, 15.9221, 1, 0, 0.645052,0.0110821) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491958,0.000131655) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344469,-0.00301671) , 
5, 2.44865, 1, 0, 0.459498,-0.00291266) , 
0, 0.799534, 1, 0, 0.5,0.00014208)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53993,-0.00413998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565811,0.00151884) , 
3, 0.482015, 1, 0, 0.563361,0.00560483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.437158,0.00230289) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429991,-0.00170741) , 
6, 26.2568, 1, 0, 0.431112,-0.00580417) , 
3, 1.09941, 1, 0, 0.5,0.000138742)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.627011,0.00722317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600756,0.00127709) , 
6, 11.2297, 1, 0, 0.602255,0.00899822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.313815,-0.0111408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46125,-0.000437301) , 
4, 10.1511, 1, 0, 0.458645,-0.00344963) , 
2, 0.799613, 1, 0, 0.5,0.000134913)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488791,-8.64035e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598443,-0.0181657) , 
6, 296.479, 1, 0, 0.489377,-0.00101717) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756108,-0.00134116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.752877,0.00724853) , 
3, 0.663091, 1, 0, 0.753613,0.0275404) , 
4, 209.054, 1, 0, 0.5,0.000130876)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.388762,-0.00191911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532899,0.000501777) , 
4, 43.9645, 1, 0, 0.495368,-0.000606962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.880133,0.0257161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.762341,0.00734688) , 
5, 1.93125, 1, 0, 0.770715,0.0428159) , 
1, 8.04975, 1, 0, 0.5,0.000123514)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477216,-0.000205171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.729417,0.00323753) , 
6, 140.347, 1, 0, 0.504842,0.000842007) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201368,-0.00773858) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24049,-0.0192567) , 
4, 124.567, 1, 0, 0.206404,-0.0433753) , 
0, 2.40064, 1, 0, 0.5,0.000124569)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599983,0.00154427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786221,0.00666234) , 
4, 97.7158, 1, 0, 0.664222,0.016971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532259,0.00052988) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404494,-0.00164123) , 
5, 2.27356, 1, 0, 0.482894,-0.00162792) , 
0, 0.501654, 1, 0, 0.5,0.000126664)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.527348,0.000553356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298387,-0.009248) , 
2, 2.26588, 1, 0, 0.522001,0.00191204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.439566,0.00818902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281201,-0.00511803) , 
5, 1.71073, 1, 0, 0.299342,-0.0161872) , 
3, 1.91091, 1, 0, 0.5,0.000123626)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666746,0.00635449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342182,-0.0144853) , 
5, 2.65287, 1, 0, 0.646932,0.027465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447136,-0.000705376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.659589,0.00172577) , 
4, 113.58, 1, 0, 0.49432,-0.000933163) , 
2, 0.482582, 1, 0, 0.5,0.000123722)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481944,0.00406656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380816,-0.00152598) , 
5, 1.70053, 1, 0, 0.387809,-0.0060253) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.596382,0.0012374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421795,-0.00420895) , 
2, 1.77541, 1, 0, 0.583636,0.00471243) , 
1, 4.05473, 1, 0, 0.5,0.000126427)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537586,-0.00424561) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502407,0.000336978) , 
3, 0.476053, 1, 0, 0.50402,0.000692437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.122281,-0.0171683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474553,0.0135399) , 
4, 162.541, 1, 0, 0.148215,-0.0494309) , 
3, 2.74377, 1, 0, 0.5,0.00012616)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478951,0.000958847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407434,-0.00289239) , 
6, 53.6249, 1, 0, 0.447556,-0.00390636) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585163,0.00148427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.675319,-0.0094768) , 
6, 297.201, 1, 0, 0.587376,0.00682494) , 
6, 84.208, 1, 0, 0.5,0.000118747)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554679,0.00097467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.43964,-0.00104482) , 
5, 2.11438, 1, 0, 0.487943,-0.0010349) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.786018,0.00635841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.513514,-0.00247284) , 
0, 1.9539, 1, 0, 0.741106,0.0232068) , 
1, 7.00995, 1, 0, 0.5,0.00011963)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606965,0.00166998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542489,0.0199884) , 
0, 1.22792, 1, 0, 0.57105,0.0714218) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.521835,0.000282391) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293328,-0.00364736) , 
3, 1.91091, 1, 0, 0.499641,-0.000242527) , 
5, 1.25485, 1, 0, 0.5,0.000117714)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368276,-0.00710661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.5072,0.000259897) , 
4, 10.1511, 1, 0, 0.504842,0.000763698) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.271968,-0.00236541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143262,-0.0163782) , 
2, 1.17473, 1, 0, 0.206404,-0.0391955) , 
0, 2.40064, 1, 0, 0.5,0.000115349)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510554,0.000293513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278794,-0.00897647) , 
2, 2.52346, 1, 0, 0.507811,0.00107158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.000236271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229436,-0.00813765) , 
0, 1.17654, 1, 0, 0.288773,-0.0259281) , 
5, 2.84658, 1, 0, 0.5,0.000108735)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.767047,0.0134006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627206,0.00220366) , 
5, 1.79066, 1, 0, 0.633861,0.0146287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453237,-0.000675978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.686757,0.00228864) , 
4, 139.438, 1, 0, 0.484323,-0.00159871) , 
2, 0.581654, 1, 0, 0.5,0.000102542)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599983,0.00141441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.786221,0.00598952) , 
4, 97.7158, 1, 0, 0.664222,0.0152385) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478243,-0.000388327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.760462,0.00783426) , 
1, 8.04975, 1, 0, 0.482894,-0.00147043) , 
0, 0.501654, 1, 0, 0.5,0.000105859)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499169,0.00212795) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.466793,-0.000813096) , 
6, 26.5331, 1, 0, 0.472516,-0.00158347) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.729765,0.00372388) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.674694,-0.00898618) , 
6, 297.649, 1, 0, 0.725134,0.0139276) , 
6, 140.347, 1, 0, 0.5,0.000104072)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53993,-0.00364656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565811,0.00129968) , 
3, 0.482015, 1, 0, 0.563361,0.00471506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425425,-0.00108227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.749286,0.00894875) , 
4, 252.835, 1, 0, 0.431112,-0.00490246) , 
3, 1.09941, 1, 0, 0.5,0.000107271)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573424,0.0113424) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562348,0.00174418) , 
5, 1.24416, 1, 0, 0.562722,0.0118339) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495198,-0.000157718) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.245827,-0.00915266) , 
2, 2.24897, 1, 0, 0.48955,-0.00184622) , 
5, 1.89154, 1, 0, 0.5,0.000107463)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39227,-0.000906037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586366,0.000833523) , 
1, 4.05473, 1, 0, 0.50402,0.000608992) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.130103,-0.0169226) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.241998,0.00965468) , 
2, 1.94523, 1, 0, 0.148215,-0.0441517) , 
3, 2.74377, 1, 0, 0.5,0.000103301)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478951,0.000863639) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407434,-0.00261598) , 
6, 53.6249, 1, 0, 0.447556,-0.00353182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.661159,0.00373702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.563551,0.000286687) , 
3, 0.729406, 1, 0, 0.587376,0.00615689) , 
6, 84.208, 1, 0, 0.5,0.00010223)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38089,-0.01228) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313359,-0.000253619) , 
5, 2.31744, 1, 0, 0.355796,-0.0444216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507179,0.00242537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500802,-0.000241204) , 
6, 22.4555, 1, 0, 0.501618,0.000606046) , 
4, 8.16209, 1, 0, 0.5,0.000106536)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666746,0.00561603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342182,-0.013491) , 
5, 2.65287, 1, 0, 0.646932,0.0238381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403216,-0.00113361) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56928,0.000633384) , 
4, 63.8548, 1, 0, 0.49432,-0.000818361) , 
2, 0.482582, 1, 0, 0.5,9.92699e-05)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560329,0.000829118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413172,-0.00137501) , 
2, 1.43367, 1, 0, 0.525081,0.00170961) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.433411,0.0251687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291214,-0.00291058) , 
5, 1.40603, 1, 0, 0.292488,-0.0132019) , 
0, 2.15241, 1, 0, 0.5,0.000101649)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472731,-0.00025277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730062,0.00324354) , 
6, 140.822, 1, 0, 0.499045,0.000465458) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728661,-0.00349648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.461126,-0.0272155) , 
2, 1.05071, 1, 0, 0.652701,-0.0581636) , 
6, 325.604, 1, 0, 0.5,0.000101249)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547223,-0.00349334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.505801,0.000364699) , 
3, 0.480109, 1, 0, 0.507811,0.000969211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411392,-0.000144258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.229436,-0.00743544) , 
0, 1.17654, 1, 0, 0.288773,-0.0233286) , 
5, 2.84658, 1, 0, 0.5,0.000102716)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.494146,-5.17511e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757763,0.00466217) , 
4, 209.054, 1, 0, 0.504842,0.000668364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.201368,-0.00595488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24049,-0.0175647) , 
4, 124.567, 1, 0, 0.206404,-0.0346595) , 
0, 2.40064, 1, 0, 0.5,9.51603e-05)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574634,0.0105558) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.562862,0.00153164) , 
5, 1.25145, 1, 0, 0.563235,0.0103628) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487408,-0.000251897) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627208,-0.0141495) , 
6, 323.728, 1, 0, 0.488209,-0.0018224) , 
5, 1.90746, 1, 0, 0.5,9.26846e-05)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.465617,-0.000424352) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.753641,0.0064363) , 
4, 238.889, 1, 0, 0.471802,-0.00159067) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.734293,0.00364358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.581814,-0.00181286) , 
5, 2.41228, 1, 0, 0.700041,0.0119718) , 
1, 6.02488, 1, 0, 0.5,8.4914e-05)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.704539,0.00387927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59541,0.000364071) , 
3, 1.10382, 1, 0, 0.664222,0.0137021) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553553,0.000608221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.410076,-0.00113424) , 
2, 1.07701, 1, 0, 0.482894,-0.00133068) , 
0, 0.501654, 1, 0, 0.5,8.74808e-05)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50903,0.000216591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.275903,-0.00861395) , 
2, 2.52346, 1, 0, 0.506421,0.000704606) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.463955,0.0202233) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168457,-0.00976386) , 
5, 1.4154, 1, 0, 0.181931,-0.03045) , 
3, 2.55157, 1, 0, 0.5,8.81035e-05)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.636265,0.00317785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486503,-0.000288089) , 
2, 0.522211, 1, 0, 0.495368,-0.000478906) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749903,0.00978511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.798713,0.00189258) , 
4, 95.1311, 1, 0, 0.770715,0.033003) , 
1, 8.04975, 1, 0, 0.5,8.43392e-05)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38089,-0.0113056) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313359,-5.29619e-05) , 
5, 2.31744, 1, 0, 0.355796,-0.0404364) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507179,0.00227735) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.500802,-0.000233186) , 
6, 22.4555, 1, 0, 0.501618,0.000535965) , 
4, 8.16209, 1, 0, 0.5,8.14413e-05)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478951,0.000763986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.407434,-0.00235609) , 
6, 53.6249, 1, 0, 0.447556,-0.00321475) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590246,0.0011339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256132,-0.0145477) , 
2, 2.52814, 1, 0, 0.587376,0.00555862) , 
6, 84.208, 1, 0, 0.5,7.59804e-05)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.593715,-0.00523254) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565328,0.00149079) , 
3, 0.480109, 1, 0, 0.566788,0.00637536) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469724,-0.0004125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.597723,-0.0150811) , 
6, 329.035, 1, 0, 0.470404,-0.0027082) , 
5, 2.0348, 1, 0, 0.5,8.10026e-05)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55469,0.000668708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630428,-0.0168207) , 
6, 348.06, 1, 0, 0.555113,0.00325498) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567935,0.00171227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.365962,-0.00173695) , 
0, 0.889762, 1, 0, 0.404931,-0.00541522) , 
3, 1.27025, 1, 0, 0.5,7.32584e-05)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.36879,-0.00601895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508864,0.000231287) , 
4, 10.1511, 1, 0, 0.506486,0.000704856) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.219833,-0.00396572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.285545,-0.0112092) , 
4, 108.714, 1, 0, 0.232729,-0.0259907) , 
0, 2.37582, 1, 0, 0.5,7.2385e-05)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.481944,0.00324378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.380816,-0.00119023) , 
5, 1.70053, 1, 0, 0.387809,-0.00463515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.590979,0.000863253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350331,-0.00665326) , 
5, 2.8004, 1, 0, 0.583636,0.00357491) , 
1, 4.05473, 1, 0, 0.5,6.84612e-05)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537586,-0.00349657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502407,0.00026534) , 
3, 0.476053, 1, 0, 0.50402,0.000499671) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295891,0.00827517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.119121,-0.0157542) , 
5, 1.77394, 1, 0, 0.148215,-0.0375578) , 
3, 2.74377, 1, 0, 0.5,6.9711e-05)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519529,-0.00338438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468599,2.9864e-05) , 
3, 0.52282, 1, 0, 0.472516,-0.00132699) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737151,0.00282588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.377927,-0.0130474) , 
2, 2.10556, 1, 0, 0.725134,0.011471) , 
6, 140.347, 1, 0, 0.5,6.53841e-05)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55611,-0.00151764) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.56899,0.00152772) , 
3, 0.584016, 1, 0, 0.56569,0.00423916) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302024,-0.0071146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.446465,-0.000422709) , 
4, 16.1786, 1, 0, 0.440307,-0.0037215) , 
3, 1.03535, 1, 0, 0.5,6.84466e-05)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.488603,-0.000199625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.763895,0.00513553) , 
4, 236.9, 1, 0, 0.495368,-0.000448106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.777188,0.00508662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.699522,0.0168049) , 
3, 1.46978, 1, 0, 0.770715,0.0303391) , 
1, 8.04975, 1, 0, 0.5,6.98084e-05)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606965,-0.000292828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542489,0.0165633) , 
0, 1.22792, 1, 0, 0.57105,0.0551025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507856,0.000128294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314221,-0.00409434) , 
2, 2.10736, 1, 0, 0.499641,-0.00020862) , 
5, 1.25485, 1, 0, 0.5,6.94171e-05)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.645991,0.00117441) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588051,0.0116806) , 
2, 2.18176, 1, 0, 0.645052,0.00743655) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491958,0.000119928) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344469,-0.00219999) , 
5, 2.44865, 1, 0, 0.459498,-0.00199154) , 
0, 0.799534, 1, 0, 0.5,6.63968e-05)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.666746,0.00479907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342182,-0.012484) , 
5, 2.65287, 1, 0, 0.646932,0.0198667) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.387684,-0.00143176) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531982,0.000314324) , 
4, 43.9645, 1, 0, 0.49432,-0.000699741) , 
2, 0.482582, 1, 0, 0.5,6.5674e-05)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
