// Class: ReadBDTG
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDTG
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/13       [393741]
Creator        : mdjordje
Date           : Tue Feb 23 10:41:18 2016
Host           : Linux vocms0301.cern.ch 2.6.32-573.7.1.el6.x86_64 #1 SMP Wed Sep 23 10:12:03 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/m/mdjordje/CMSSW_7_6_3/src/CMGTools/TTHAnalysis/macros/finalMVA/2lss
Training events: 125846
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "True" [Create PDFs for classifier outputs (signal and background)]
NTrees: "200" [Number of trees in the forest]
nCuts: "200" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e-01" [Learning rate for GradBoost algorithm]
NegWeightTreatment: "pairnegweightsglobal" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
NNodesMax: "5" [deprecated: Use MaxDepth instead to limit the tree size]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "0.0794623.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]])) max_Lep_eta                                                    max_Lep_eta                                                    max_Lep_eta                                                                                                                       'F'    [0.00116471224464,2.49979782104]
MT_met_lep1                   MT_met_lep1                   MT_met_lep1                   MT_met_lep1                                                     'F'    [0.00345964450389,1643.45983887]
nJet25_Recl                   numJets_float                 numJets_float                 numJets_float                                                   'F'    [1,14]
mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                mindr_lep1_jet                                                  'F'    [0.268908649683,5.08621120453]
mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                mindr_lep2_jet                                                  'F'    [0.26680329442,5.01681900024]
LepGood_conePt[iF_Recl[0]]    LepGood_conePt_iF_Recl_0__    LepGood_conePt[iF_Recl[0]]    LepGood_conePt[iF_Recl[0]]                                      'F'    [20.0017719269,1127.06286621]
LepGood_conePt[iF_Recl[2]]    LepGood_conePt_iF_Recl_2__    LepGood_conePt[iF_Recl[2]]    LepGood_conePt[iF_Recl[2]]                                      'F'    [10.00004673,420.584594727]
NSpec 3
iF_Recl[0]                    iF0                           iF0                           F                                                               'F'    [0,4]
iF_Recl[1]                    iF1                           iF1                           F                                                               'F'    [0,4]
iF_Recl[2]                    iF2                           iF2                           F                                                               'F'    [0,4]


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTGNode
   
#ifndef BDTGNode__def
#define BDTGNode__def
   
class BDTGNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTGNode ( BDTGNode* left,BDTGNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTGNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTGNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTGNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTGNode*   fLeft;     // pointer to the left daughter node
   BDTGNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTGNode::~BDTGNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTGNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTGNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDTG : public IClassifierReader {

 public:

   // constructor
   ReadBDTG( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDTG" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "max(abs(LepGood_eta[iF_Recl[0]]),abs(LepGood_eta[iF_Recl[1]]))", "MT_met_lep1", "nJet25_Recl", "mindr_lep1_jet", "mindr_lep2_jet", "LepGood_conePt[iF_Recl[0]]", "LepGood_conePt[iF_Recl[2]]" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDTG() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTGNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDTG::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTGNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTGNode*)current->GetRight();
         else current=(BDTGNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReadBDTG::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363882,-0.0186457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266897,-0.0378717) , 
5, 91.1569, 1, 0, 0.32269,-0.17731) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.625856,0.0121041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469491,-0.00356728) , 
5, 102.618, 1, 0, 0.572836,0.0728363) , 
2, 2.03483, 1, 0, 0.5,-1.31908e-13)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363882,-0.0173749) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266897,-0.0348466) , 
5, 91.1569, 1, 0, 0.32269,-0.163909) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522881,0.00212331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678306,0.0158749) , 
2, 4.0398, 1, 0, 0.572836,0.0694414) , 
2, 2.03483, 1, 0, 0.5,0.00149568)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0223026) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48659,-0.00203491) , 
2, 2.00498, 1, 0, 0.398056,-0.0900453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669717,0.0146221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504643,0.000217669) , 
5, 108.126, 1, 0, 0.619213,0.111327) , 
2, 3.00498, 1, 0, 0.5,0.00277927)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0207249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48659,-0.00191859) , 
2, 2.00498, 1, 0, 0.398056,-0.0835797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681298,0.0148114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527548,0.00234685) , 
5, 91.6027, 1, 0, 0.619213,0.106224) , 
2, 3.00498, 1, 0, 0.5,0.00391207)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0192728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48659,-0.00180894) , 
2, 2.00498, 1, 0, 0.398056,-0.0775827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673362,0.0136126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511741,0.000788633) , 
5, 102.618, 1, 0, 0.619213,0.101344) , 
2, 3.00498, 1, 0, 0.5,0.00489502)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0179323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48659,-0.00170557) , 
2, 2.00498, 1, 0, 0.398056,-0.0720195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669717,0.0128022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504643,3.07346e-05) , 
5, 108.126, 1, 0, 0.619213,0.0967001) , 
2, 3.00498, 1, 0, 0.5,0.00575333)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447008,-0.0028392) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331374,-0.0184332) , 
5, 91.1569, 1, 0, 0.398056,-0.0668582) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681298,0.0130107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527548,0.00189163) , 
5, 91.6027, 1, 0, 0.619213,0.0922735) , 
2, 3.00498, 1, 0, 0.5,0.00649503)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0160449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48659,-0.00107055) , 
2, 2.00498, 1, 0, 0.398056,-0.0621991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587301,0.00575729) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.742453,0.017788) , 
2, 5.04478, 1, 0, 0.619213,0.0880405) , 
2, 3.00498, 1, 0, 0.5,0.00705524)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484013,1.06886e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33476,-0.0184106) , 
5, 121.643, 1, 0, 0.447392,-0.0310072) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.010603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0221505) , 
2, 6.02985, 1, 0, 0.678306,0.13839) , 
2, 4.0398, 1, 0, 0.5,0.00758559)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459577,-0.000608549) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.347955,-0.0137965) , 
5, 75.9108, 1, 0, 0.398056,-0.0554808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.681298,0.011841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.527548,0.0013095) , 
5, 91.6027, 1, 0, 0.619213,0.0820214) , 
2, 3.00498, 1, 0, 0.5,0.00790211)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32269,-0.0140951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.522881,0.00139694) , 
2, 2.01493, 1, 0, 0.447392,-0.0272293) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00979306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0211233) , 
2, 6.02985, 1, 0, 0.678306,0.12852) , 
2, 4.0398, 1, 0, 0.5,0.00825411)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.484013,0.00032595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.33476,-0.016233) , 
5, 121.643, 1, 0, 0.447392,-0.0250899) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00935509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0204046) , 
2, 6.02985, 1, 0, 0.678306,0.122826) , 
2, 4.0398, 1, 0, 0.5,0.00860877)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367613,-0.00545654) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291954,-0.0186485) , 
0, 1.07018, 1, 0, 0.32269,-0.0847081) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649768,0.0101499) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507733,-0.000392656) , 
5, 75.0794, 1, 0, 0.572836,0.0471806) , 
2, 2.03483, 1, 0, 0.5,0.00877797)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517213,0.00302305) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.388805,-0.00854482) , 
5, 75.9044, 1, 0, 0.447392,-0.022223) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00874315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0195805) , 
2, 6.02985, 1, 0, 0.678306,0.115195) , 
2, 4.0398, 1, 0, 0.5,0.00908409)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443114,6.97659e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.35892,-0.0112371) , 
0, 1.1448, 1, 0, 0.398056,-0.0423509) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669717,0.00967195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.504643,-0.000892635) , 
5, 108.126, 1, 0, 0.619213,0.0693742) , 
2, 3.00498, 1, 0, 0.5,0.00914979)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258243,-0.0236262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340812,-0.00834018) , 
2, 1.00498, 1, 0, 0.32269,-0.073788) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.615133,0.0071796) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449781,-0.00504265) , 
5, 119.142, 1, 0, 0.572836,0.0433833) , 
2, 2.03483, 1, 0, 0.5,0.00926601)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471502,-0.000161793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.304136,-0.0190244) , 
5, 152.135, 1, 0, 0.447392,-0.0187246) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00790127) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0186294) , 
2, 6.02985, 1, 0, 0.678306,0.10505) , 
2, 4.0398, 1, 0, 0.5,0.00947414)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491852,0.00267332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400696,-0.00790965) , 
0, 1.20697, 1, 0, 0.447392,-0.0173358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00754972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0180331) , 
2, 6.02985, 1, 0, 0.678306,0.100407) , 
2, 4.0398, 1, 0, 0.5,0.00948893)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367613,-0.00408562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291954,-0.0148954) , 
0, 1.07018, 1, 0, 0.32269,-0.0655828) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.649768,0.00878551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507733,-0.000385019) , 
5, 75.0794, 1, 0, 0.572836,0.0402168) , 
2, 2.03483, 1, 0, 0.5,0.00941064)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479249,0.0010641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3658,-0.0109521) , 
6, 32.4698, 1, 0, 0.447392,-0.0154345) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00704856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0173489) , 
2, 6.02985, 1, 0, 0.678306,0.0941281) , 
2, 4.0398, 1, 0, 0.5,0.00952648)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434061,-0.00076946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.323904,-0.0128963) , 
1, 159.421, 1, 0, 0.398056,-0.0317326) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.66045,0.00866322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.538518,-0.000848769) , 
6, 27.2258, 1, 0, 0.619213,0.0575866) , 
2, 3.00498, 1, 0, 0.5,0.0094399)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.258243,-0.0200985) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340812,-0.00620894) , 
2, 1.00498, 1, 0, 0.32269,-0.0571086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.606,0.0069262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508664,-0.00289586) , 
0, 1.42019, 1, 0, 0.572836,0.0367722) , 
2, 2.03483, 1, 0, 0.5,0.00943654)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560215,0.00542443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429012,-0.00425086) , 
5, 64.0639, 1, 0, 0.474605,-0.00408947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.0110081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0204779) , 
2, 7.03483, 1, 0, 0.742453,0.138708) , 
2, 5.00995, 1, 0, 0.5,0.00944929)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578205,0.00684194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471469,-0.00270137) , 
0, 1.4183, 1, 0, 0.539313,0.0333608) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.442939,-0.00265068) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286679,-0.0213317) , 
3, 1.36972, 1, 0, 0.388257,-0.0591596) , 
1, 163.531, 1, 0, 0.5,0.00928209)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468589,0.000126713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293839,-0.0177695) , 
5, 162.299, 1, 0, 0.447392,-0.0123955) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651926,0.00612717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0159983) , 
2, 6.02985, 1, 0, 0.678306,0.0824162) , 
2, 4.0398, 1, 0, 0.5,0.00920487)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367613,-0.00250907) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.291954,-0.0122525) , 
0, 1.07018, 1, 0, 0.32269,-0.0506144) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602724,0.00612004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.501967,-0.00341001) , 
0, 1.51946, 1, 0, 0.572836,0.0336597) , 
2, 2.03483, 1, 0, 0.5,0.00912123)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430372,-0.000285447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.658207,0.00751783) , 
2, 3.00498, 1, 0, 0.540586,0.0365863) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.479104,8.78429e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370452,-0.0118656) , 
0, 1.11032, 1, 0, 0.423361,-0.0428133) , 
6, 28.3844, 1, 0, 0.5,0.00909642)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560215,0.00493173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.429012,-0.00373729) , 
5, 64.0639, 1, 0, 0.474605,-0.00304561) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76541,0.0129471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.647756,0.00339066) , 
3, 1.35245, 1, 0, 0.742453,0.123944) , 
2, 5.00995, 1, 0, 0.5,0.00899443)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589454,0.00712443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486947,-0.000828754) , 
0, 1.10752, 1, 0, 0.533815,0.0275723) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431931,-0.0031161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273471,-0.0213789) , 
3, 1.32674, 1, 0, 0.374357,-0.0608954) , 
1, 179.884, 1, 0, 0.5,0.0088119)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507968,0.00209451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386554,-0.00797586) , 
6, 32.4698, 1, 0, 0.474605,-0.00273466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.0094103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0188806) , 
2, 7.03483, 1, 0, 0.742453,0.117931) , 
2, 5.00995, 1, 0, 0.5,0.00870578)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59356,0.00594084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437743,-0.00265851) , 
1, 155.355, 1, 0, 0.5447,0.0327573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471862,-0.000400091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315794,-0.0151127) , 
1, 111.603, 1, 0, 0.406909,-0.0419498) , 
3, 1.58708, 1, 0, 0.5,0.00852181)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339783,-0.00455588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594711,0.00496245) , 
2, 2.03483, 1, 0, 0.523621,0.0264934) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.436636,-0.00544047) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25938,-0.0275805) , 
6, 41.3278, 1, 0, 0.412393,-0.0584533) , 
0, 1.74151, 1, 0, 0.5,0.00845347)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52511,0.00367207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430333,-0.00423395) , 
0, 1.11996, 1, 0, 0.474605,-0.00227238) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.00882353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0182363) , 
2, 7.03483, 1, 0, 0.742453,0.110253) , 
2, 5.00995, 1, 0, 0.5,0.0083963)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432239,-1.30807e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662219,0.00684324) , 
2, 3.00498, 1, 0, 0.54455,0.0343738) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470997,-0.000740266) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358221,-0.0116531) , 
0, 1.39565, 1, 0, 0.431528,-0.0320648) , 
6, 26.3417, 1, 0, 0.5,0.0081856)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561769,0.00518278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459364,-0.00221199) , 
0, 1.20697, 1, 0, 0.512473,0.0162583) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.38058,-0.0100565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.218402,-0.0336228) , 
3, 1.31438, 1, 0, 0.307221,-0.118486) , 
5, 207.266, 1, 0, 0.5,0.00807006)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589176,0.00537591) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422506,-0.00357764) , 
1, 179.884, 1, 0, 0.549412,0.0325006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483043,0.000139282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332448,-0.0119337) , 
1, 111.598, 1, 0, 0.419349,-0.0322102) , 
3, 1.46724, 1, 0, 0.5,0.00791649)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499179,0.00121126) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328838,-0.0117172) , 
5, 152.188, 1, 0, 0.474605,-0.00209782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.00824083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0175861) , 
2, 7.03483, 1, 0, 0.742453,0.102581) , 
2, 5.00995, 1, 0, 0.5,0.00782684)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565549,0.00502081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447282,-0.00232993) , 
6, 28.3844, 1, 0, 0.523621,0.0233808) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532607,0.0019914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378977,-0.00976767) , 
5, 47.9068, 1, 0, 0.412393,-0.0505458) , 
0, 1.74151, 1, 0, 0.5,0.00768124)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.468589,0.00015353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293839,-0.0131779) , 
5, 162.299, 1, 0, 0.447392,-0.00847282) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.737111,0.00877919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.591872,0.00151692) , 
5, 91.6112, 1, 0, 0.678306,0.0616107) , 
2, 4.0398, 1, 0, 0.5,0.00749388)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517904,0.00206148) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.759762,0.0101665) , 
2, 5.00995, 1, 0, 0.549412,0.0300158) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474408,-0.000500881) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314108,-0.0125215) , 
1, 127.54, 1, 0, 0.419349,-0.0295241) , 
3, 1.46724, 1, 0, 0.5,0.00739613)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.339783,-0.00397862) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.594711,0.00420543) , 
2, 2.03483, 1, 0, 0.523621,0.0219826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504033,-0.000397799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358788,-0.0106248) , 
5, 61.8547, 1, 0, 0.412393,-0.0471611) , 
0, 1.74151, 1, 0, 0.5,0.0072987)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432239,5.84206e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.662219,0.00592722) , 
2, 3.00498, 1, 0, 0.54455,0.0296629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487125,0.000437241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379365,-0.00794641) , 
0, 1.11032, 1, 0, 0.431528,-0.0272528) , 
6, 26.3417, 1, 0, 0.5,0.00722834)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383947,-0.00209061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661502,0.00655871) , 
2, 2.04478, 1, 0, 0.584712,0.0443247) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520419,0.00222084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401876,-0.00527197) , 
3, 1.14371, 1, 0, 0.454617,-0.0128299) , 
5, 64.0639, 1, 0, 0.5,0.00710823)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588427,0.00549133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487037,-0.000566873) , 
0, 1.07023, 1, 0, 0.531196,0.0199484) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.390729,-0.00444133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252176,-0.0235823) , 
5, 224.667, 1, 0, 0.368227,-0.047667) , 
1, 188.061, 1, 0, 0.5,0.00700527)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507968,0.00162382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386554,-0.00596789) , 
6, 32.4698, 1, 0, 0.474605,-0.00163151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.695114,0.00570046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.822493,0.0127161) , 
2, 6.0398, 1, 0, 0.742453,0.0879937) , 
2, 5.00995, 1, 0, 0.5,0.00686595)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534443,0.00293014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322399,-0.0129343) , 
5, 207.266, 1, 0, 0.520616,0.0188715) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430274,-0.00474156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24256,-0.0244507) , 
6, 42.5808, 1, 0, 0.406974,-0.0481887) , 
0, 1.81609, 1, 0, 0.5,0.006706)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.513913,0.00157554) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.757954,0.00910261) , 
2, 5.00995, 1, 0, 0.5447,0.0240819) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471862,-0.000340826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315794,-0.0109823) , 
1, 111.603, 1, 0, 0.406909,-0.0299346) , 
3, 1.58708, 1, 0, 0.5,0.00655862)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.580771,0.00500857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391968,-0.00535381) , 
5, 157.696, 1, 0, 0.553074,0.0342417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548828,0.00241713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413166,-0.00455746) , 
5, 60.6647, 1, 0, 0.458065,-0.0154699) , 
0, 1.07023, 1, 0, 0.5,0.00647162)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52511,0.00265489) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430333,-0.00302159) , 
0, 1.11996, 1, 0, 0.474605,-0.00145599) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.00645019) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0160369) , 
2, 7.03483, 1, 0, 0.742453,0.0805555) , 
2, 5.00995, 1, 0, 0.5,0.0063196)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.361268,-0.00267767) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616956,0.00420054) , 
2, 2.01493, 1, 0, 0.555409,0.0266948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48353,0.00020991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.328134,-0.00955347) , 
3, 1.37459, 1, 0, 0.426017,-0.0212791) , 
1, 122.649, 1, 0, 0.5,0.00615106)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48778,0.00123873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.717043,0.0067743) , 
2, 4.0398, 1, 0, 0.54455,0.025091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485746,-0.000152457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357408,-0.00783884) , 
3, 1.39155, 1, 0, 0.431528,-0.0230581) , 
6, 26.3417, 1, 0, 0.5,0.00611205)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536358,0.00268646) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322276,-0.011136) , 
1, 269.827, 1, 0, 0.520616,0.0167834) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430274,-0.0042421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.24256,-0.0217679) , 
6, 42.5808, 1, 0, 0.406974,-0.0426585) , 
0, 1.81609, 1, 0, 0.5,0.00599994)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.383947,-0.00213885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.661502,0.00558654) , 
2, 2.04478, 1, 0, 0.584712,0.036506) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520419,0.00187698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401876,-0.00440561) , 
3, 1.14371, 1, 0, 0.454617,-0.0105395) , 
5, 64.0639, 1, 0, 0.5,0.00587209)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500875,0.000842051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292192,-0.0142904) , 
5, 207.266, 1, 0, 0.488222,0.00159873) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00928597) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0154162) , 
2, 7.03483, 1, 0, 0.822493,0.120545) , 
2, 6.04478, 1, 0, 0.5,0.00578988)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342428,-0.00307057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.599027,0.00353026) , 
2, 2.03483, 1, 0, 0.528208,0.0188592) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447704,-0.00246443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305016,-0.0138311) , 
4, 2.15314, 1, 0, 0.42329,-0.0303259) , 
0, 1.6172, 1, 0, 0.5,0.00563532)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.337732,-0.00331806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.596291,0.00311002) , 
2, 2.03483, 1, 0, 0.523285,0.0152008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.452842,-0.00129304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344334,-0.00930703) , 
3, 0.991221, 1, 0, 0.383671,-0.0425269) , 
6, 40.6407, 1, 0, 0.5,0.00557289)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542953,0.00255283) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403731,-0.00799795) , 
0, 2.08957, 1, 0, 0.531196,0.0157094) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378026,-0.00443586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184554,-0.0359625) , 
5, 318.208, 1, 0, 0.368227,-0.037476) , 
1, 188.061, 1, 0, 0.5,0.00552854)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584489,0.00450075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450398,-0.00138394) , 
5, 47.5406, 1, 0, 0.474605,-0.00131036) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721123,0.00559906) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.014928) , 
2, 7.03483, 1, 0, 0.742453,0.0695876) , 
2, 5.00995, 1, 0, 0.5,0.00541155)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574547,0.00403631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370144,-0.00639901) , 
5, 179.727, 1, 0, 0.553074,0.0285175) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523793,0.000881397) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385325,-0.00513396) , 
5, 80.9928, 1, 0, 0.458065,-0.0131005) , 
0, 1.07023, 1, 0, 0.5,0.00526874)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.528353,0.00178875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413244,-0.00341581) , 
6, 28.3844, 1, 0, 0.488222,0.00132056) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.00973661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0184483) , 
2, 8.00995, 1, 0, 0.822493,0.110136) , 
2, 6.04478, 1, 0, 0.5,0.00515473)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58542,0.00404844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442457,-0.00380821) , 
4, 1.63878, 1, 0, 0.555088,0.0232306) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.472423,-0.000469949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299848,-0.0106216) , 
5, 124.655, 1, 0, 0.433959,-0.0168407) , 
3, 1.32344, 1, 0, 0.5,0.00500675)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589819,0.00461875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.397077,-0.00366076) , 
5, 153.133, 1, 0, 0.559127,0.0319641) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506589,0.00048733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371104,-0.00641993) , 
6, 31.4196, 1, 0, 0.469091,-0.00917547) , 
0, 0.908628, 1, 0, 0.5,0.00494738)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.461795,0.000142541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.692614,0.00492631) , 
2, 4.0398, 1, 0, 0.515756,0.0123316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.46581,-0.00204715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.344405,-0.00998954) , 
6, 19.8207, 1, 0, 0.397153,-0.0440952) , 
0, 1.9404, 1, 0, 0.5,0.00483567)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542006,0.00187109) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.846459,0.0115451) , 
2, 6.01493, 1, 0, 0.555409,0.0210225) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487405,0.0003402) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340655,-0.00697254) , 
3, 1.28823, 1, 0, 0.426017,-0.0170015) , 
1, 122.649, 1, 0, 0.5,0.00473955)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571491,0.00317656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441161,-0.00325845) , 
4, 1.63878, 1, 0, 0.54169,0.0164822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.490577,0.00183415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371169,-0.00529117) , 
1, 47.8374, 1, 0, 0.399556,-0.0238238) , 
3, 1.65898, 1, 0, 0.5,0.00465987)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594564,0.00474658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39983,-0.00334726) , 
5, 153.133, 1, 0, 0.563357,0.0333184) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53309,0.00170463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.425555,-0.00336055) , 
6, 21.1425, 1, 0, 0.474776,-0.00687202) , 
0, 0.80918, 1, 0, 0.5,0.00457248)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579953,0.0030671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450294,-0.00131427) , 
5, 58.5561, 1, 0, 0.488222,0.0009988) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00775508) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.013863) , 
2, 7.03483, 1, 0, 0.822493,0.0989885) , 
2, 6.04478, 1, 0, 0.5,0.00445153)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520727,0.00159309) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298591,-0.0121938) , 
5, 223.789, 1, 0, 0.509805,0.00941962) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423487,-0.00537643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28125,-0.0171114) , 
3, 1.82559, 1, 0, 0.378536,-0.0587701) , 
0, 2.11444, 1, 0, 0.5,0.00432618)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.52511,0.00191841) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430333,-0.00228333) , 
0, 1.11996, 1, 0, 0.474605,-0.00145241) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768749,0.00763348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666591,0.000623647) , 
3, 1.24711, 1, 0, 0.742453,0.0583816) , 
2, 5.00995, 1, 0, 0.5,0.00422051)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284353,-0.0107626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.578415,0.00362555) , 
2, 1.06468, 1, 0, 0.562897,0.0280305) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.547994,0.00341519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.449499,-0.00217528) , 
0, 0.613581, 1, 0, 0.467534,-0.00822569) , 
6, 18.1709, 1, 0, 0.5,0.0041177)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607957,0.00490792) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378935,-0.00407233) , 
3, 2.49781, 1, 0, 0.583298,0.0382623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537848,0.00149674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412609,-0.00335003) , 
3, 1.27656, 1, 0, 0.479371,-0.0044753) , 
1, 49.0619, 1, 0, 0.5,0.00400799)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33353,-0.00289439) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.589233,0.00223874) , 
2, 2.03483, 1, 0, 0.516036,0.00968142) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476215,0.00480669) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352703,-0.0081058) , 
4, 0.553995, 1, 0, 0.363884,-0.0449998) , 
6, 48.8115, 1, 0, 0.5,0.00391837)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.579953,0.00279823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.450294,-0.00123128) , 
5, 58.5561, 1, 0, 0.488222,0.000720612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.00828089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0173474) , 
2, 8.00995, 1, 0, 0.822493,0.0910908) , 
2, 6.04478, 1, 0, 0.5,0.00390486)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551221,0.00232178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.359767,-0.00534966) , 
1, 228.947, 1, 0, 0.528208,0.0137692) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.447704,-0.00186075) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305016,-0.0111971) , 
4, 2.15314, 1, 0, 0.42329,-0.0233122) , 
0, 1.6172, 1, 0, 0.5,0.00379954)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550109,0.00255055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456684,-0.00133486) , 
6, 18.1709, 1, 0, 0.488222,0.000683547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00684232) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.012994) , 
2, 7.03483, 1, 0, 0.822493,0.0872222) , 
2, 6.04478, 1, 0, 0.5,0.00373279)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520727,0.00139946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298591,-0.0111055) , 
5, 223.789, 1, 0, 0.509805,0.00813867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503454,0.00260563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366253,-0.00879781) , 
3, 0.652708, 1, 0, 0.378536,-0.0523476) , 
0, 2.11444, 1, 0, 0.5,0.00362064)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607957,0.0045195) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378935,-0.00371081) , 
3, 2.49781, 1, 0, 0.583298,0.0350814) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.537848,0.00135798) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.412609,-0.00310795) , 
3, 1.27656, 1, 0, 0.479371,-0.00428433) , 
1, 49.0619, 1, 0, 0.5,0.00352966)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594564,0.00399805) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39983,-0.00279297) , 
5, 153.133, 1, 0, 0.563357,0.0278485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587464,0.0031513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.448439,-0.00188308) , 
5, 47.5472, 1, 0, 0.474776,-0.00625662) , 
0, 0.80918, 1, 0, 0.5,0.00345507)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489323,0.00040202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335395,-0.00754088) , 
6, 50.8542, 1, 0, 0.474605,-0.00158883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.768749,0.00685568) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.666591,0.000303475) , 
3, 1.24711, 1, 0, 0.742453,0.0507307) , 
2, 5.00995, 1, 0, 0.5,0.00337164)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.0131016) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.00794811) , 
5, 81.0341, 1, 0, 0.258243,-0.0551011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59516,0.00290731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463117,-0.000750749) , 
5, 69.5717, 1, 0, 0.516505,0.0072953) , 
2, 1.06468, 1, 0, 0.5,0.00330775)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348005,-0.00220343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606186,0.00268268) , 
2, 2.03483, 1, 0, 0.535778,0.0144047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50106,0.000380014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386239,-0.00457119) , 
6, 20.0265, 1, 0, 0.435906,-0.0166646) , 
0, 1.4183, 1, 0, 0.5,0.00327443)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562784,0.00366295) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.473799,-0.000728436) , 
0, 0.585422, 1, 0, 0.488222,0.000439827) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.0074347) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0166256) , 
2, 8.00995, 1, 0, 0.822493,0.0804038) , 
2, 6.04478, 1, 0, 0.5,0.00325741)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280955,-0.0106687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.565808,0.00209365) , 
2, 1.06468, 1, 0, 0.551661,0.0148045) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.425593,-0.00159355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.200158,-0.0274166) , 
1, 439.374, 1, 0, 0.418916,-0.0151359) , 
1, 130.826, 1, 0, 0.5,0.00315237)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483971,0.00029029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751815,0.00544918) , 
2, 5.00995, 1, 0, 0.509805,0.00720826) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423487,-0.00434355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.28125,-0.0141306) , 
3, 1.82559, 1, 0, 0.378536,-0.0473478) , 
0, 2.11444, 1, 0, 0.5,0.00313319)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607957,0.00406816) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378935,-0.00306131) , 
3, 2.49781, 1, 0, 0.583298,0.0315849) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524661,0.000725773) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.376793,-0.00397145) , 
3, 1.58886, 1, 0, 0.479371,-0.00399541) , 
1, 49.0619, 1, 0, 0.5,0.00306718)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534995,0.00149217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.324124,-0.00843331) , 
1, 269.825, 1, 0, 0.523285,0.00923456) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.444213,0.000553268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360904,-0.00608362) , 
4, 0.821775, 1, 0, 0.383671,-0.028063) , 
6, 40.6407, 1, 0, 0.5,0.00301403)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.634152,0.00685065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.552558,0.00310145) , 
4, 0.952903, 1, 0, 0.583211,0.0414616) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.493221,-2.79288e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.189405,-0.0309982) , 
5, 317.421, 1, 0, 0.489477,-0.00191015) , 
0, 0.473543, 1, 0, 0.5,0.00295885)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550109,0.00215673) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456684,-0.00118797) , 
6, 18.1709, 1, 0, 0.488222,0.000263083) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00578979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0120323) , 
2, 7.03483, 1, 0, 0.822493,0.0743871) , 
2, 6.04478, 1, 0, 0.5,0.00287489)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.466034,0.000126399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.695784,0.00363121) , 
2, 4.0398, 1, 0, 0.520113,0.00900904) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459854,-0.00140623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320279,-0.00833461) , 
1, 128.12, 1, 0, 0.40613,-0.0261989) , 
0, 1.82852, 1, 0, 0.5,0.00279639)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619082,0.00398302) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427257,-0.000925881) , 
3, 2.16228, 1, 0, 0.583298,0.0291085) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541101,0.00132291) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422813,-0.00240097) , 
3, 1.18734, 1, 0, 0.479371,-0.00375391) , 
1, 49.0619, 1, 0, 0.5,0.00276919)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00181533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00458981) , 
2, 2.02985, 1, 0, 0.607623,0.0300401) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00418022) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.0011155) , 
0, 0.473537, 1, 0, 0.476025,-0.00337616) , 
5, 47.5406, 1, 0, 0.5,0.00271168)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502806,0.000518164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.348593,-0.00603166) , 
6, 50.8542, 1, 0, 0.488222,0.000207341) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.00655318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0158983) , 
2, 8.00995, 1, 0, 0.822493,0.069838) , 
2, 6.04478, 1, 0, 0.5,0.00266082)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514921,0.000961902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224144,-0.0198746) , 
1, 400.647, 1, 0, 0.509805,0.006227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406622,-0.00441394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265145,-0.0157488) , 
4, 2.15688, 1, 0, 0.378536,-0.0423481) , 
0, 2.11444, 1, 0, 0.5,0.00259867)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589853,0.003362) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404077,-0.00344989) , 
3, 1.63756, 1, 0, 0.54727,0.0178046) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522039,0.000445686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383214,-0.00377596) , 
5, 91.1569, 1, 0, 0.467971,-0.00779134) , 
4, 1.07029, 1, 0, 0.5,0.00254685)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560485,0.00215968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273065,-0.0143514) , 
5, 278.867, 1, 0, 0.553074,0.0164983) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543452,0.00226643) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.437601,-0.00203928) , 
1, 47.8278, 1, 0, 0.458065,-0.00850867) , 
0, 1.07023, 1, 0, 0.5,0.00252883)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.591655,0.00317178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483636,-0.000686615) , 
0, 1.65444, 1, 0, 0.562897,0.0195463) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560331,0.00361276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45595,-0.00144034) , 
0, 0.46467, 1, 0, 0.467534,-0.00633921) , 
6, 18.1709, 1, 0, 0.5,0.00247347)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495208,0.000253353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257444,-0.0128478) , 
5, 256.836, 1, 0, 0.488222,7.40059e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00511812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0113397) , 
2, 7.03483, 1, 0, 0.822493,0.0662145) , 
2, 6.04478, 1, 0, 0.5,0.00240451)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.0110943) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.00564585) , 
5, 81.0341, 1, 0, 0.258243,-0.0431529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.59516,0.0023165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463117,-0.000659553) , 
5, 69.5717, 1, 0, 0.516505,0.00545916) , 
2, 1.06468, 1, 0, 0.5,0.00235253)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.587563,0.00298221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.402992,-0.00341787) , 
3, 1.63756, 1, 0, 0.544758,0.0149884) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476393,-0.00053161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.315631,-0.0085065) , 
6, 48.8115, 1, 0, 0.461137,-0.00864448) , 
4, 1.16482, 1, 0, 0.5,0.00233898)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.597568,0.00327633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459327,-0.00271715) , 
0, 1.95449, 1, 0, 0.580047,0.0233748) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549581,0.00210459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.452767,-0.00143408) , 
3, 0.813237, 1, 0, 0.475416,-0.00414266) , 
1, 57.2383, 1, 0, 0.5,0.00232289)    );
  // itree = 100
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.552348,0.00214205) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464655,-0.000869622) , 
0, 0.784318, 1, 0, 0.488222,5.82351e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.00594315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.015303) , 
2, 8.00995, 1, 0, 0.822493,0.0626145) , 
2, 6.04478, 1, 0, 0.5,0.00226245)    );
  // itree = 101
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476829,6.16465e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700436,0.00317386) , 
2, 4.0398, 1, 0, 0.531196,0.00774565) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378938,-0.00245477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.197701,-0.0221804) , 
1, 441.489, 1, 0, 0.368227,-0.0212204) , 
1, 188.061, 1, 0, 0.5,0.0022009)    );
  // itree = 102
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483971,0.000200677) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751815,0.00436443) , 
2, 5.00995, 1, 0, 0.509805,0.00540396) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.525157,0.00542757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.369967,-0.00629567) , 
3, 0.582335, 1, 0, 0.378536,-0.037389) , 
0, 2.11444, 1, 0, 0.5,0.00220754)    );
  // itree = 103
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00233063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326006,-0.00867394) , 
4, 2.66954, 1, 0, 0.562897,0.0177887) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560331,0.00330062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45595,-0.0013343) , 
0, 0.46467, 1, 0, 0.467534,-0.00590378) , 
6, 18.1709, 1, 0, 0.5,0.0021623)    );
  // itree = 104
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00176091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00400098) , 
2, 2.02985, 1, 0, 0.607623,0.0255271) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00342648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.000964428) , 
0, 0.473537, 1, 0, 0.476025,-0.0031082) , 
5, 47.5406, 1, 0, 0.5,0.00210863)    );
  // itree = 105
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601568,0.00328178) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445844,-0.0015914) , 
3, 1.36831, 1, 0, 0.54727,0.0151842) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483442,-0.000338421) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.320851,-0.00761229) , 
6, 48.8115, 1, 0, 0.467971,-0.00680445) , 
4, 1.07029, 1, 0, 0.5,0.00207678)    );
  // itree = 106
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607957,0.00312339) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378935,-0.00260944) , 
3, 2.49781, 1, 0, 0.583298,0.0236933) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541101,0.00103036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.422813,-0.00197189) , 
3, 1.18734, 1, 0, 0.479371,-0.00330275) , 
1, 49.0619, 1, 0, 0.5,0.00205588)    );
  // itree = 107
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.348005,-0.00165715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.606186,0.00190524) , 
2, 2.03483, 1, 0, 0.535778,0.00988211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45918,-0.000756426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31322,-0.00758863) , 
4, 2.15314, 1, 0, 0.435906,-0.0120656) , 
0, 1.4183, 1, 0, 0.5,0.00201957)    );
  // itree = 108
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555952,0.00157007) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330149,-0.0078853) , 
1, 269.829, 1, 0, 0.54455,0.0104951) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534522,0.00308477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41714,-0.00223615) , 
0, 0.477622, 1, 0, 0.431528,-0.0109793) , 
6, 26.3417, 1, 0, 0.5,0.00203054)    );
  // itree = 109
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523646,0.000659535) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371938,-0.00273722) , 
5, 124.649, 1, 0, 0.488222,1.525e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00425321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0104944) , 
2, 7.03483, 1, 0, 0.822493,0.0563911) , 
2, 6.04478, 1, 0, 0.5,0.00200169)    );
  // itree = 110
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.523117,0.000905294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.310823,-0.00627524) , 
5, 207.266, 1, 0, 0.509805,0.00485412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557306,0.00883239) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373548,-0.00548436) , 
3, 0.511962, 1, 0, 0.378536,-0.0337506) , 
0, 2.11444, 1, 0, 0.5,0.00197054)    );
  // itree = 111
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00160373) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00365474) , 
2, 2.02985, 1, 0, 0.607623,0.0231775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532709,0.0018306) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45528,-0.00123442) , 
4, 0.857601, 1, 0, 0.476025,-0.00280272) , 
5, 47.5406, 1, 0, 0.5,0.0019304)    );
  // itree = 112
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550109,0.00157298) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456684,-0.000900575) , 
6, 18.1709, 1, 0, 0.488222,1.85835e-06) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843177,0.00753154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73302,0.000405285) , 
0, 1.67838, 1, 0, 0.822493,0.053936) , 
2, 6.04478, 1, 0, 0.5,0.00190226)    );
  // itree = 113
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600318,0.00294682) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46369,-0.00169892) , 
0, 1.95647, 1, 0, 0.583298,0.0217183) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554305,0.00194338) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45709,-0.00116955) , 
3, 0.808121, 1, 0, 0.479371,-0.00306372) , 
1, 49.0619, 1, 0, 0.5,0.00185544)    );
  // itree = 114
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.357899,-0.00144387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.61527,0.00202193) , 
2, 2.03483, 1, 0, 0.546091,0.0111231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502468,0.000194181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.368836,-0.00358838) , 
1, 127.535, 1, 0, 0.449467,-0.00840688) , 
0, 1.20697, 1, 0, 0.5,0.00180696)    );
  // itree = 115
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550567,0.0016062) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.463441,-0.000821374) , 
4, 1.16482, 1, 0, 0.503757,0.00293537) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372341,0.00526738) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.184951,-0.0259059) , 
0, 0.48426, 1, 0, 0.218265,-0.0820759) , 
5, 317.421, 1, 0, 0.5,0.00181668)    );
  // itree = 116
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518434,0.000740901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235282,-0.0183031) , 
5, 289.351, 1, 0, 0.51462,0.0048727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.464146,0.00450333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.345581,-0.00570283) , 
4, 0.57631, 1, 0, 0.358727,-0.0280696) , 
6, 50.8542, 1, 0, 0.5,0.00178327)    );
  // itree = 117
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558833,0.0021323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.471187,-0.000580891) , 
0, 0.647577, 1, 0, 0.488222,-5.02131e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.7891,0.00379537) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.883669,0.0100003) , 
2, 7.03483, 1, 0, 0.822493,0.0511749) , 
2, 6.04478, 1, 0, 0.5,0.00175474)    );
  // itree = 118
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.00955849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.00368578) , 
5, 81.0341, 1, 0, 0.258243,-0.0338145) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561816,0.00125315) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415368,-0.00154397) , 
5, 108.126, 1, 0, 0.516505,0.00413204) , 
2, 1.06468, 1, 0, 0.5,0.001707)    );
  // itree = 119
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483971,0.000143908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751815,0.00370277) , 
2, 5.00995, 1, 0, 0.509805,0.00431697) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503454,0.00321946) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.366253,-0.00547019) , 
3, 0.652708, 1, 0, 0.378536,-0.0306112) , 
0, 2.11444, 1, 0, 0.5,0.00170801)    );
  // itree = 120
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00142199) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00330861) , 
2, 2.02985, 1, 0, 0.607623,0.0208965) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00290324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.00081392) , 
0, 0.473537, 1, 0, 0.476025,-0.00260392) , 
5, 47.5406, 1, 0, 0.5,0.00167744)    );
  // itree = 121
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.607957,0.00262629) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378935,-0.00232789) , 
3, 2.49781, 1, 0, 0.583298,0.0196483) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.554305,0.00180382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45709,-0.00107916) , 
3, 0.808121, 1, 0, 0.479371,-0.00280246) , 
1, 49.0619, 1, 0, 0.5,0.00165396)    );
  // itree = 122
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00186719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326006,-0.00733126) , 
4, 2.66954, 1, 0, 0.562897,0.0140336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529551,0.000765576) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41896,-0.00187934) , 
3, 1.15568, 1, 0, 0.467534,-0.0047932) , 
6, 18.1709, 1, 0, 0.5,0.00161636)    );
  // itree = 123
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518434,0.000673284) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235282,-0.0169171) , 
5, 289.351, 1, 0, 0.51462,0.00440716) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.454755,0.00223045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335158,-0.00588667) , 
3, 0.714545, 1, 0, 0.358727,-0.025623) , 
6, 50.8542, 1, 0, 0.5,0.00159084)    );
  // itree = 124
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.540798,0.00110327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447018,-0.00100078) , 
0, 1.07023, 1, 0, 0.488222,-0.000104594) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.00453322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0141971) , 
2, 8.00995, 1, 0, 0.822493,0.0473799) , 
2, 6.04478, 1, 0, 0.5,0.00156856)    );
  // itree = 125
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605367,0.00293859) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447147,-0.00150365) , 
3, 1.36831, 1, 0, 0.550918,0.0134362) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.508734,0.00014565) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.350991,-0.00396412) , 
5, 121.649, 1, 0, 0.473505,-0.00465899) , 
4, 0.975761, 1, 0, 0.5,0.00153414)    );
  // itree = 126
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.592812,0.0025924) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502239,7.87488e-05) , 
3, 0.811923, 1, 0, 0.523621,0.00592227) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.418005,-0.00174899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.14184,-0.0326927) , 
5, 250.152, 1, 0, 0.412393,-0.0147405) , 
0, 1.74151, 1, 0, 0.5,0.00153417)    );
  // itree = 127
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.600318,0.00252801) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46369,-0.00145283) , 
0, 1.95647, 1, 0, 0.583298,0.0184982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483568,-0.000140685) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338673,-0.00887884) , 
0, 2.28844, 1, 0, 0.479371,-0.00269865) , 
1, 49.0619, 1, 0, 0.5,0.00150885)    );
  // itree = 128
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505245,0.000317484) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.335955,-0.00523035) , 
6, 59.0251, 1, 0, 0.495166,0.000528647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.0108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,0.000547092) , 
4, 1.34234, 1, 0, 0.883669,0.0759323) , 
2, 7.01493, 1, 0, 0.5,0.0014668)    );
  // itree = 129
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00136083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00302649) , 
2, 2.02985, 1, 0, 0.607623,0.0188877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00265153) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.000755644) , 
0, 0.473537, 1, 0, 0.476025,-0.0024599) , 
5, 47.5406, 1, 0, 0.5,0.00142924)    );
  // itree = 130
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30296,-0.00522014) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615818,0.00308508) , 
2, 2.03483, 1, 0, 0.558758,0.017587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.50445,0.000105733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.351462,-0.004279) , 
6, 44.7261, 1, 0, 0.485209,-0.00265786) , 
4, 0.763074, 1, 0, 0.5,0.00141348)    );
  // itree = 131
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491715,9.29154e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187208,-0.0191175) , 
1, 441.529, 1, 0, 0.488222,-0.000121137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.807806,0.0042009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0137091) , 
2, 8.00995, 1, 0, 0.822493,0.0435713) , 
2, 6.04478, 1, 0, 0.5,0.00141839)    );
  // itree = 132
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.609281,0.00255024) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511948,0.000115862) , 
4, 1.26117, 1, 0, 0.562897,0.012402) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478579,-0.00022377) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.337196,-0.00550217) , 
0, 2.09029, 1, 0, 0.467534,-0.00428777) , 
6, 18.1709, 1, 0, 0.5,0.00139425)    );
  // itree = 133
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.604472,0.00220855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.370495,-0.00322042) , 
3, 2.49781, 1, 0, 0.580047,0.015602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.530699,0.00115363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.447669,-0.00123536) , 
4, 0.975761, 1, 0, 0.475416,-0.00300503) , 
1, 57.2383, 1, 0, 0.5,0.00136691)    );
  // itree = 134
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.594564,0.00211358) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39983,-0.00203568) , 
5, 153.133, 1, 0, 0.563357,0.0136399) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.510434,0.00021334) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375905,-0.00274376) , 
6, 32.2849, 1, 0, 0.474776,-0.00355105) , 
0, 0.80918, 1, 0, 0.5,0.0013442)    );
  // itree = 135
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574656,0.00159851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470915,-0.000474616) , 
1, 57.2383, 1, 0, 0.495166,0.000464022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.0102989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,0.000308612) , 
4, 1.34234, 1, 0, 0.883669,0.0702172) , 
2, 7.01493, 1, 0, 0.5,0.00133188)    );
  // itree = 136
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.156487,-0.0333647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.261455,-0.00500466) , 
4, 0.606493, 1, 0, 0.258243,-0.0280735) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589605,0.00139197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455579,-0.000561638) , 
5, 75.0794, 1, 0, 0.516505,0.00329912) , 
2, 1.06468, 1, 0, 0.5,0.0012942)    );
  // itree = 137
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491715,8.13156e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187208,-0.0174105) , 
1, 441.529, 1, 0, 0.488222,-0.000123847) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843177,0.00618927) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73302,-0.000625147) , 
0, 1.67838, 1, 0, 0.822493,0.0404067) , 
2, 6.04478, 1, 0, 0.5,0.00130427)    );
  // itree = 138
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603491,0.00262721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.514468,0.000197929) , 
3, 0.811923, 1, 0, 0.535778,0.00683141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45918,-0.000484804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.31322,-0.00597072) , 
4, 2.15314, 1, 0, 0.435906,-0.0086601) , 
0, 1.4183, 1, 0, 0.5,0.00128173)    );
  // itree = 139
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00124444) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00269575) , 
2, 2.02985, 1, 0, 0.607623,0.01665) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.002411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.000676022) , 
0, 0.473537, 1, 0, 0.476025,-0.00215902) , 
5, 47.5406, 1, 0, 0.5,0.00126764)    );
  // itree = 140
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55864,0.00134855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469959,-0.000515519) , 
0, 0.80918, 1, 0, 0.495166,0.000440219) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00989753) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,9.80126e-05) , 
4, 1.34234, 1, 0, 0.883669,0.0658245) , 
2, 7.01493, 1, 0, 0.5,0.00125372)    );
  // itree = 141
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30296,-0.00477744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615818,0.00276451) , 
2, 2.03483, 1, 0, 0.558758,0.0155573) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495037,-4.53376e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314113,-0.00655409) , 
6, 59.0251, 1, 0, 0.485209,-0.00239368) , 
4, 0.763074, 1, 0, 0.5,0.00121636)    );
  // itree = 142
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.476829,-7.57147e-06) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.700436,0.0021029) , 
2, 4.0398, 1, 0, 0.531196,0.00469025) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462533,0.00229256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352518,-0.00295834) , 
3, 0.61859, 1, 0, 0.368227,-0.0134335) , 
1, 188.061, 1, 0, 0.5,0.00122095)    );
  // itree = 143
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518849,0.000570972) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.278857,-0.00666454) , 
1, 327.059, 1, 0, 0.509805,0.00322052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557306,0.00858725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373548,-0.00394873) , 
3, 0.511962, 1, 0, 0.378536,-0.023444) , 
0, 2.11444, 1, 0, 0.5,0.00122881)    );
  // itree = 144
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00148006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326006,-0.006286) , 
4, 2.66954, 1, 0, 0.562897,0.0109257) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529551,0.000638271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41896,-0.00152519) , 
3, 1.15568, 1, 0, 0.467534,-0.0038086) , 
6, 18.1709, 1, 0, 0.5,0.00120768)    );
  // itree = 145
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574656,0.00144269) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470915,-0.000427643) , 
1, 57.2383, 1, 0, 0.495166,0.00041977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00957128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,2.37504e-05) , 
4, 1.34234, 1, 0, 0.883669,0.0624722) , 
2, 7.01493, 1, 0, 0.5,0.00119181)    );
  // itree = 146
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30296,-0.00438605) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.615818,0.00258761) , 
2, 2.03483, 1, 0, 0.558758,0.0146152) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.495037,-4.70809e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.314113,-0.00601391) , 
6, 59.0251, 1, 0, 0.485209,-0.00222958) , 
4, 0.763074, 1, 0, 0.5,0.001158)    );
  // itree = 147
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.566134,0.00190447) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487536,-0.000216724) , 
4, 0.763074, 1, 0, 0.503192,0.00186259) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179715,-0.0254652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269117,0.00457302) , 
6, 59.029, 1, 0, 0.208588,-0.0629839) , 
5, 333.944, 1, 0, 0.5,0.00115997)    );
  // itree = 148
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.577523,0.00194696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.114111,-0.0442986) , 
1, 547.826, 1, 0, 0.575179,0.0161568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.570183,0.00242129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475672,-0.000563587) , 
3, 0.628409, 1, 0, 0.485339,-0.00179619) , 
0, 0.585422, 1, 0, 0.5,0.0011336)    );
  // itree = 149
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612639,0.00195207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434935,-0.00902433) , 
0, 2.31371, 1, 0, 0.607623,0.0151195) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550956,0.00136789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453511,-0.00080865) , 
3, 0.819471, 1, 0, 0.476025,-0.0020207) , 
5, 47.5406, 1, 0, 0.5,0.00110193)    );
  // itree = 150
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.548074,0.000889903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.453528,-0.000705396) , 
0, 1.07023, 1, 0, 0.495166,0.00034413) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00926786) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,6.29496e-05) , 
4, 1.34234, 1, 0, 0.883669,0.0595691) , 
2, 7.01493, 1, 0, 0.5,0.001081)    );
  // itree = 151
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.621735,0.00245707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529298,0.000383816) , 
0, 0.970754, 1, 0, 0.562897,0.0100515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560268,0.000936782) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430296,-0.00113347) , 
5, 64.4866, 1, 0, 0.467534,-0.00359136) , 
6, 18.1709, 1, 0, 0.5,0.00105333)    );
  // itree = 152
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.00780712) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.00142052) , 
5, 81.0341, 1, 0, 0.258243,-0.0234694) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.561816,0.000852506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.415368,-0.00108169) , 
5, 108.126, 1, 0, 0.516505,0.00271195) , 
2, 1.06468, 1, 0, 0.5,0.00103879)    );
  // itree = 153
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.550109,0.000961855) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456684,-0.000583918) , 
6, 18.1709, 1, 0, 0.488222,-0.000174816) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843177,0.00552658) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73302,-0.000939414) , 
0, 1.67838, 1, 0, 0.822493,0.0344501) , 
2, 6.04478, 1, 0, 0.5,0.00104522)    );
  // itree = 154
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585552,0.0016667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332718,-0.0139) , 
5, 276.402, 1, 0, 0.583298,0.013757) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483273,-0.000111995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.334244,-0.00788756) , 
0, 2.30087, 1, 0, 0.479371,-0.00212936) , 
1, 49.0619, 1, 0, 0.5,0.00102403)    );
  // itree = 155
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57902,0.00202666) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484574,-0.000240524) , 
0, 0.473543, 1, 0, 0.495166,0.000304578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00891553) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,-9.35211e-05) , 
4, 1.34234, 1, 0, 0.883669,0.0560572) , 
2, 7.01493, 1, 0, 0.5,0.000998241)    );
  // itree = 156
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589855,0.00193648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.499437,-2.67584e-05) , 
3, 0.811923, 1, 0, 0.520616,0.00380141) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.434713,-0.000808757) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.273043,-0.00769745) , 
3, 2.22437, 1, 0, 0.406974,-0.0118253) , 
0, 1.81609, 1, 0, 0.5,0.000966544)    );
  // itree = 157
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612682,0.00209668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502829,-0.000313603) , 
5, 98.8942, 1, 0, 0.583298,0.0130987) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56628,0.00220275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468712,-0.000599914) , 
3, 0.629668, 1, 0, 0.479371,-0.00204675) , 
1, 49.0619, 1, 0, 0.5,0.000959575)    );
  // itree = 158
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.533912,0.000542387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.228888,-0.0157288) , 
3, 3.19284, 1, 0, 0.531196,0.00383494) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44502,-0.00558783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.358251,-0.00114611) , 
5, 81.6041, 1, 0, 0.368227,-0.0113032) , 
1, 188.061, 1, 0, 0.5,0.000937157)    );
  // itree = 159
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491715,5.22631e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187208,-0.0145244) , 
1, 441.529, 1, 0, 0.488222,-0.000209153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.843177,0.00521451) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.73302,-0.000951852) , 
0, 1.67838, 1, 0, 0.822493,0.0319884) , 
2, 6.04478, 1, 0, 0.5,0.000925348)    );
  // itree = 160
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562842,0.00162569) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487201,-0.000195916) , 
4, 0.763074, 1, 0, 0.502327,0.00151243) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224867,-0.0223038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316819,-0.00257872) , 
6, 110.019, 1, 0, 0.27439,-0.0571183) , 
6, 93.7511, 1, 0, 0.5,0.000913802)    );
  // itree = 161
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57902,0.00189435) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.484574,-0.000230946) , 
0, 0.473543, 1, 0, 0.495166,0.000239905) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00853579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,-0.000227364) , 
4, 1.34234, 1, 0, 0.883669,0.0524412) , 
2, 7.01493, 1, 0, 0.5,0.000889384)    );
  // itree = 162
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39492,-0.00122672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683048,0.00221103) , 
2, 2.02985, 1, 0, 0.607623,0.0131131) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532709,0.00109466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45528,-0.000772358) , 
4, 0.857601, 1, 0, 0.476025,-0.00186688) , 
5, 47.5406, 1, 0, 0.5,0.000862195)    );
  // itree = 163
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483971,5.00016e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751815,0.00250636) , 
2, 5.00995, 1, 0, 0.509805,0.00248543) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382631,-0.00259055) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717787,-0.0593762) , 
6, 74.3666, 1, 0, 0.378536,-0.0192554) , 
0, 2.11444, 1, 0, 0.5,0.000861497)    );
  // itree = 164
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511325,0.000347781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339138,-0.00428738) , 
6, 62.1259, 1, 0, 0.503192,0.0014572) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.419267,0.0141442) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.181477,-0.0192708) , 
0, 0.36116, 1, 0, 0.208588,-0.0536512) , 
5, 333.944, 1, 0, 0.5,0.000860086)    );
  // itree = 165
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.588944,0.00153948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400287,-0.00554115) , 
5, 207.371, 1, 0, 0.583298,0.0119929) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.56628,0.00209683) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.468712,-0.000564687) , 
3, 0.629668, 1, 0, 0.479371,-0.00190497) , 
1, 49.0619, 1, 0, 0.5,0.000853706)    );
  // itree = 166
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00117826) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326006,-0.00561173) , 
4, 2.66954, 1, 0, 0.562897,0.00850687) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.529551,0.000515971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.41896,-0.00124717) , 
3, 1.15568, 1, 0, 0.467534,-0.00312663) , 
6, 18.1709, 1, 0, 0.5,0.000833982)    );
  // itree = 167
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.55864,0.00103385) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.469959,-0.000415991) , 
0, 0.80918, 1, 0, 0.495166,0.0002151) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858102,0.00471102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0120404) , 
2, 8.02985, 1, 0, 0.883669,0.0495684) , 
2, 7.01493, 1, 0, 0.5,0.000829145)    );
  // itree = 168
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605353,-0.00147122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6082,0.00207601) , 
6, 13.0732, 1, 0, 0.607623,0.012216) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00179936) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.000522984) , 
0, 0.473537, 1, 0, 0.476025,-0.0017338) , 
5, 47.5406, 1, 0, 0.5,0.000807598)    );
  // itree = 169
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.00695885) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.000817546) , 
5, 81.0341, 1, 0, 0.258243,-0.0197358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519893,0.00038165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374501,-0.0055803) , 
0, 2.31333, 1, 0, 0.516505,0.00219058) , 
2, 1.06468, 1, 0, 0.5,0.000789334)    );
  // itree = 170
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646333,0.0045116) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604903,0.0163212) , 
6, 47.9159, 1, 0, 0.640532,0.0566705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534769,0.000523572) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.434266,-0.000955362) , 
0, 1.4183, 1, 0, 0.498739,0.000282787) , 
3, 0.436675, 1, 0, 0.5,0.000784338)    );
  // itree = 171
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522545,0.00045276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.357611,-0.0041125) , 
6, 59.0251, 1, 0, 0.51424,0.00221867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.321635,-0.00593503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.298298,0.000995427) , 
6, 35.4399, 1, 0, 0.311981,-0.0184802) , 
1, 269.825, 1, 0, 0.5,0.000761343)    );
  // itree = 172
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.564734,0.000826158) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.456627,-0.000489428) , 
1, 81.7675, 1, 0, 0.495166,0.000165429) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00802911) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,-0.00055009) , 
4, 1.34234, 1, 0, 0.883669,0.0476185) , 
2, 7.01493, 1, 0, 0.5,0.000755831)    );
  // itree = 173
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589853,0.00167341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.404077,-0.00260551) , 
3, 1.63756, 1, 0, 0.54727,0.00708405) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517011,0.000451413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.421305,-0.00145724) , 
0, 1.19682, 1, 0, 0.467971,-0.00355602) , 
4, 1.07029, 1, 0, 0.5,0.000741507)    );
  // itree = 174
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.584882,0.00124939) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.403453,-0.00187588) , 
1, 202.94, 1, 0, 0.562897,0.00800682) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560268,0.000787947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430296,-0.000949433) , 
5, 64.4866, 1, 0, 0.467534,-0.00298979) , 
6, 18.1709, 1, 0, 0.5,0.000753994)    );
  // itree = 175
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.651887,0.00440481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.420151,-0.00268577) , 
1, 206.815, 1, 0, 0.600175,0.0271169) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504622,9.95793e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265616,-0.00583545) , 
1, 327.059, 1, 0, 0.496296,-0.00022301) , 
3, 0.508575, 1, 0, 0.5,0.000751845)    );
  // itree = 176
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492001,4.26493e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.2054,-0.0106011) , 
5, 317.421, 1, 0, 0.488222,-0.000224936) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.837167,0.0042556) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678609,-0.00354481) , 
1, 197.768, 1, 0, 0.822493,0.0271861) , 
2, 6.04478, 1, 0, 0.5,0.000740911)    );
  // itree = 177
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.569674,0.00173076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194575,-0.0244597) , 
1, 392.473, 1, 0, 0.561092,0.0119301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.506944,8.98604e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354167,-0.00274016) , 
6, 44.7261, 1, 0, 0.487556,-0.00154908) , 
4, 0.71581, 1, 0, 0.5,0.000731855)    );
  // itree = 178
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57755,0.00114267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474911,-0.000287145) , 
1, 49.0619, 1, 0, 0.495166,0.000182466) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858102,0.00419173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.011562) , 
2, 8.02985, 1, 0, 0.883669,0.0445526) , 
2, 7.01493, 1, 0, 0.5,0.000734511)    );
  // itree = 179
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612137,0.00287167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454277,-0.00288245) , 
4, 1.60353, 1, 0, 0.582289,0.0163971) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507137,0.000127832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346312,-0.00302017) , 
6, 50.1618, 1, 0, 0.491926,-0.000822823) , 
3, 0.604442, 1, 0, 0.5,0.000715832)    );
  // itree = 180
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.483971,3.58054e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.751815,0.00219282) , 
2, 5.00995, 1, 0, 0.509805,0.00209612) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557306,0.00798335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.373548,-0.00287307) , 
3, 0.511962, 1, 0, 0.378536,-0.0164847) , 
0, 2.11444, 1, 0, 0.5,0.000708221)    );
  // itree = 181
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617995,-0.00250932) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.646212,0.00744986) , 
0, 0.635051, 1, 0, 0.640532,0.0513446) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.574646,0.00135604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483953,-0.000253167) , 
0, 0.585422, 1, 0, 0.498739,0.000249647) , 
3, 0.436675, 1, 0, 0.5,0.000704121)    );
  // itree = 182
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504804,0.000204717) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.222383,-0.0119391) , 
3, 3.19284, 1, 0, 0.502327,0.00116504) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224867,-0.0195372) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316819,-0.0014091) , 
6, 110.019, 1, 0, 0.27439,-0.0464628) , 
6, 93.7511, 1, 0, 0.5,0.000678745)    );
  // itree = 183
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.558106,0.00121793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.48611,-0.000189356) , 
4, 0.785251, 1, 0, 0.501732,0.00104398) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229867,-0.00559657) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21227,-0.0245495) , 
2, 1.0199, 1, 0, 0.223279,-0.0594703) , 
4, 3.24443, 1, 0, 0.5,0.000667519)    );
  // itree = 184
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572192,0.00100117) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326006,-0.00486879) , 
4, 2.66954, 1, 0, 0.562897,0.00718134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.473676,-0.000196076) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.326036,-0.00510849) , 
0, 2.22679, 1, 0, 0.467534,-0.00272138) , 
6, 18.1709, 1, 0, 0.5,0.000649993)    );
  // itree = 185
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57755,0.00107509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474911,-0.000277838) , 
1, 49.0619, 1, 0, 0.495166,0.00012263) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.858102,0.00395389) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.938347,0.0112727) , 
2, 8.02985, 1, 0, 0.883669,0.0420856) , 
2, 7.01493, 1, 0, 0.5,0.000644725)    );
  // itree = 186
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58815,0.00139814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.442261,-0.0029052) , 
4, 1.6453, 1, 0, 0.558064,0.0052016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45704,-0.00126029) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401161,0.00148899) , 
4, 1.83019, 1, 0, 0.441337,-0.00398913) , 
3, 1.25154, 1, 0, 0.5,0.000629824)    );
  // itree = 187
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605353,-0.00158979) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6082,0.0018482) , 
6, 13.0732, 1, 0, 0.607623,0.0103369) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.567939,0.00157521) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46395,-0.000460498) , 
0, 0.473537, 1, 0, 0.476025,-0.00153362) , 
5, 47.5406, 1, 0, 0.5,0.000628978)    );
  // itree = 188
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.646333,0.00370387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.604903,0.015216) , 
6, 47.9159, 1, 0, 0.640532,0.048485) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502487,0.000120601) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361364,-0.00438222) , 
0, 2.3009, 1, 0, 0.498739,0.000187251) , 
3, 0.436675, 1, 0, 0.5,0.000616844)    );
  // itree = 189
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.284804,-0.0063325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.235335,-0.000206388) , 
5, 81.0341, 1, 0, 0.258243,-0.0166379) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517598,0.000258133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.207141,-0.0210754) , 
3, 3.20137, 1, 0, 0.516505,0.00177013) , 
2, 1.06468, 1, 0, 0.5,0.000593733)    );
  // itree = 190
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660137,0.00404257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.557624,0.000612118) , 
3, 0.538534, 1, 0, 0.562897,0.00681134) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.560268,0.000691181) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.430296,-0.000832028) , 
5, 64.4866, 1, 0, 0.467534,-0.00261324) , 
6, 18.1709, 1, 0, 0.5,0.000595345)    );
  // itree = 191
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498654,7.04092e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191213,-0.0111907) , 
1, 441.529, 1, 0, 0.495166,9.15407e-05) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898617,0.00721809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.795588,-0.00116247) , 
4, 1.34234, 1, 0, 0.883669,0.0402292) , 
2, 7.01493, 1, 0, 0.5,0.000590926)    );
  // itree = 192
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302079,-0.00454895) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.617979,0.00203576) , 
2, 2.03483, 1, 0, 0.561092,0.0102587) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573261,0.000994482) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.462544,-0.000565914) , 
1, 55.7986, 1, 0, 0.487556,-0.00138796) , 
4, 0.71581, 1, 0, 0.5,0.000582878)    );
  // itree = 193
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.497468,6.59473e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.88735,0.00613837) , 
2, 7.01493, 1, 0, 0.502327,0.00103765) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.224867,-0.0180108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316819,-0.0012802) , 
6, 110.019, 1, 0, 0.27439,-0.0422833) , 
6, 93.7511, 1, 0, 0.5,0.00059533)    );
  // itree = 194
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568867,0.00139829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489972,-0.000144417) , 
4, 0.71581, 1, 0, 0.503192,0.00102938) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179715,-0.0202079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.269117,0.00875785) , 
6, 59.029, 1, 0, 0.208588,-0.0401833) , 
5, 333.944, 1, 0, 0.5,0.000582832)    );
  // itree = 195
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612137,0.00251866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454277,-0.00260063) , 
4, 1.60353, 1, 0, 0.582289,0.0141848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.507137,0.000108122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346312,-0.00267104) , 
6, 50.1618, 1, 0, 0.491926,-0.00076025) , 
3, 0.604442, 1, 0, 0.5,0.000575138)    );
  // itree = 196
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.585493,0.00046213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.498767,0.0041967) , 
4, 1.82722, 1, 0, 0.570914,0.00912321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.644284,0.00646834) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.481348,-0.000263498) , 
3, 0.436675, 1, 0, 0.482776,-0.00150589) , 
0, 0.647577, 1, 0, 0.5,0.000571268)    );
  // itree = 197
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578638,0.00102776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.445983,-0.00186707) , 
4, 1.63878, 1, 0, 0.549412,0.00383775) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.430708,-0.00160741) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.393785,0.00157848) , 
4, 1.83019, 1, 0, 0.419349,-0.00482135) , 
3, 1.46724, 1, 0, 0.5,0.0005481)    );
  // itree = 198
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.505069,0.000191874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363584,-0.00404544) , 
0, 2.31333, 1, 0, 0.501732,0.000881156) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.190961,-0.0214953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263567,-0.000865387) , 
4, 3.50908, 1, 0, 0.223279,-0.0523631) , 
4, 3.24443, 1, 0, 0.5,0.000549922)    );
  // itree = 199
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605353,-0.00157165) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.6082,0.00170441) , 
6, 13.0732, 1, 0, 0.607623,0.00932154) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545432,0.00132571) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.464166,-0.000468519) , 
6, 14.0855, 1, 0, 0.476025,-0.00141972) , 
5, 47.5406, 1, 0, 0.5,0.00053714)    );
   return;
};
 
// Clean up
inline void ReadBDTG::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDTG::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
